### ISSUE TITLE
New comment on MUI for Figma (Community) by E G

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#109]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3Dt9PZ_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPW5wOO0jRlJb7-2F5EIMxe7bUb6d29tNyB0Nb3nPF8BxXOp7M-2BuAdkZSyhLCrcYF-2B0yCMTJ8cVdWAYr3oA5GndCVmlEmh0ye02OtFVlbleRT17kC2tDL460AWv7sRqAOXkz8yOFIcpNi3jg4m424oMaoU1rPB-2FdjWNzHLR7qgq69ZeftIra1NXdjrmSIuz1RTR2Xqgay14VWx21zbiTEmq0WVOYssqwmc0dXgyTcLBGk-2BQ-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on MUI for Figma v5.9.0 (Community)<b>MUI for Figma v5.9.0 (Community)</b>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro2xsEoIP4rsp4cMKFbG6fzjSFIE71y8TrnDJMIuqVQoKIFdb_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPW5wOO0jRlJb7-2F5EIMxe7bRg-2FTJ2mEcj4QR2qrhu1FxVZDTm-2FhtPvTjhUcyJJ4xConQjrKmAOUYrl0O-2Fk66aaENLAAt7kwmKJxMu7rp0hXiaxc2-2BiXZ0yCPlLpdS99AIufo8Yzm8pkzCf0DC0IdG5mykVqJ8csONUZOJjCFay2RZV3o4GLr96BvHvdA9yNWNyKTBKvCr-2BjIuhPcXSx0NXHNfgiApzef2AjdomyV5q2iA-3D-3D"
><img
src="https://www.gravatar.com/avatar/337b9faf7bf24bb143e607eaf18e2f3c?size=240&default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_e_v2.png"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro2xsEoIP4rsp4cMKFbG6fzjSFIE71y8TrnDJMIuqVQoKJGY9_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPW5wOO0jRlJb7-2F5EIMxe7bBIl9KLqucqqyUi7mTRrbP-2FxjdI-2F9Z3qRyGo-2BCJ3Ueu4K0PctOsHEGChn9-2BtFupGQGlUY9wGMSUfywIe8KwXY7SDKhyn43u36O92tws8Y970W4gaLsn5c41Ox8wzoQqq4EYofkapP3ivQ2ircXh32kuv2y8YKbUTCtY9z10fgDZD6xD51RHKQVO-2FUlW8h4VoAmN8u5cM7M00ZBAIqaTWLBQ-3D-3D"
>E G</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Is there a way to import my code build which uses MUI Core into Figma without dealing with .json configuration files for both design system and components? I am so lost
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfMUO67n7PeqwOO-2B6XpKis6U4qrKpBcAXQ-2FQokO0niIp4INxL_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPW5wOO0jRlJb7-2F5EIMxe7baLkYr2PqFtDsDaUWhCyA36hz2uyxDhX-2BYJSXog1-2BXQ50Fh6WTOzaKwqVyrnQu9aSqdeRwuhGdsSEhYmlYIVeShi8PFblo8YmGQTApVqIA6axX2t0LvGECMIf5bI1s1r-2FfHXSwz-2FA4xiIURdeM2VFjCbrO76vu-2FZMnIball-2ByK-2FfxmSNlIjysgZ7-2FGhffh-2FblvduessS9uW5N-2FdjyfrrBaA-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by oliviertassinari** [comment]
It's not possible yet, I have created #110 to keep track of this use case.
