### ISSUE TITLE
Figma: Autocomplete in disabled mode should be gray and without clear option

### ISSUE THREAD

**Issue by WilliamZimmermann** [mui/mui-design-kits#113]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When disabling an Autocomplete Field with Outlined variant, the field become dotted, arrow down (to open the menu) is still black and the "clear" X doesn't disappear.

### Expected behavior 🤔

For Autocomplete Field with outlined variant, in disabled mode, the right style should be a sort of **gray** and solid, not dotted. Also, arrow down should be disabled and "clear" should disappear. 

### Steps to reproduce 🕹

![image](https://user-images.githubusercontent.com/6362750/195860934-89fba82a-1582-4fd3-9d96-de32f1b71eb3.png)

Steps:
1. Insert an Autocomplete Field
2. Change it to "Outlined" variant
3. Change his State to Disabled
4. Has Value should be false
5. Notice the errors commented above

### Context 🔦

This issue affect us because our layout shows the wrong layout for our devs.

### Your environment 🌎

| Software            | Version               |
| ------------------- | --------------------- |
| Design file version | v5.9.0                |
| Design tool         | Figma |
| etc.                |                       |

**Comment by oliviertassinari** [comment]
@WilliamZimmermann The Autocomplete doesn't have a "Disabled" state, but the Outlined input does (what you have provably set, hence why it doesn't update the close icon). This sounds like a feature request to me.
