### ISSUE TITLE
[figma] Use text properties for components

### ISSUE THREAD

**Issue by davidsl4** [mui/mui-design-kits#114]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Figma has introduced text properties for components, and they can be used to set the text using the properties panel.

### Examples 🌈

For example, in buttons, there should be a new property called content (or label), and its value should be displayed on the button.

**Comment by oliviertassinari** [comment]
@davidsl4 Thanks for the suggestion, I can see the feature covered in https://help.figma.com/hc/en-us/articles/5579474826519-Explore-component-properties: 

<a href="https://www.youtube.com/watch?v=iIq8FLt1hUY&t=218s">
<img width="687" alt="Screenshot 2022-10-18 at 00 49 50" src="https://user-images.githubusercontent.com/3165635/196298085-24764354-69f7-4f92-be96-a72edbfbc48d.png">
</a>

I have tried this quickly with the menu item:

<img width="605" alt="Screenshot 2022-10-18 at 00 51 02" src="https://user-images.githubusercontent.com/3165635/196298204-548539b0-b50b-470c-9f9e-c2bb344da075.png">

I'm not sure to fully understand the use case. It feels similar to editing the text value directly.

Regarding the name, does `children` work?

**Comment by adrianmanea** [comment]
Hi David, thank you for the suggestion. I may be biased because I always work with CMD/CTRL + click to select and edit text layer contents. I find it simpler than editing from the component properties. But it's definitely an improvement and not a regression.
