### ISSUE TITLE
How do I transfer ownership?

### ISSUE THREAD

**Issue by Fredasaurus** [mui/mui-design-kits#116]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I have modified the MUI for Figma framework on my personal account. I now need to transfer this to a new work account. How do I do this and keep all the functionality intact? Thanks.

**Comment by oliviertassinari** [comment]
@Fredasaurus I think that the simplest in your case is to save a local copy: https://help.figma.com/hc/en-us/articles/8403626871063-Save-a-local-copy-of-files.
