### ISSUE TITLE
[question] Is mui figma version the same as @mui/material version? Are they in sync?

### ISSUE THREAD

**Issue by AlexanderKositsyn** [mui/mui-design-kits#118]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

**Comment by adrianmanea** [comment]
Yes, it is up to date with the current APIs even though @mui/material moves faster than the Figma library.

**Comment by AlexanderKositsyn** [comment]
If Im using mui/material version 5.4 , do i have to use 5.4 version of mui figma?

**Comment by adrianmanea** [comment]
Nope! The Figma library can be used with any code version. We release only significant updates.

**Comment by AlexanderKositsyn** [comment]
Thank you!

**Comment by oliviertassinari** [comment]
@AlexanderKositsyn To be even more specific: when we release a new version of the design kits, we aim to match with the latest version of the React components, so we use the latest version used to release the React component MUI Core. For example, if we release a new version of Figma today, it would be v5.10.11: https://github.com/mui/material-ui/releases/tag/v5.10.11

MUI X, follows a different versioning strategy but it's the same we aim to support the latest version of the MUI X release when we release a new version of Figma.
