### ISSUE TITLE
Can't publish library (initial publish)

### ISSUE THREAD

**Issue by marcinbauer85** [mui/mui-design-kits#119]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I'm trying to publish a fresh download of MUI 5.4.0, but when trying to publish all elements the UI doesn't progress and there is a "Publish failed" toast.
The only way to publish is to publish components almost one at a time.

### Your environment 🌎

Latest figma app, macOS Ventura.

**Comment by adrianmanea** [comment]
Hei, this is a common problem because of the library being large. The solution is to simply wait with the window focused. The initial push is the most annoying.

**Comment by marcinbauer85** [comment]
I tried let it sit for 5hours and it just stood there (but Figma was responsive). I had to publish the first few components 1-by-1. The library is amazing, but I think it would need breaking up into smaller files. I know this poses problems in using it, and since Figma mentioned something about W3C DS specs in the current Schema conference it might be good to wait for what they have prepared.

**Comment by oliviertassinari** [comment]
I'm closing as it's unlikely something we can fix. I hope Figma will improve this experience overtime.
