### ISSUE TITLE
[figma] v5.9.0 UI kit footer is wrong

### ISSUE THREAD

**Issue by ivanbachev** [mui/mui-design-kits#120]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

<img width="2992" alt="Screen Shot 2022-11-08 at 22 54 48" src="https://user-images.githubusercontent.com/1560160/200673303-6e86d8c0-9f02-4ef0-ac2d-62a554bf5588.png">

### Current behavior 😯

The footer component instances shows the old version of the UI kit - v5.4.0

### Expected behavior 🤔

The component needs to be updated to show the correct version - v5.9.0

### Your environment 🌎

| Software            | Version               |
| ------------------- | --------------------- |
| Design file version | v5.9.0               |
| Design tool         | Figma |
| etc.                |                       |

**Comment by oliviertassinari** [comment]
@ivanbachev Thanks for the report. We did it wrong in the last release. Let's get the next release correct 😁
