### ISSUE TITLE
[figma] Blue swatches color styles are wrong

### ISSUE THREAD

**Issue by ivanbachev** [mui/mui-design-kits#122]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

![MUI Figma UI kit - Blue vs Material Design - Blue](https://user-images.githubusercontent.com/1560160/201310999-0f98509b-8b8c-44fc-be83-3e3690388c83.png)

### Current behavior 😯

The Blue hue color swatches defined as styles in the Figma UI kit are wrong.

Some of the swatches are different from those shown here - https://m2.material.io/resources/color/ - and do not follow a smooth gradation from light to dark.  

### Expected behavior 🤔

The Blue hue color swatches in MUI Figma UI kit should match those seen on https://m2.material.io/resources/color/ and https://mui.com/material-ui/customization/color/#color-palette 

### Your environment 🌎

| Software            | Version               |
| ------------------- | --------------------- |
| Design file version | v5.9.0                |
| Design tool         | Figma |
| etc.                |                       |

**Comment by adrianmanea** [comment]
Yes, you are correct, we already had it corrected in the upcoming update.
