### ISSUE TITLE
New comment on MUI for Figma (Community) by David Sanders

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#127]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DvEHg_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmO18NQzUPX0bBhedIMZUDDyoKUC33HydH5RfRtK-2FTrlIL2KbO1fOArcH7JM4mdFpWWzqsJlvBaZUKpBkleWIgQ3uvlFQtbF-2FEkBatf0XDVhOxD8Qo-2BLhHER6R8hUkFYWtymzKLi5a7j8Nhz3hy90inn1mKb2Ni5EWbO1qTwqL9-2B07JTuK56JhAbfGzKpe-2F9yPQsfPZTv5DCxQuhld0DMYK83zRM-2B1Kek45CeDQaLYzUVA-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>MUI for Figma v5.9.0 (Community)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4ec488bgtPjnUJVFxoM3rrATJwGyAw-2FWRXylEQZCD4CBbEm_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmO18NQzUPX0bBhedIMZUDDy6Nd-2FxHMxE3XYosi2HhntgZSBtFNypS7GkBPkWZylPY0BdRumtVuEM7qojNSZ53qNHRb2Cir9wXRhUAm-2FvB1U3Z9K7zzvnyDNP7-2B08a9-2FAevtTcetFfRq8jdt7fM0HZVB-2FcS9NeCRHVQk-2FdAGrJxg-2Bxt7UBZ441DL4Flkwm56O0jy60iMa-2BWJCDrTV8bLrXeyVQMpYa-2BgXC-2BkhUML4Eawqg-3D-3D"
><img
src="https://s3-alpha.figma.com/profile/33f69c11-cc88-4cc4-ba15-01efa285fcef"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4ec488bgtPjnUJVFxoM3rrATJwGyAw-2FWRXylEQZCD4CWWtf_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmO18NQzUPX0bBhedIMZUDDy6ie-2Fey3VLBTFZRBokaZ7a-2FuGz8Eb1g-2BW92TEGIqOlKj626UdcWKvyl-2FHmLqzuYE0YIcyEiq716X-2BEqAonBc-2FNjNwZcIbOvzVUbk-2FgNuzZ-2FZWfGnS3UvixfPHhwyC-2FKNmL81ZQEhHAo4zTC-2B2Xax7VFNHtiuTHK3Sti1uAebF5Eez1vZVnqdK56givsG6-2BWzt4B7XPogVw2EId-2FxM-2F96ieQ-3D-3D"
>David Sanders</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
zaldrian Awesome! Thank you for the clarification!
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfA98sFvP23LYGi0zLCLw5rZmA4Gs47bCCC-2BGz9U6u0GymmKo_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmO18NQzUPX0bBhedIMZUDDyEkDRRrOUFowua3jjmTa782HBhjsOSy5gOdirqDQjsKBNx71vqHIuelkfgabB7Jnm0jeBptbfq-2BlSZzhNm9Wm-2B9NgXrCiugfFEbEvtMOCc4wjpOzDYP43DElKZVnvq-2FMESkdD5FIYOpGROsAqAmRjyrFKn9PnNB6js3OF2Dq12HinVgkeCrYb42vZFn6-2FtMys-2BwlMt2KGStruKPjmngri6g-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
Answered on Figma community.
