### ISSUE TITLE
New comment on MUI for Figma (Community) by Alfredo Dominguez

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#128]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DWriP_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMo5ynAP-2B-2BFYAkUwHhJgdeaF2QPdpyrtDWogHZ0rKJaryEGVhssGzoObe-2Bo1wE5O9tzy0JHrVKPX54f1M-2F5rKpPNV10Z8Cm31gumcLszhOmtqK1lTSsww-2F8jCtgZyWFcum-2FkD7v-2FrOpQvoFcT0FEOIfBIIEOzfk4MNEecF1HajRC-2Bte0W3FbKt8hjLVHXtzzwbd39ThyM3cLz85Fo2vugJJOA1fWIz8RkPMdv9yl08uVw-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>MUI for Figma v5.9.0 (Community)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kroxmMz9XNfrI78EEYUIWo8AXlWPYWQmaA0Br8HAcQbHmjdrr1_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMo5ynAP-2B-2BFYAkUwHhJgdeaDhe-2BdH0FRDayDCFz51QuYgtdW-2FlzcLrAFDVW0m92dmQFIksbya-2F5Dpec3cfd1GY07gi-2B3E5pZSkffd66OCS34pbTlXSxUDpjUpA8RgxiCcVmNX8TACU-2FNqu6pBNpSeZVmdRROktbWZdDr-2B6cCbPMFP0tXVRajwDjU8Wrp7VJ6eEPeojYcxDoRCpAgHwrFX52HQ8pvPQ7A1Gy4PSf6WJ-2BBw-3D-3D"
><img
src="https://www.gravatar.com/avatar/1404985997ba5cfa68cb30368747ff91?size=240&default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_a_v2.png"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kroxmMz9XNfrI78EEYUIWo8AXlWPYWQmaA0Br8HAcQbHmjJ9J0_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMo5ynAP-2B-2BFYAkUwHhJgdeaRPAHH9M6pMgrFfOU5cYZqRwKdEhPtbuzpYxWIHgQucmxVB9nKiCPIn2oT9cn6fS8-2FS1O4lAFyJmjvi-2BwXhgF0wI-2FYLnYNG5TmivY4XzYtBRyyWohZ8mOLTn-2FIvIdZcmkVBNr99nO-2FMyx9mCMQjbTR80X-2FW0DWGhG8TP8oGfJ-2BdApTEfMNLkpblFK5-2FjcAG3gRKw3OV-2Fel1Je1tJon1wXAg-3D-3D"
>Alfredo Dominguez</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Text Field&#47;Filled nor Text Field&#47;Outlined exist on this copy of Figma design!
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfF4rAl3z-2BMlnEck5F71G3oNCwfqtkaFfnqb9m4cZi0E8UeP__Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMo5ynAP-2B-2BFYAkUwHhJgdea8T5Lp-2FwIRUn3p3pli2baLVgFZS0BvfkL-2BcKklApvUanQRZpbC-2Fe787poHDkQF-2B4-2F6-2F5mxUr5v4fHHr7NA0dTyD-2FRY3gUHgzNpLxFSjwlAFdZbGrxZGBNlAxbpTWkypYP3o8QJy2jo35c-2FSzxwY7UHLZjIVzX-2F8FcekXmQso2JsSoMth-2FmYDqgcYnk4EbwByLfwnFocOfVsAmaWT5s6fhDg-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
Answered.
