### ISSUE TITLE
[figma] Make the Figma tree structure closer to the React dom structure

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-design-kits#13]
The user feedback, from an exigent user (Coursera) https://mui.zendesk.com/agent/tickets/1146

> We expect our Figma components to be created in such a way so that the nesting of objects in the hierarchical tree on the left (see image) matches the code and our API's. 
I know that it's highly unlikely that your components will match what we do 100%, but I wondered if they might be a good start or a close-ish match. They weren't really, so they aren't really a good starting point for us.

## Your Environment 🌎

v5.0.0

**Comment by adrianmanea** [comment]
Still tinkering on this issue, I'm wondering if this is the right path we want to go with the library. 

### MUI Experimental
![image](https://user-images.githubusercontent.com/5917515/140317480-609c6eb6-dfad-48b5-a59c-ecb05402cc15.png)

### Google's Material 3 Design Kit 
![image](https://user-images.githubusercontent.com/5917515/140319566-9944b684-3851-44b3-ba9e-9cdfbf703a17.png)

From my perspective, this shouldn't scare or niche designers in the way of requiring development knowledge.

**Comment by oliviertassinari** [comment]
> From my perspective, this shouldn't scare or niche designers in the way of requiring development knowledge.

I didn't get this part. But looking at your screenshot, I personally really like it. Looking at the Slider, I feel that it's perfect 👌 

<img width="173" alt="Screenshot 2021-11-05 at 00 21 04" src="https://user-images.githubusercontent.com/3165635/140433556-d86d0b98-c14f-430f-be94-825a151aba81.png">

We don't mention "Root" for the root element, and we add a space for the underlying component slots, like "Slider Track".

**Comment by adrianmanea** [comment]
I think we went forward towards this issue with the next update (5.9.0) we tried to match as closely as possible the props available to the API.

**Comment by oliviertassinari** [comment]
@adrianmanea Great thanks. It wasn't super clear if this designer wanted us to match the DOM or React API, but I assume it's about the latter.

I believe it's related to a new initiative that we stared for the documentation of the React components. We are better documenting the DOM structure of each React component, e.g. https://mui.com/base/react-slider/#anatomy and the React structure in https://mui.com/x/api/data-grid/data-grid/#slots cc @samuelsycamore @mnajdova
