### ISSUE TITLE
[sketch] Text Field icon adornment alignment

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-design-kits#131]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Open Sketch v5.4.0
2. Go to the Examples, Text field page.

### Current behavior 😯

<img width="356" alt="Screenshot 2022-12-13 at 13 55 14" src="https://user-images.githubusercontent.com/3165635/207323708-28d6a295-f0c4-468f-91d1-78b54885fd76.png">

### Expected behavior 🤔

Correct visual output.

### Context 🔦

https://mui.zendesk.com/agent/tickets/5902

**Comment by adrianmanea** [comment]
This is solved in the deployed update.

**Comment by oliviertassinari** [comment]
"deployed update", meaning v5.4.1.
