### ISSUE TITLE
[sketch] TextField resizing break

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-design-kits#132]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Open MUI for Sketch v5.4.0
2. Go to Examples, Select
3. Resize the selects

### Current behavior 😯

<img width="562" alt="Screenshot 2022-12-13 at 14 56 53" src="https://user-images.githubusercontent.com/3165635/207349537-bb252e24-8c89-4f99-8767-71530957bb86.png">

### Expected behavior 🤔

Keep the correct shape:

<img width="487" alt="Screenshot 2022-12-13 at 14 57 10" src="https://user-images.githubusercontent.com/3165635/207349745-8c6014ec-9f0f-44d0-98f5-d9ca960f436a.png">

### Context 🔦

https://mui.zendesk.com/agent/tickets/5907

**Comment by adrianmanea** [comment]
This is solved on the deployed version.

**Comment by oliviertassinari** [comment]
So fixed in v4.5.1
