### ISSUE TITLE
New comment on MUI for Figma (Community) by Joaquin Bonifacino

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#134]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DMe1D_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmM-2F7JEjhF0j0PwGBYFYww-2BuH8uiGQVPn5BzSd4td7vrlvetCDdiCPqvy9J1ccsAyNCSUsUOEUVqI7FqvjyXeEJabfZPQ34PEsoQv-2BAO1uTZdWZd681NT9eYY4sqxIKdLdydCWiXnARqMDfC4IJrk1hNtWIy5cz1aj2LPZz0W7AdLn7Hnpblrr1-2BqqjNI0rXRxDW01Ydx6iDZ38L3zToTERugZs7zVxV1ONps4dF3swgHg-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>MUI for Figma (Community version) (with Material UI)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro0J2FDIiAewpanEfX1T8Bxze-2B2kkmu4uqLgFoVgjIYU5-krb_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmM-2F7JEjhF0j0PwGBYFYww-2BuwMgppGalZjvAkOv5JaOgRTXD5mEOkBNqgMxy8CFkyHlmqGzFRoEUhpmCS1x2KGTYh2j771tQngc-2F-2BR-2B3jEISJdGuTy9wb1SmFDVxsNwuL8rK2rf-2FoCooWoPwKuW76tZlwpmrcqYlsd3sKPydbilNIsw3uAhrDNIfRGOz-2B4CzgbLABLPom4g7QynwTLOhvUsMsiQZpZO4BECQym4Z-2F2SDjQ-3D-3D"
><img
src="https://www.gravatar.com/avatar/5f56dc6f1d99cade87840a2d3dec34a9?size=240&default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_j_v2.png"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro0J2FDIiAewpanEfX1T8Bxze-2B2kkmu4uqLgFoVgjIYU5e2LI_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmM-2F7JEjhF0j0PwGBYFYww-2BuQSV-2BSNgnVg1XSgwJ-2BjQzRgTLdsGdbGoqYaEQXrudxDwjRkwPm3OmNfcbcvZcrtSVHXa-2FYkc745GPccCC1KmIYS05R5QednXNR2MjSWg8pVFXMqdopGguuvmQWZgYTJtujyof62gzwJiqnHvCMV3k4OqlZo-2FseMYPhX47MOOySSBPZ6mTq8psPjUXPi4I4k0TVuQrqZW6ikUkwPrNf87vzA-3D-3D"
>Joaquin Bonifacino</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Hi iam totally new to figma, when i copypaste any component it stays purple and i cant drag anything inside it, is that because this is the free version or? even unlocking every component didnt changed anything
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfLbn5IkcXKSKHfLv-2BMb55zrUVcseikiFxeCUNT771JvnGdz0_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmM-2F7JEjhF0j0PwGBYFYww-2BuV3TlA88rGG0l0enVqyZBaXOLHhY3R-2BTEd5kUqGzy5pDdhTOYJPDPoyZ4X6genrEQN9U3Cp0gJMssh-2F8XJFn-2BhwiBYBOGYf6UXDnaeh1NS6k0PBSaqmT1UWIdTVa6wcGP5HkiuBJlcb17DkgSllZEA9jlTdlhqYurhtg6d-2F8SjfmkVX8KoNPc1pWSun1zmyCUWC-2BxXlwGwWvqRYOAvcP3mw-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by oliviertassinari** [comment]
Answered on Figma's file page.
