### ISSUE TITLE
[Bug] Background color component Alert mismatch with Figma's design kit

### ISSUE THREAD

**Issue by phongdang707** [mui/mui-design-kits#137]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Hi, we're currently trying to use the MUI Alert component but we found some mismatch between the background colors, and we think we found the root cause.

### Current behavior 😯

On [Alert Component page](https://mui.com/material-ui/react-alert/), the background variant color are:

- error: #fdeded
- warning: #fff4e5
- info: #e5f6fd
- success: #edf7ed

![image](https://user-images.githubusercontent.com/40537969/210505884-38f3db38-855a-4bcc-aba7-c96eda689f0a.png)

### Expected behavior 🤔

However, on our [MUI for Figma Material Pro v5.9.0](https://mui.com/store/items/figma-react/) which should be similar to [this community version](https://www.figma.com/community/file/912837788133317724), the color for the background are:

- error: #fbeaea
- warning: #fdf0e6
- info: #e6f3fa
- success: #eaf2ea

![image](https://user-images.githubusercontent.com/40537969/210506022-74497b85-126d-4995-885c-335edcbea7f3.png)

### Context 🔦

Our design team is using the Figma version and they are confused because of this mismatch. We're hoping for both to use the same background colors

We have also gone in and check for the code of the Alert component and it seems like this is because of [this condition](https://github.com/mui/material-ui/blob/9e53a715c2786dad865d6ff327192d10f3517f8c/packages/mui-material/src/Alert/Alert.js#L60)

I think change from `getBackgroundColor(theme.palette[color].light, 0.9)` to `getBackgroundColor(theme.palette[color].main, 0.9)`

![image](https://user-images.githubusercontent.com/40537969/210508185-da0305f3-ebe0-4d6d-ad85-6da354c41c17.png)

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by oliviertassinari** [comment]
@phongdang707 interesting, on v5.11.0, I see the following for the error background color:

- React: #FDEDED
- Figma: #FBEAEA

<img width="342" alt="Screenshot 2023-01-05 at 14 06 16" src="https://user-images.githubusercontent.com/3165635/210786936-d9787f19-3fc8-4142-ac57-375cb38963bf.png">

We can fix this. The code is using this token `lighten(theme.palette.error.light, 0.9)` in light mode. Token studio doesn't support it https://docs.tokens.studio/available-tokens/color-tokens. The closest would be `rgba({error.light},0.1)` but this would be a mess with the opacity layer.

**Comment by adrianmanea** [comment]
I'm hoping Tokens Studio releases the color modifier soon: https://github.com/tokens-studio/figma-plugin/issues/1166 —  the roadmap says this January. This helps with issues at hand, I think they may use the same lighten and darken dependencies.

**Comment by vladmosienko-unicreo** [comment]
Why for Alerts `.light` and `.dark` is used ? If e.g. for LinearProgress, Slider, Switch, `.main` is used in lighten/darken fns? It makes alert background almost white if  I setup much lighter color in theme config for `light` prop, e.g:
```
warning: {
          main: '#F6BA1E',
          dark: '#C79209',
          light: '#FFFCF3',
          contrastText: '#ffffff',
}
```
Here first alert is just `severity="warning"` (so it takes `.light` from theme cfg and lighten it), second has inlined `backgroundColor: (theme) => lighten(theme.palette.warning.main, 0.9)`

![image](https://github.com/mui/mui-design-kits/assets/124776941/69fa3f69-85a1-4d91-a241-014a815279cf)

If i am wrong in understanding how it should be used/configured, please let me know

**Comment by LukaszSecuritas** [comment]
I would also love to know @vladmosienko-unicreo, did you figure that out?
