### ISSUE TITLE
Autocomplete Component Breaks/Doesn't work from the start.

### ISSUE THREAD

**Issue by dustindahlberg** [mui/mui-design-kits#142]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Issues:
1. Clear value icon is ever-present (even when "no value" is selected), and hiding it breaks the component.
![Screen Shot 2023-01-09 at 4 39 53 PM](https://user-images.githubusercontent.com/122321899/211422711-747046ec-7efe-43c3-b8f0-c60a0c61b4ec.png)
2. Selecting Active when the field has no value breaks the layout when it has been resized.
![Screen Shot 2023-01-09 at 4 40 49 PM](https://user-images.githubusercontent.com/122321899/211422960-32ee706c-344b-4a25-9180-5620aff329a8.png)

There are also conflicts in prototyping because the components have internal interactions that override prototyping in the design file. For example, tapping on the autocomplete opens a blank list of items instead of my curated list on the next screen.

### Your environment 🌎

| Software            | Version               |
| ------------------- | --------------------- |
| Design file version | v5.11.0                |
| Design tool         | Figma |
| etc.                |                       |

**Comment by adrianmanea** [comment]
Hei Dustin, you are correct right, we missed this one but it's really easy to solve it. Attached is a video.

https://user-images.githubusercontent.com/5917515/211512891-4f4a7426-914d-4f6e-ac44-40179d721b35.mov

**Comment by adrianmanea** [comment]
> For example, tapping on the autocomplete opens a blank list of items instead of my curated list on the next screen.

I think you are saying that in the present mode (interactions prototype) the values of your Menu do not persist. That is true because it loses referrers and we haven't figured out a way yet — a solution is to simply keep the Menu Active. Here's a demo:


https://user-images.githubusercontent.com/5917515/211521716-97bf368d-f432-4c11-927f-1b8e370d5024.mov

**Comment by dustindahlberg** [comment]
Also found a bug with the hover event for the dropdown when the elevation is set to outline. The width of the hover event no longer extends the width of the dropdown.
![Screen Shot 2023-01-10 at 8 44 55 AM](https://user-images.githubusercontent.com/122321899/211582703-906e4c24-bd05-4066-a766-a5d7273cdecc.png)
![Screen Shot 2023-01-10 at 8 45 12 AM](https://user-images.githubusercontent.com/122321899/211582748-1b93a362-1936-43b8-b9a4-66923510ece7.png)

**Comment by adrianmanea** [comment]
That's not a bug, it's the way Figma works, unfortunately, items go back to their defined fixed width. You will need to manually set the items back to 'Fill Container'.
