### ISSUE TITLE
How do you notify licensees that there is a new version?

### ISSUE THREAD

**Issue by charisehansen** [mui/mui-design-kits#143]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Just noticed the new design file. I'm wondering how you notify people of the latest file?

**Comment by oliviertassinari** [comment]
@charisehansen Thanks for the reminder. I have scheduled the emails and documented the process so it can be delegated https://mui-org.notion.site/Design-kits-Release-7f96355005f6432ebf3379430d8b36ce.
