### ISSUE TITLE
Snackbar background color doesn't match documentation

### ISSUE THREAD

**Issue by dustindahlberg** [mui/mui-design-kits#145]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Dragged snack bar from list of assets to my figma file. The component in the library shows a grey background, but it is white when I try to use it. 

Snackbar in library
![Screen Shot 2023-01-16 at 11 18 26 AM](https://user-images.githubusercontent.com/122321899/212737355-71109e52-6a0c-4f0a-9169-18f13d8bfe34.png)

Snackbar after I pulled it into my design file from assets panel
![Screen Shot 2023-01-16 at 11 18 16 AM](https://user-images.githubusercontent.com/122321899/212737418-5f7bc580-122b-4454-b508-950e78f556a4.png)

### Current behavior 😯

 It appears Figma is resetting the background colors for the paper component within the Snackbar. I wouldn't expect to have to set a gradient and custom color before I could use a component.

### Expected behavior 🤔

I would expect styles to be consistent with what is in the library and not reset when I attempt to use a component. (I would also expect the colors being used to be styles set in the library).

### Your environment 🌎

| Design file version | v5.11.0                |
| Design tool         | Figma |

**Comment by adrianmanea** [comment]
I can reproduce the behavior only if I change the elevation level which resets the background color. I don't know how to force the paper to keep the custom background color yet. Thank you for reporting!
