### ISSUE TITLE
[Token Studio Setup] + [Access to older versions of Figma File] 

### ISSUE THREAD

**Issue by smeidu** [mui/mui-design-kits#146]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

A basic question on the Token Setup: Core Tokens like **Font Family** are not sitting within a global Set, but can be found in light/base, light/components, dark/base, dark/components. I can't find a way to change the base font globally. Do I miss something?

Also: I see lots of road blocks with the new Token Version of the MUI File. Is there a link to download the latest-pre-Token version.

### Your environment 🌎

v5.11.0

**Comment by adrianmanea** [comment]
<img width="404" alt="image" src="https://user-images.githubusercontent.com/5917515/213424110-f1d66bce-e36d-4fd0-b6b5-d6d4849b643d.png">

**Comment by adrianmanea** [comment]
The global is actually the `fontFamilies.roboto` token. You can simply rename it to `fontFamilies.global` and change your font there. Tokens Studio will automatically rename where it's being used, so no extra effort. The reason why is this way by default is that people might use multiple font families.

<img width="404" alt="image" src="https://user-images.githubusercontent.com/5917515/213424471-78fc8a8a-e8ad-4cea-b842-9c104a3b34ec.png">

You can use customize the library without the plugin at all. You can look at it as a utility plugin!

> Also: I see lots of road blocks with the new Token Version of the MUI File. Is there a link to download the latest-pre-Token version.

Can you name any other road block? I understand it can feel 'sketchy' to use the plugin being at it's early stage. Happy to send the previous version but it doesn't have a lot of the new features. Just send an email to [figma@mui.com](mailto:figma@mui.com)

**Comment by adrianmanea** [comment]
I understand the frustration, we've also had a crash once in a while but very rarely. Hopefully, Figma will announce a native solution to Tokens. As I mentioned in my previous comment, the plugin is totally optional, one can use it only for enabling modes.

**Comment by mr-burns-cb** [comment]
I have this issue also. I can't seem to get Token Studio to change the text-styles in the file. Roboto just keeps on showing up. Can't figure out why it's not working.

**Comment by adrianmanea** [comment]
Hi @mr-burns-cb we totally apologize for that, I know what's wrong and we intend to release a quick fix by the end of this month. For the Typography, there is a small typo in the Tokens Studio. Rename the "Typography" group into small case "typography".

We did the small caps renaming lastly and we ended up with this typo in prod.

<img width="404" alt="image" src="https://user-images.githubusercontent.com/5917515/214309119-90cc3f71-3030-43c9-a5bb-afbef9a556fa.png">

**Comment by oliviertassinari** [comment]
Would it make sense to add docs for this in https://mui.com/figma/getting-started/?

**Comment by adrianmanea** [comment]
I was thinking we could release a quick fix by the end of this month so we can solve it for good?

**Comment by mr-burns-cb** [comment]
I think it's solved. Just have to correct another typo. Attached here, thanks to @adrianmanea for helping out. It works awesome.

<img width="657" alt="Screenshot 2023-01-25 at 14 51 28" src="https://user-images.githubusercontent.com/113112709/214581345-3ec96a0b-8b1c-4ee2-868f-d4e617f89f04.png">

**Comment by coreyfromtesouro** [comment]
@mr-burns-cb yea I spotted the Components token issue yesterday as well. Also, @adrianmanea if it's helpful, here are a few additional issues i've spotted.

1. The headings variant's have become unlinked from the Typography component.
2. The filled variant's of the Alert's components still reference the "alerts-description" global style, when the other have changed to the body2 class.
3. It would visually appear a majority of the design tokens have become unlinked. In the example image below, I show the elevation tokens for example. It seems link theres still somewhat of a link, as changes still appear to take place globally at time, however visually, it does not show a link in the token inspection. Not sure if that's an issue on Design Tokens side or not.

<img width="1172" alt="type-component-issue" src="https://user-images.githubusercontent.com/123583051/214642150-97e8658a-d56b-4650-9385-1507609a7e0c.png">
<img width="1254" alt="alert-description-issue" src="https://user-images.githubusercontent.com/123583051/214642159-79309fa1-f42b-452b-9efc-09ef73fd4174.png">
<img width="1394" alt="token-unlinking-issue" src="https://user-images.githubusercontent.com/123583051/214642162-8d1f0137-bb9a-4c74-87a5-6396dc070ed1.png">

**Comment by coreyfromtesouro** [comment]
Another small inconsistency, the filled / warning / alert component is referencing the background / paper-elevation color token when it should be referencing the color warning / contrast token.
<img width="2132" alt="Screenshot 2023-01-25 at 1 03 31 PM" src="https://user-images.githubusercontent.com/123583051/214646202-02e09f3e-2d46-4928-b3db-b0154e67cf97.png">

**Comment by adrianmanea** [comment]
Thank you for reporting this @coreyfromtesouro 

> The headings variant's have become unlinked from the Typography component.

Yes, only from the typography table. It requires resetting the component.

> It would visually appear a majority of the design tokens have become unlinked.

Although it is not showing in the tokens studio the linkage (highlighting the token based on the selected layer) changing the elevation works as expected from the plugin. Clearly a visual bug from their end.

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/5917515/214792007-2341c9a9-96da-4a46-b78e-fc3bbab83eb7.png">

> The filled variants of the Alert's components still reference the "alerts-description" global style

That is correct. Only the filled variant uses body2, font-weight: medium - the rest are using base body2

> the filled / warning / alert component is referencing the background / paper-elevation color 

I couldn't understand where the color is coming from honestly, but it wasn't the contrast in my tests when I did them. Maybe @oliviertassinari can help me understand the default color here: https://github.com/mui/material-ui/blob/master/packages/mui-material/src/Alert/Alert.js#L84

**Comment by coreyfromtesouro** [comment]
Hey @adrianmanea just another quick call out, the base colors in design tokens are also unlinked from figma's local styles are they are in a folder called "colors". To relink these with the design tokens, all the base colors will have to be renamed with the prefix "colors." to match the naming convention see in local styles. I.E. "colors.grey.400"

<img width="1427" alt="current" src="https://user-images.githubusercontent.com/123583051/214953541-fab5c775-fc79-4c85-8c60-214d50f858da.png">
<img width="1350" alt="fix" src="https://user-images.githubusercontent.com/123583051/214953547-c52b6107-96a5-47d7-9d7b-e8005d513a1b.png">
<img width="465" alt="fix-2" src="https://user-images.githubusercontent.com/123583051/214953550-6e003ac1-8a7b-4c22-b698-25d5013e7681.png">
0"

**Comment by adrianmanea** [comment]
Ah, correct. These are actually static, but I think one can mutate the colors.
