### ISSUE TITLE
differences between mui-design-kit and mui/material react component's specification

### ISSUE THREAD

**Issue by mogamogua** [mui/mui-design-kits#147]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Our team is currently making design system based on MUI design kit **v5.4.0 Figma Community version**, and **`@mui/material` v 5.10.0.**
but while develop our design system, we found some mismatches between figma and react code.
when compare with pure version (which is not customized by our design team) mui design kit, there are still mismatches between react code and figma file. 

Most of this differences are component props - design kit's component get more various props. 
Also, there are some trivial differences that is not easy to found.

### Example
![image](https://user-images.githubusercontent.com/62272445/213602943-0971d0f5-3efd-468e-91fc-a484089cfceb.png)

- `smallScreen` prop: this is used in MenuItem, Appbar component in figma file, but in react code, we can not found this prop.

![image](https://user-images.githubusercontent.com/62272445/213603616-fe3d62fb-3538-43c9-b78f-67efebf52499.png)
- Bottom Navigation component : `iconOnly` prop is in figma file, but there's no `iconOnly` in react code base. 

![스크린샷 2023-01-20 오전 11 13 39](https://user-images.githubusercontent.com/62272445/213603551-2c090808-e2fb-4a02-a136-e28ff26575ad.png)

- Dialog Component's Dialog Content padding 
  - Figma : 8px 24px, 
  - React code base : 20px 24px

AND EXTRA...

When we find these mismatches while developing, have to spend much time on communication between designers and engineers.

Why are there so many mismatches between figma and @mui/material?

### Your environment 🌎

| Software            | Version               |
| ------------------- | --------------------- |
| Design file version | v5.4.0                |
| Design tool         | Figma |
| etc.                |          @mui/material v5.10.0    |

**Comment by adrianmanea** [comment]
Thank you for reporting. I think there's some confusion between a prototyping tool and a code library in general. Figma can do so much in terms of the simulation of the browser's behavior. The `Small Screen` prop from Figma emphasizes this statement even more. 

The Figma components properties are designed to help **designers** create faster screens.

The React components properties are designed to help **developers** create faster screens.

We try to make the best of both worlds.

> DialogContent missmatch

Correct, there are different paddings with conditionals, which in Figma we cannot do unless we have a special prop...

**Comment by oliviertassinari** [comment]
> `smallScreen` prop: this is used in MenuItem, Appbar component in figma file, but in react code, we can not found this prop.

This looks normal, this prop is to simulate the breakpoint change of look in React so designers can design screens for different breakpoints.

> Bottom Navigation component: iconOnly prop is in figma file, but there's no iconOnly in react code base.

This looks normal, as a shorthand. In React, it's done with composition, doing it Figma would be "heavy"

> Dialog Component's Dialog Content padding
Figma : 8px 24px,
React code base : 20px 24px

https://mui.com/material-ui/react-dialog/#alerts vs. https://www.figma.com/file/zgGilmnCri3D3trq7SveBe/MUI-for-Figma-vXXX---Material-UI-(master)?node-id=11045%3A146738&t=1knORrcPjA0CKmW9-0

yeah, we might have a bug on this one:

<img width="803" alt="Screenshot 2023-01-25 at 13 47 23" src="https://user-images.githubusercontent.com/3165635/214567166-304b314b-2d3b-454c-a5db-e1384a823788.png">

**Comment by mogamogua** [comment]
I didn't expect this issue to be sorted out so quickly like this, thank you for the answers!

> The Figma components properties are designed to help designers create faster screens.
>The React components properties are designed to help developers create faster screens.
>We try to make the best of both worlds.

I understood why there are differences between the two files and realized that I misunderstood the purpose of the design kit and react code you guys provided.


> Correct, there are different paddings with conditionals, which in Figma we cannot do unless we have a special prop...
I'm not sure what this means.  Is there any limitation in Figma in making the the details same with `mui/mateiral` 's component?



>yeah, we might have a bug on this one:

 I wonder if reporting this kind of bug would be helpful, or is it a known issue.


I think I had to appreciate for your great work in advance, but I coudn't because I was in impatience when I worte this issue. 😂 Thank you for making great work. Our team is using it really well to build our services.
