### ISSUE TITLE
New comment on MUI for Figma (Community) by Yuliia

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#148]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DL3f2_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOM1-2FOfsSMjskcn2DoPZPQaCuGHctVpGukXSUSGunpher8sXH5wZmT8-2F-2FwszY3yoSPwKU71-2BWRlu0NCgqT1F7or-2BMsnXrpBjWPEtt00bngFAvm4-2Bbl8dtIe8APTorSiepOCmjiaPnGbzfJ47vtv5q0QW8VNAaZTkW8fT-2BmrydYc9cwlxYLbuSzeggCsMnBPfKhi2-2F3Gl3Sk9BI-2Fs0U93Or9jX6kMEm2r-2Bad3y8HOJBvfQ-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>MUI for Figma (Community, Material UI, Joy UI, MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro-2FOBvyusl159TFNJWjDPr1Xq6jpiFQ1Oce2qJxb22tfMhgGj_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOM1-2FOfsSMjskcn2DoPZPQa0PLvwrteGn-2BAMTtB4u5BePOQgj6VsMd6pz79FKH2zazT-2FXN7HMka0RKHl2edqMUeCBWykeitS2H-2Fh0b-2B1ZkkEQm4DoaUJsmBJ7VEX-2B5es3VKF8h8yrnf1OtmBaH-2F8DDdVz-2F-2FTpYJuj0rslUub0k0QMUZ3lg7FBYBkwkqgFnEpPEVFn1pNj6saTZRkhfYloAeHmJ1FiXfKwUNIhjtBZ75rg-3D-3D"
><img
src="https://www.gravatar.com/avatar/cc349515e1e78960ae239e309cc79c1c?size=240&default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_y_v2.png"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro-2FOBvyusl159TFNJWjDPr1Xq6jpiFQ1Oce2qJxb22tfMRAYF_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOM1-2FOfsSMjskcn2DoPZPQaKhp82lr6hLIWZ23LIVNu-2F4ccu2zftoJ1i4X-2Blf3KCLg73R7c3Ca2aG0agTSMaK-2F8uEO0A-2BuMfin8YUKeN6qsuV3HJfvuEB3-2FPiNp1kinNJ5vXSlpS4P8-2BdGbx-2F1rBOeUudSXmOthB7-2FdjyltMnY-2FHjEkwZEEM2sUyIrNXTUWm4Wl1rHhYiAjmWdHGBPxbilfItlogtW4F5FpCIc63rYbzA-3D-3D"
>Yuliia</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Hello! To have a latest version, you have to buy it, am I understand right? The project I&#39;m working on bought v.5.0.0, so to update it to the latest I have to purchase last template?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfBgujjmYcWwwiEKjGp6SB9gfIKZ14m77pOdnUoADwMM-2BZSI4_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOM1-2FOfsSMjskcn2DoPZPQaa-2FGsfu3z-2BccFyzkPNqrUstuGhJOEJQNqjD8O9DM3-2Bq4qaFarOypcmoI-2FACNruT0hzN86fZrxawHNQAu0Xs7MyUaY8TnksHDKIF6Pp-2BvPJ1HRR-2F5o2kc7m2RqlZ2wuxolTqOh7komNNSUx4fv7niHUuSdQi87i7hHThfoSR9UxOVS6p91fs8JF-2BEUMedAn2cjzG1L4vd1CJ9W4N54dW5PRg-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
Answered on community.
