### ISSUE TITLE
New comment on MUI for Figma (Community) by Alexey

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#153]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3Dg5bV_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMEUOb9lk-2Bucuoky5NU9rVqOGTbphDPt8T5vawEy-2BpjpfFmQgifRuSINrWy-2Bf6lBHD7bLenBnEfW-2Buasxcx-2B2NKGCAe6JimjL1PKcBXzC3XiE-2FpPy6gmxKpl0sXN9TT3JCMBaI70j8o9inJD1jrXi-2FJRBBv3ujzshfCrMUErkomvI4WoORIrSUKgeszeEFeqzxnsVt5YgRGjtqC3Yci4Or6rL5-2BQbucq82y2XvwsCR7uw-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>MUI for Figma (Community, Material UI, Joy UI, MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kroxmMz9XNfrI78EEYUIWo8AWvBYlFaU3ba0f6AJfSgJAt6ByN_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMEUOb9lk-2Bucuoky5NU9rVq6y58Q-2BcUBz-2FK5KGb9Z2v3qdO5tg79OQ6fGoo9PAPUZk7q7mrfWzw6dssgilmD6UPRdY8OX5UgvL4FSAMUg2r63yljOZA8tcv184SYkGh1G3zmMND3pddlGORqlQdnk3TN6VOaKIx94nxBUa8kmdW4xnmt99rT50-2FvHkiIOAdfx-2BcqZ0ezbpB110WVvDFOpg6ygwiIqABdSZhpdRgi6FUOQ-3D-3D"
><img
src="https://s3-alpha.figma.com/profile/33d0257b-3816-4a07-ba1a-3a1829237fa4"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kroxmMz9XNfrI78EEYUIWo8AWvBYlFaU3ba0f6AJfSgJAtlWOA_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMEUOb9lk-2Bucuoky5NU9rVqHU95rSSGDTSaNnTHxSGlK-2FP1U0YAH2k2bAY8d3EoEpbYMsO3yGQzehC6tHsCRlpbNBh5uIQKFNTl-2FqY2teLiANEEQ7LSunVnmLBCiYbY0ZNUbVcyjfyeXnOYxAbnZdwKr7khah5kMjj5L8xjuXUGmt-2B9M4RUkIvsoZFisS6sOg7ZVF54EpSclxXV2wriP8wJnNofYA963G1X6dwC4W6qXQ-3D-3D"
>Alexey</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
How to update from 5.4.0 to 5.11.0 ? <br>Does the Token Studio plugin only work with the new version of the MUI?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfIPp64-2BWz5p8Ja13VLL7760je2zEelPc-2FGLHfGgK4hdque6j_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMEUOb9lk-2Bucuoky5NU9rVqW-2BElGVPtlA7ddof72D22lGLD78-2FelDJ3Fpohg-2F0J5BfD-2BjBL6PUvIUgF7QrQaRswIuZJpo5SukMWDfkaoyVQIpGrthlYRm1i7CoEZvxesP-2F7W-2B7m5W2IIYpfVtrcyEu07NS0q07N62IAgGeRAl-2BqVi9LUok9xyzQQkiaN-2FLvgLhRIdOpFVFc2PhTpFRZkU8LxaM4p2FTtLj49dakNYhRvg-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
Answered on the community.
