### ISSUE TITLE
Styles are wrongly spelled in Figma

### ISSUE THREAD

**Issue by erikfriberg** [mui/mui-design-kits#154]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps: 
1. Open the latest version of MUI for Figma
2. Open the color styles panel in Figma
3. Scroll down to the secondary/states section and observe the names, focusVisible is wrongly spelled.

<img width="233" alt="Screenshot 2023-01-29 at 19 37 40" src="https://user-images.githubusercontent.com/3165635/215348401-e19c49d3-fd0c-404f-bdd5-7efba154242e.png">

Next, scroll to the "Text styles" section.

5. Scroll to the "Typography" section and observe the name of the section. (it should be all lower case)
6. Scroll down to the "Components" section and observe the name of that section. (it should be all lower case)

### Current behavior 😯

The color style: focusVisibile
and the Text style sections: "Typography" and "Components" are not spelled like in Tokens Studio, which prevents the style from receiving updates on variable updates.

### Expected behavior 🤔

The style should be named focusVisible and the sections should be named "typography" and "components" respectively.

### Context 🔦

I’m trying to automatically update tokens using the Tokens Studio plugin, but some inconsistencies are preventing me from doing it smoothly :)

### Your environment 🌎

| Software            | Version               |
| ------------------- | --------------------- |
| Design file version | v5.11.0                |
| Design tool         | Figma |

**Comment by adrianmanea** [comment]
Hi @erikfriberg totally right, and thank you for opening an issue. We already have one opened with the typos, we intend to release a quick fix update by the end of this month.
