### ISSUE TITLE
Theme switching in Design Files – not Library

### ISSUE THREAD

**Issue by jarincz** [mui/mui-design-kits#162]
Hi Mui,
is there any way how to fast switch between Dark/Light mode in Figma design files using single MUI Library?
I've been using Themer plugin for fast switch between designs to in light and dark mode but since you've implemented Token plugin it's possible only in library itself — This leads to constatnly changing whole library and publishing again or again or you have to have 2 separate libraries for Light and Dark mode and then swap them in design file.

Is there any easy way how to swap my design files themes without changing whole library again and an again.
Thanks for help.

**Comment by splitloose-earth** [comment]
https://github.com/mui/mui-design-kits/issues/161 .... i think the answer is not possible as this time. Best of luck
