### ISSUE TITLE
Insane hang time when changing color assets in XD

### ISSUE THREAD

**Issue by WildYellowfin** [mui/mui-design-kits#163]
Hi,
I recently downloaded the XD mui kit, and have been trying to set up my app's color theme. Every time I make a change, XD will hang for several minutes, and sometimes doesn't come back. There is a bit of a delay between when I close the color edit menu and when the wheel of death pops up. Right now it is totally unusable... Have I perhaps set something up wrong?

Edit: Only happens when the color drag tool is used - pasting a hex is fine.

**Comment by oliviertassinari** [comment]
Duplicate of #18
