### ISSUE TITLE
Typography component does not have all options available

### ISSUE THREAD

**Issue by splitloose-earth** [mui/mui-design-kits#164]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I noticed the typography component inside the Figma Design Kit has a subset of variants.  It only has subtitle (1&2), body (1&2) and caption. 

Is there a purpose for not including the other typography options (H1-6, etc).  I find the component would be useful have those options available to leverage as standalone instances like Page titles, or article headings.  I do understand I can apply the style to a text box independently, but do think there could be a case to include it in the figma typography component.

### Your environment 🌎

MUI Figma 5.11

**Comment by adrianmanea** [comment]
Hei! You are correct — we fixed this already in the deployed update. You can grab it by [signing in](mui.com/store/sign-in) on the store. Also, now the styles are changing based on the variant (body1, body2, etc).

**Comment by oliviertassinari** [comment]
I have made a few edits to clarify things:

<img width="284" alt="Screenshot 2023-03-01 at 11 43 19" src="https://user-images.githubusercontent.com/3165635/222116973-f8481646-4ae4-48dd-bea1-5b0c11a854bf.png">

<img width="437" alt="Screenshot 2023-03-01 at 11 43 11" src="https://user-images.githubusercontent.com/3165635/222117002-cddb7262-8c96-441c-9461-c29fde96c8c0.png">

<img width="827" alt="Screenshot 2023-03-01 at 11 43 29" src="https://user-images.githubusercontent.com/3165635/222122160-948fbd94-d86e-40ff-a61e-e570f6654fd5.png">
