### ISSUE TITLE
Does the paid version of the MUI library contain all the components we would need to create a design in Figma? Or is it just a licensing fee with the same components as the free version?

### ISSUE THREAD

**Issue by Ramsha-CoreNest** [mui/mui-design-kits#167]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

**Comment by adrianmanea** [comment]
Hi Ramsha, the paid file includes all the component APIs! Here's a preview of the full library: https://www.figma.com/file/SLZjfaEJi9R2Sq6IE1Dp1Q/MUI-for-Figma-v5.11.1---Material-UI-(Full-preview)?node-id=4662%3A14&t=QqVGkX8ICWz85H4m-1
