### ISSUE TITLE
[figma] Add Scrollbar component

### ISSUE THREAD

**Issue by ivanbachev** [mui/mui-design-kits#170]
### Duplicates

- [x] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Is there a way to add a Scroll component to the UI Kit? 

I noticed that currently there is no such component available and in the instances where a scroll is shown, it is featured as a frame named “Scroll / Vertical”

<img width="353" alt="Screen Shot 2023-03-15 at 14 56 09" src="https://user-images.githubusercontent.com/1560160/225316608-f8a3b819-ed1c-40d1-963e-1926e719e018.png">

Here are screenshots from the components where a scroll is shown:

Menu
<img width="1743" alt="Screen Shot 2023-03-15 at 14 53 52" src="https://user-images.githubusercontent.com/1560160/225316681-d5c7e054-42d9-4c70-901b-5587e5e0891d.png">

Tabs
<img width="1733" alt="Screen Shot 2023-03-15 at 14 54 38" src="https://user-images.githubusercontent.com/1560160/225316711-029e15ee-7c52-47ed-8013-bcd3fc26a25a.png">

Table
<img width="1602" alt="Screen Shot 2023-03-15 at 14 55 38" src="https://user-images.githubusercontent.com/1560160/225316752-9a8f1dcd-ab8f-474a-8c85-5d27fce87530.png">

Maybe such scroll component can be added to the "Misc" page and feature vertical and horizontal variants + 3 scroll states respectively _(top/middle/bottom & left/center/right)_.

**Comment by adrianmanea** [comment]
That's correct, we haven't defined it as a component because the looks really differ from browser to browser. I think we can have it hidden under a `_Native / Scroll` label.

**Comment by adrianmanea** [comment]
Scrollbar added as a color variable.
