### ISSUE TITLE
New comment on MUI for Figma (Community) by Dylan Simpson

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#172]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DrKuN_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmONSHExurbSRdEgfrIgt77x90x-2BnFdha-2BbCW54wXv48DgOoW4BNp61xmxvu-2BE-2BAVWExldWNQpH5CjRY2uV7qtfiDXKPaU4loDzn-2FNjoLgYTqM0IbKLRwlyZHz7aEJnMwHuI10OEm53S-2Bs-2FUNUnU5AoiQLum5NCu9a0WAtKlcbak-2BOcRmCnLMNGRDauE7gPOzh2QImy9s4uN4a2rcv9pCd3d-2Fyw2bAgR4gkVFmFfuNkaGQ-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>MUI for Figma (Community, Material UI, Joy UI, MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4ec488bgtPjnUJVFxoM3rqUhMRv8xHvO-2Bp1eWkPkKZvMEhh_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmONSHExurbSRdEgfrIgt77xLBK6TZDx2Xv25k2sCZJvRVP82RRc9hN8nY5A7RcvG8WL5I351LONwpteZKCNEy0U3rbqgvXcfHqI9-2FBfB-2B-2BcEbuuhvYvgmLut694uaXUWW-2FbanyRo-2FXEzMiDpU1w0cETbKmF-2FbBMg06QvsxnI5l-2B-2BzGFVF1rmJ4K-2FRBx3md0qYMqimlxWSTUs5yP0DZ-2BrIZSr6gGm92FdyFUQKOwHn3g3g-3D-3D"
><img
src="https://s3-alpha.figma.com/profile/08e680a8-591a-4a4e-b423-ba4142e26e89"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4ec488bgtPjnUJVFxoM3rqUhMRv8xHvO-2Bp1eWkPkKZvNeL9_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmONSHExurbSRdEgfrIgt77x1H7CORYRg0gKvMvSCPv5SRtme92Xk6VkN20YqVnPWQcZTKuxL3cYqlKD4SVmSe4pglZe7intyYVpzRiBjrB3fVioSd-2BqxAJTXOiBk-2BySqqOyYaHM47yOV6kpiCgaIVzK1i4eFD3FRYUqEtiHqLSxhXvxLaExE7ivEgcIf8YwAUsqmgK60XdFu016SnJgt6PXNJBryKql5bO3wlspUvEA2w-3D-3D"
>Dylan Simpson</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
I noticed that there are no color variants for the Snackbar component. This does not match the MUI documentation. Is there a simply way to update the instance?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfGuHIRwBR2t5Z3G-2F1b6sTETeGhJm8qps2fWjM-2FHtSf1TJ1kE_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmONSHExurbSRdEgfrIgt77xMGx-2B89bFCaEFkXuqGqDwZ55-2FhLKH5sF0K0cHsWumPhhgITl7SW6ZJfY761tdVNmJcRjv87TDDN8jlmdgX45xQbHIwNpv2uwzA-2FszpcWuujK5ddbvvMuCAOrMb7WaRYcuhu5W0IiNjHlpB9GPjxBOHYk0UlFXdLdet-2F8LTY44jlXp3-2Flmx2KHu6UC2-2BH-2F1yJO-2F-2FIg1UU7LhIhgA121yglFA-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
Answered on Figma community.
