### ISSUE TITLE
I want to download the MUI 5.11 Figma version but I can't or is not giving me the option. Our company bought the 5.4 and we want to update to the new version. 

### ISSUE THREAD

**Issue by Oscarf77** [mui/mui-design-kits#175]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Can you help with this? The account says the updates are for 1 year so I don't know if it pass the year yet.

### Your environment 🌎

Figma Version

**Comment by adrianmanea** [comment]
Hello Oscar, your access to the latest update may have expired depending on your purchase date. To better assist you, kindly share your order details through our email at [figma@mui.com](mailto:figma@mui.com).
