### ISSUE TITLE
New comment on MUI for Figma (Community) by Bishara tannous

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#177]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DYrPF_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmM39VlhjZxEH91E68tfdAY0u51ZKvjT5UCCeCocUr6i2CKsPw8ZiCuteHBC-2BqDDt0-2FCZljnn5YwJruqfQCI9Z8avdujws3Tf9Lu-2B8cxeSdSbnpKW-2Fi0clov9-2F5MeKJeyxsEZ-2FVq-2F4XMM8aycNyqH2WBdPJg62Z9kS7253AumKesoAcNLKkAjYhR7P1GdDziGRrEGRKKAlONcEF5wE0d8cuGmBSmMLAc4PPoTH1rN47UIA-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>MUI for Figma (Material UI, Joy UI, MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro0nkP4lHZ2sdDzllGSFGQmOHbhC6xtH6VknXCEopKaEwwAai_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmM39VlhjZxEH91E68tfdAY0EJjIILASiEQi8qEbC3KUy9Gs8VLP2eNxlN9aVI2bqQ9NT4HcBnv7gSqMA8OD3llZI2CWcd-2BCkx7Wq3BhaIXeeZxBJ1urCYNZRq12datz-2BQhf0VdmaU3yeaRY8tPtPZiP1pSp12myCN0r-2BfrUaubEA2Ftmmvn7G8oHExAtXnd2lckJ-2FxaMn1Vfjj4K1-2FHfmF93m279Xg8HH05cITRudo18g-3D-3D"
><img
src="https://s3-alpha.figma.com/profile/d63e94e9-6980-4c09-aee2-e157b2c4ba5a"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro0nkP4lHZ2sdDzllGSFGQmOHbhC6xtH6VknXCEopKaEwrXah_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmM39VlhjZxEH91E68tfdAY06x8hvc-2FJVJbU7vGr7ldRdGhRqscvQh4Ny64RwRkQmnoXZwglKFB0VILIWTHqs0-2BUQpkfaQQuPxG0eV3r9l38qAUE84l2mVlhqDDb8BKGEiT6yT3HPQdKSIi2GvTv5hksiauSRgS8Ub4sUjOr8slicNklq5SJx2J-2BWY65O3CwO-2BV7CZq56l1nbUizPRxNo-2BwyvFTIAYJFy3BnVtjzXmvOiA-3D-3D"
>Bishara tannous</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
I purchased the kit, but no .Fig file in the zipped file, just PDFs... any idea?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfMbl-2FI9-2BwBvAqjiKJ11uzuARJ-2F9lvy48mSdYP0LcHLfuYOd2_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmM39VlhjZxEH91E68tfdAY0EuPmUmnRbBaTHod6TQYUo3lnwqufI8TJDlp-2BYPuGo0w9i9-2BuZJKMQTkItjzgUAU3KZh-2BkfBn5pP9iOGyS-2FLOXhSX5eRqpXsaF7pT23fvg9-2BMtgnkHty5tIVGeYMQ9-2FuEsUy3At-2Brsy5VFFgan0dBfHE4ODkAxo4DdPdqapfHWBO4r6ybqyEIBfQVBvCvp3JAG646QKxhyd138z3M2EO9YA-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
Answered on the community page.
