### ISSUE TITLE
[question] Issues migrating to v5.11.1 & Design Tokens - No dark mode toggle?

### ISSUE THREAD

**Issue by wvian** [mui/mui-design-kits#178]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hi,

Our design system was built on an older version Pro v5.9.0 file. We are trying to update and migrate to the new v5.11.1 Figma file however it seems like the components no longer support the "Dark Mode" toggle available for each component like a text field, etc. Looking at the documentation, it seems like the update is forcing us to use Design Tokens instead to define the overall styles which is NOT an option for us. The instructions on how to use design tokens to change base colors do not work, even when purchasing a Pro license from design tokens- it does not allow us to just change the HEX code for base colors. Not only that but trying to update any color with tokens takes 20mins+. MUI had stated that updates to their DS library are minimal and that only changes would be additions.. so why did all components change to eliminate the dark mode toggle? Is there a way to revert this change and continue building multiple color themes without using tokens studio?

This is frustrating because we were expecting an easy transition. We also reached out to design tokens for support but ultimately we still cannot leverage it efficiently after trying with them multiple times.

Maybe I am not finding the right information. Thank you. 

### Your environment 🌎

v.5.11.1

**Comment by adrianmanea** [comment]
You don't need to purchase any additional features from Tokens Studio to make use of the library. You can use the plugin for simply toggling modes and making global changes (spacing, border radius, etc).

The problem with the Dark Mode as a toggle was the high volume of variants (we reached max RAM usage) and it became unusable. Having both modes inside a single file enables toggling modes for all your screen in a few minutes! Just enable it from the plugin -> apply the new changes to the library (may take a few minutes) -> go back to your screens with a different mode.

Additionally, you can duplicate the file, apply dark mode, and save it as a separate library (dark mode).
