### ISSUE TITLE
New comment on MUI for Figma (Community) by Rosie

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#179]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DBOZZ_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmNXUTbD-2FMsTP5tOhwm0XsXvm-2B8CdEFWGVwvAKA9s75sULfm0yfb9FUmZikQoeVxnoCQH2Hq1yW19T3pBlnJMdGI6U7VlhlAuAGEBI3uGdmGxlfK-2BdqNO9mxH52XtyikOMUGBDU7OuUF3g2zAjuFygiNuS3gB9aa2aHZXI-2BEmzSoIpfzkjMTjPMYkmlHeDxBfEXtZNSi-2BtrEhRshsCMbB48tClYJOhP6iTMzQ2-2F6fDRHBA-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>MUI for Figma (Material UI, Joy UI, MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro0J2FDIiAewpanEfX1T8BxxPWjMZGKnespB8FLXFCl4EvmIV_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmNXUTbD-2FMsTP5tOhwm0XsXvB10g6G2mxJ5CUbIG0zsxqxp-2FpDGVudJCxtq872RkP384Gf0arqjDSbyzB5tM19C9eUW-2B6hHdcqFpTosvfxHIxlyXyd-2FnrZGNOnuWSGql1F7oupsdG06doeBxeVgHICryRkVak3o6CxasU3kGmfmM7xSrcb5HLScsZ5eFbzjOG3u5WZd4AUUXXb40pZNmINtoUDbmlfxpEJy1amhnVq3t-2Bw-3D-3D"
><img
src="https://s3-alpha.figma.com/profile/9613e256-eafb-45b0-b50b-83250ca2158c"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro0J2FDIiAewpanEfX1T8BxxPWjMZGKnespB8FLXFCl4Ek4e-_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmNXUTbD-2FMsTP5tOhwm0XsXvw4g6gr5mrTVnzhoHyWmX-2FEiU-2FbjXAaYc1-2FlyjHqcNCwrQ3UjN62xpohD1-2Bk4aqfMao0kaisrdceBuC8KIK45-2FanjKkBhZvDhVqDx4KUvPZcCvUGc38MJ0d7X59fwozIqltuXXI9hogr3QPFBO2pVqKofjaFl3CbQ1KA7bPJpEgPzcv4rg2g83DaeR-2FsNmqdgJt8Ql-2BzADYMFpT2kE7120w-3D-3D"
>Rosie</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
ㅕㅛ셔ㅛ셔
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfAUNDjZci69FlMIM5xguRLYiZ0SmVXig0Jr45P-2FoOZ-2BJCYfo_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmNXUTbD-2FMsTP5tOhwm0XsXvkDk-2BfFo-2ByFVVkQEcCydmZx1kJ4qlGxTe-2FNpR2X0cYomSC3e-2FnmNLnRZ-2BfJ8SbizSaZZ3tXxFcLFI8VGv4QvKVmpvIGdZhbOnxYj8k4NuC609gcLp9xwdxjr5U4rdbch9vkFpowk3-2Fh3X39CXgQKdHe8QVvquHVL4GLe-2FcdXXqrjYQt9tq-2FFkZeKdeHW19bXhcfIDfB4xL9AOb8QRWl3o6w-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
I don't find the comment anymore, google can't translate it either haha.
