### ISSUE TITLE
[adobe-xd] Performance issues

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-design-kits#18]
> sometimes there are too many layers which makes adobe XD hang.

factuur@corverdevelopment.nl

> I'm using it on the latest macOS powerful desktop, the file keeps loading and freezing all the time, especially when copying and pasting between different projects (files), maybe it's XD itself

danielribas1984@gmail.com

---

@adrianmanea thoughts on the issue:

> Regarding this issue, I'm thinking to "fork" the main document and remove most states, strip out the not-so-necessary components, and basically have a light version alternative. The maintenance will be a bit tricky but we plan to hire another designer to take more responsibilities.

## Your Environment 🌎

v4.13.0

**Comment by adrianmanea** [comment]
We're experiencing performance issues when changing tokens which are bound to a high number of components (e.g Buttons" but that is understandable. Otherwise, on our environment (M1/i9 Macs) common tasks like drag and dropping components feels smooth.

**Comment by oliviertassinari** [comment]
Ok, let's wait to see if we still get this feedback after the release of v5.0.0: #32.

**Comment by oliviertassinari** [comment]
I'm closing for now, waiting for more feedback.
