### ISSUE TITLE
New comment on MUI for Figma (Community) by Steffie

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#180]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3Dguww_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmO-2By-2F2fRCuZu9InqcHX0jXZXpbjKv8-2Bo3B0APKOiX9TRsrnY4VfvGdt7erg39PpzA4-2BLGX0lkSBnyhBoTZRLgpppStn-2BEaMHtZeKfIxo44SSwn0viKLtnvD20sRygg845JqmqhMUniyF-2FnKs-2Be-2FUjDuH2XU0ACHqWpO3Diq9eyYaDYNQi07qN-2FN6ENaLK3n3UWqTkAZmohcBpkvrOVLlKgCyhdyYn0jN4-2FTPLqHihMVjQ-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>MUI for Figma (Material UI, Joy UI, MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro7-2Ft9SzmG-2FNlVO-2FPtIa14evjHgxDM6satcVk059ZFW68GdM8_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmO-2By-2F2fRCuZu9InqcHX0jXZcb-2B94KeDM3tmZQUIl1Yl5nzMomZl8XIYEDK3fINymL7TAnqqVlsDdXSJGGFfA9zVAxwknpCoZSGwm-2FXOi1i6JdFqWQaJPy8DnLkqD-2F4g6-2FYNgdnPXHt4LZoHTLg58ThsKtUd9bipzsNCz-2ByytX-2Fr1aBcT8uwNfiuiJ-2Bm0LGogpjth0xsOkWy2vBp4MwGnnALba-2FbLq4-2FjLvMp7HUCm-2Bukw-3D-3D"
><img
src="https://s3-alpha.figma.com/profile/546015c9-0d19-4057-8126-5c650da3b35c"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro7-2Ft9SzmG-2FNlVO-2FPtIa14evjHgxDM6satcVk059ZFW68wQPB_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmO-2By-2F2fRCuZu9InqcHX0jXZbddr0-2FCaojq-2BiyxdPR8iyu9Dc3nwZTcSozDiiiUFbctacHKffwvivgSsQDJBjWpVWv7UkNDePwnwMlTxRjuAPwb3iYmk-2BAHRpB-2FzEJRxfIwuIBnU3DhRBhtnIKdIL0kntVtN1RmdZTXCU91npatgmBSleVQP9kYmiG9bEte05ag9WkDzVXxaXtuTVEYkE8JxtMsikKrRz4JkSoGu9TbG8A-3D-3D"
>Steffie</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Do we need to purchase a license to access the dark mode styles on Token Studio?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfK4QFGtlgRVuWKzh4vHue6SyAbqKvK1llhiZZTiLwAYScvjD_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmO-2By-2F2fRCuZu9InqcHX0jXZF23E6-2F7Nuv0iedhQUCMnK92-2B8gLXEeo5MskXEGOdcrYMqrr-2FaiemRJdWwpQXaG2h-2BGv4WPiGAJxtXjV1G1qHWF2n4NsZIFCo-2FeAPPPZnD25KG1Jv81glJvb1i8LI19AMZf4BMQKpTcDa3IU5537RWmpZFj5rJ1BQ1yMBRyE0NWCNFzfJQ7N-2BHrrHYkVDqWRoNj6HGjoD4XaZ8LdfJFxCpA-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
Answered on the community channel.
