### ISSUE TITLE
Chip Component Uses Wrong Token for Text Color

### ISSUE THREAD

**Issue by pr0da** [mui/mui-design-kits#181]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Filled, Error/Warning/Info/Success chip component variants use the `secondary/contrast` token as text color instead of the corresponding color variant's `contrast` token.

Link to live example:

![image](https://user-images.githubusercontent.com/1568701/234622594-a61fbb72-0692-40e8-bddd-5110a2bf4c73.png)

Steps:
1. Check out Filled, Error/Warning/Info/Success chip component variants in the official Figma ui kit.

### Current behavior 😯

Filled, Error/Warning/Info/Success chip component variants use the `secondary/contrast` token as text color.

### Expected behavior 🤔

Filled, Error/Warning/Info/Success chip component variants should use the corresponding `error/contrast`, `warning/contrast`, `info/contrast` and `success/contrast` tokens as text color.

### Context 🔦

I've tried to customize colors with "Token Studio for Figma" but could not change Filled, Error/Warning/Info/Success Chip text colors independently, because all of them are tied to the `secondary/contrast` token.

### Your environment 🌎

| Software            | Version               |
| ------------------- | --------------------- |
| Design file version | v5.11.1                |
| Design tool         | Figma |
| etc.                |                       |

**Comment by adrianmanea** [comment]
Yes, I found the mistake too after release. Sorry about that and thank you for opening the issue.

Attaching a video on how to fix in 30 seconds.

https://user-images.githubusercontent.com/5917515/234787412-d6f3dbb4-470a-4103-9b19-fe50d2c0ea08.mov
