### ISSUE TITLE
<DataGrid> | Header Rows component missing columns

### ISSUE THREAD

**Issue by pr0da** [mui/mui-design-kits#183]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

<DataGrid> | Header Rows component missing columns for "Columns: 8" and "Columns: 10" variants.

![image](https://user-images.githubusercontent.com/1568701/236773907-b6b33dc3-14fb-49b6-a6ac-1cd03e0d8ea7.png)

![image](https://user-images.githubusercontent.com/1568701/236773940-88f4c236-a43b-4176-8a4e-4b95c3417ecf.png)

### Current behavior 😯

<DataGrid> | Header Rows "Columns: 8" and "Columns: 10" variants have 5 pre defined columns only.

### Expected behavior 🤔

<DataGrid> | Header Rows "Columns: 8" and "Columns: 10" variants should have 8 and 10 pre defined columns.

### Your environment 🌎

| Software            | Version               |
| ------------------- | --------------------- |
| Design file version | v5.11.1                |
| Design tool         | Figma |
| etc.                |                       |

**Comment by adrianmanea** [comment]
Thank you for reporting this, you are right! Adding this to our next release, should be a quick fix. Simply duplicate (CMD/CTRL + D) the last Cell until you get 10 items.
