### ISSUE TITLE
[question] Seeking advice on exporting and utilizing global styles efficiently for development

### ISSUE THREAD

**Issue by jonatanvazquez** [mui/mui-design-kits#185]
### The problem in depth 🔍

What recommendation could you give me to easily export all global styles and use them in my development? Sometimes, some styles are modified, and it would be easier for me to export the entire style sheet whenever a change is made to keep it up to date.

### Your environment 🌎

v.5.11.1

**Comment by oliviertassinari** [comment]
You might be looking for #10 we will soon work on this.
