### ISSUE TITLE
I need support with MUI for Figma - Missing Dark Mode .fig files from the download after purchase.

### ISSUE THREAD

**Issue by rachanapand** [mui/mui-design-kits#187]
### Discussed in https://github.com/mui/mui-design-kits/discussions/84

<div type='discussions-op-text'>

I made a new purchase: Figma for  MUI 5.11 but the downloded Zip was missing the Dark mode file.  I am pasting a screenshot of the unzipped folder to show the files that came with it 
<img width="485" alt="image" src="https://github.com/mui/mui-design-kits/assets/34417134/d8a1a61e-ee2f-4e0d-b816-9f4d2942bb17">

<img width="902" alt="image" src="https://github.com/mui/mui-design-kits/assets/34417134/27235c63-128d-46bf-b77c-53403181bbea">

**Comment by oliviertassinari** [comment]
We cover how to use dark mode in the docs: https://mui.com/figma/getting-started/

<img width="675" alt="Screenshot 2023-05-21 at 13 10 05" src="https://github.com/mui/mui-design-kits/assets/3165635/df14f49e-1615-467a-98db-6f90f93f42ef">

This should answer your question.
