### ISSUE TITLE
Autocomplete Active State

### ISSUE THREAD

**Issue by philberesford75** [mui/mui-design-kits#189]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I am stacking the Autocomplete component, but when I open the Active state the menu shown is transparent. I can't find anyway to make it solid. Is this a bug? What am I doing wrong?

<img width="315" alt="image" src="https://github.com/mui/mui-design-kits/assets/134918369/64bdb9b7-a2ff-46f5-9143-fc4e7033fee0">

**Comment by adrianmanea** [comment]
Hi, that is the default behaviour of the Menu when it's open—meaning its position is on set on absolute. Unfortunately Figma layer hierarchy of overlapping is wrong in my opinion. If you want to change the Menu from absolute to block (solid as you said) follow the attached video. Also, an alternative is to manually set the height to fixed and adjust as needed.

https://github.com/mui/mui-design-kits/assets/5917515/1d10437d-d339-4a80-aeeb-910a32bb14e2

**Comment by philberesford75** [comment]
Thanks Adrian, the layer hierarchy is 💩.

**Comment by philberesford75** [comment]
> Hi, that is the default behaviour of the Menu when it's open—meaning its position is on set on absolute. Unfortunately Figma layer hierarchy of overlapping is wrong in my opinion. If you want to change the Menu from absolute to block (solid as you said) follow the attached video. Also, an alternative is to manually set the height to fixed and adjust as needed.
> 
>  MUI-F_5.11.1.Menu.change.position.mov

Hey @adrianmanea, I think I've solved it. 
Changing the Canvas Stacking to 'First on top' in the Advanced Auto Layout Settings seems to do the trick.

<img width="267" alt="image" src="https://github.com/mui/mui-design-kits/assets/134918369/38ea7e9c-e1ea-404d-b2ac-76449dae11c4">

**Comment by adrianmanea** [comment]
Oh wow, I didn't know about this setting! Thanks for sharing.

**Comment by oliviertassinari** [comment]
@adrianmanea Is this something we should change in the design kit?

**Comment by adrianmanea** [comment]
It's a setting that needs to be changed for each new auto layout created. We can only give hints on how to achieve this.

**Comment by oliviertassinari** [comment]
@adrianmanea Right ok, only a docs / support question.
