### ISSUE TITLE
[adobe-xd] Add free demo

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-design-kits#19]
We could do the same that we did with Figma in https://www.figma.com/community/file/912837788133317724.

**Comment by adrianmanea** [comment]
Done! Should I post the demo here? @oliviertassinari 

Unfortunetly there isn't an official XD library kits app, should we use GitHub to host the file?

**Comment by oliviertassinari** [comment]
I had a look at how https://www.antforxd.com/ solve this problem. They are using Convertkit to send the zip by email.

Sure, why not use GitHub to host the file. We could either add it to .git, but it's not really meant for this. Instead, I propose that we use the GitHub releases. As long as the filename stays the same between releases, we can use the same URL https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8?permalink_comment_id=3936277#gistcomment-3936277

The only other alternative that I can think of is to use Google Drive with its versioning features, so we can keep using the same URL, but that's a bit convoluted.

**Comment by oliviertassinari** [comment]
Thinking more about it, I don't think that the GitHub release is going to work as we would need to add the same free demo on each release. It sounds overkill. So what we can do instead is simple:

1. Upload the preview in Google Drive
2. Create a redirection rule to point to the latest version each time we make a new release.

**Comment by oliviertassinari** [comment]
Done, the demo can be downloaded from https://mui.com/store/items/adobe-xd-react/.
