### ISSUE TITLE
I previously customized v5.11.0 and just downloaded v5.11.1 - what now?

### ISSUE THREAD

**Issue by sararasnm** [mui/mui-design-kits#193]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I customized the colors of v5.11.0 a few months ago and just downloaded v5.11.1 - is there any way to incorporate my customizations into the latest version?

**Comment by adrianmanea** [comment]
Hi Sara, yes! The 5.11.1 is simply a quick fix update, so it shouldn't be an issue to swap components using [Swap Library](https://help.figma.com/hc/en-us/articles/4404856784663-Swap-style-and-component-libraries) feature. Keep in mind that you will have to re-do your overwrites if there are any.

**Comment by sararasnm** [comment]
Ah wonderful, thank you!
