### ISSUE TITLE
[figma] Updating typography globally

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#201]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DKg-Z_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOp2RmNuLpfaH7YmdKCWEkP30yRzuip-2BYg5Ni8k7aDmtM4zoLm6Gwc7R-2FMAydN1dt8cFAPY6lpRTX78o-2BoUENBAkTRugdfouBAEUomVOP-2BWn5wgR1RWq-2FyTMLX6FPjjPe6aM1vBOuzSQ8CaWA-2FQxNxutDQxhed4Wq4xrBkXC-2BTO9Laa-2FsWZRlk1sFijLzaWjmwY9JdWfrk5dkB-2BSLCWsT4WxZxb2VioGo2miFG0q5T1zw-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>MUI for Figma (Material UI, Joy UI, MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kroxmMz9XNfrI78EEYUIWo8AX2mgJMHjbods2K8GZPdVm1IvBx_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOp2RmNuLpfaH7YmdKCWEkPFpg83LwTc-2BF6xha0Vq2wPUTwN5-2F5-2FanD2Sy0GxCfQYj8YL-2FuN0SFFSStkncAwcOp5praQFIGEezQSxrhdQoxN6pYgaDgMYCMrEAhV43nwPC1PDh5-2FlkFP0d7Z1JkPEQjwDt-2FzWso7GNNz70ETXAttJxjbE-2BR1LQYqW7icZ8Bpoo5ArjTVNR3H7CTeTDIz-2Bz-2FxHM-2BPlMHS-2FPkfG-2BZVMS8kw-3D-3D"
><img
src="https://s3-alpha.figma.com/profile/e3945ff9-550f-4c9a-84db-8a5623579d03"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kroxmMz9XNfrI78EEYUIWo8AX2mgJMHjbods2K8GZPdVm1JuHW_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOp2RmNuLpfaH7YmdKCWEkPENbVgVaKCPW-2BI-2FTy0XtALMmyxWcqnWXRsM8-2B-2BAwO1-2FrazlmypH5O51iBx-2B452yYKp-2FXhtYU-2F123A3OdsTPv2qbkdEv-2BBBu-2FHyBXyI4rMyItgmpErPbIF8iOJxUg5gC-2FNwG1qpzxANCuujLDfKgPxHe4NSOxAG359k4X2-2Fxvd3fiDIF8JrP7S08aBGY2Jmd-2Fo14VBPtMGiofXzNZce7yfcw-3D-3D"
>Anna Gurung</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Hello, I cannot find filled and outlined text field in the community. Can you also add color library that you have used in this file?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfEbzl1dWZdLs8e86MigCMK8ZDrgIaxmFIChxv0wAtzP74jxS_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOp2RmNuLpfaH7YmdKCWEkPBFboD9BFMUXTwP-2BsI1mT1Nhf-2FDUudJXow4uLJu1FICMvQpRxr-2FoEWAQH-2FpTtqBRDkhDVduwNTqmrm1D7gC3ro5A-2FdbabelAYXSipaXig-2BKDlfz78UFM5fSa5-2BmWjUSHN4WcksWskFLnYP97x2hacQcB7m02R3Ztv0t6LKmMn76yXPG8lTFX8q3DLjzxV4PRLohmMpInpfKLbSovaDafFgg-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
Answered on the community channel.

**Comment by oliviertassinari** [comment]
@adrianmanea I have tried these instructions but couldn't make it work, I started this doc about it https://www.notion.so/mui-org/MUI-for-Figma-docs-4eb22360388047a9a31fc19d300a285e?pvs=4#7ff81883587b4339921fac97c3d89629. Is this what you had in mind?

It sounds like we might need to create a new token, like `fontFamilies.default`, it would feel better to customize this

cc @DavidCnoops

**Comment by adrianmanea** [comment]
> Is this what you had in mind? 

One can simply change the global font from the base set. In the 5.11.1 the token is called `fontFamilies.global`. Having the "Apply to page" option is way faster.

**Comment by oliviertassinari** [comment]
@adrianmanea It looks like it's called `fontFamilies.roboto` in v5.11.1, but in any cases, for me, it doesn't work

https://github.com/mui/mui-design-kits/assets/3165635/570e3de2-ef92-4c57-90cd-740cfce14bd3

I have updated https://www.notion.so/mui-org/MUI-for-Figma-docs-4eb22360388047a9a31fc19d300a285e?pvs=4#266d472b71bc4bd59c2d45d789fe091a with I could make work. I'm closing, it's not too bad
