### ISSUE TITLE
[question] Figma-variable converting issues

### ISSUE THREAD

**Issue by dusskapark** [mui/mui-design-kits#202]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hello folks, I'm currently using the Pro version of Token Studio and trying out the new Token Studio -> Figma Variable conversion feature that was recently released: https://docs.tokens.studio/variables/creating-variables 

I can successfully convert tokens into Variables, but there is an issue with components properly supporting the variables.

For example, a regular rectangle transitions smoothly between Dark/Light modes, but components (e.g. buttons) don't seem to transition.

To compare, using Token Studio for light/dark mode switching is very clear on the screen.

Can you help me understand the cause of this issue?

<img width="879" alt="Screenshot 2023-06-30 at 12 16 25 AM" src="https://github.com/mui/mui-design-kits/assets/4177529/b0eb8e3e-f237-406b-9f6e-ad1ece67e889">

<img width="1840" alt="Screenshot 2023-06-30 at 12 41 48 AM" src="https://github.com/mui/mui-design-kits/assets/4177529/ec492436-ed3b-4304-993b-3c76ece4ec0f">

![ezgif com-video-to-gif](https://github.com/mui/mui-design-kits/assets/4177529/ea9dd368-dae8-44f2-acba-34c9608ad69d)

### Your environment 🌎

- Token Studio Pro
- MUI-Figma-kit 5.11
- MacOS 13.4

### Related

https://github.com/mui/mui-design-kits/issues/198

**Comment by dusskapark** [comment]
<img width="840" alt="Screenshot 2023-06-30 at 2 53 10 PM" src="https://github.com/mui/mui-design-kits/assets/4177529/fa7195e3-b93e-49ac-891a-fc59fd4820e9">

I've identified the cause of the issue. It seems that we need to go through the task of converting all the local styles in the MUI for Figma kit into Variables, one by one. While Token Studio supports converting design tokens from the MUI kit into Variables, it doesn't take responsibility for converting local styles into Variables individually. To cater to users like me who are attempting to convert MUI FigmaKit 5.11 into Variables, it would be necessary to add this information to your Notion guide. 

Here is my workflow:

1. Purchase the Token Studio Pro. (Only pro ver.'s theme feature supports the variable transfer)
2. Use the Theme feature to create Light/Dark themes.
3. Utilize the Create Variable function to migrate the MUI kit's tokens into Variables.
4. Link local styles to the newly created Variables.

**Comment by adrianmanea** [comment]
Thank you for sharing Park, greatly appreciated. I haven't used any plugin unfortunately, I was half-way done when it came out haha. Indeed, for it to work you need to manually switch from styles to variables. We're confident we'll have a production-ready file by the mid of this month (Jul 23).
