### ISSUE TITLE
New comment on MUI for Figma (Community) by Ben Mettler

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#203]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DirSt_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPnAtg-2FcF9gsTaau-2F4Twcc0X9VlpSWAIl6YS93bXVEtKmA3sB-2BTi8hbVdkOn33d3L1heHb-2BIPFWuSR529gHShI-2BOykVzmC6ktUOUW969NPd0PVmGNqEhGx9vPNUmzsGR3JuSBgigTrdkgpIHzYZUHBwuOamf-2F5UtwIq4Vwbu43nrjR7bfMtjtsKwWc2qCq6bOVouaAY1QWHRKRir5vXWkjnot1Dipij-2B881xP7TzUeOhQ-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>MUI for Figma (Material UI, Joy UI, MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro0nkP4lHZ2sdDzllGSFGQmPJypbRfQo-2FQYMkgOqRLk-2Fx0GId_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPnAtg-2FcF9gsTaau-2F4Twcc0syi8z5XRbPxHt31reaXRsNKExiCPXt8sP7HhxouXbpGFJP-2FWYnCpYbWUAmAamUXwpiET2Yupd7pdqfjaRQNBX8rW7dPwfCBWu0GYO0w8aswyrRP2JZdZhz3ksGcZDeoQeDFNj5QDesUDNLoYd0XE-2FWVUVnhfCsChjyr6Plv8gnnBfSC524RSRpePM7fByrHRMUHrUKqt6k6RL8zlxgvFuA-3D-3D"
><img
src="https://www.gravatar.com/avatar/cfd0933b6291973850e30edecbf65475?size=240&default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_b_v2.png"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro0nkP4lHZ2sdDzllGSFGQmPJypbRfQo-2FQYMkgOqRLk-2FxwRk8_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPnAtg-2FcF9gsTaau-2F4Twcc0oEUsD86BDcehG6Su7v-2FkQxzGbIP3u1JU2udpd2tILUa91mE1pOjbMLlz0-2FbWXjrPLpMcQDAifj7E5zbKmhgg-2FASrrJEw-2F3ZmneeqcsOPXrxzE44jdQBq6yCuVDWvaboq5iREDGNbObTFBgEividTWgtKd9GibDlzpH1FIaOTSj9q8OWtYDbtVr9D-2FRiXiTkmvFLrHy28SeHC859c-2FEKflA-3D-3D"
>Ben Mettler</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Hi, we just purchased the full version of the MUI kit for Figma but when I try to use the components either by copying and pasting or using them from a published library the layout changes. So for instance with the button component the label isn&#39;t centered and is positioned in the top left corner. I also noticed the padding is uneven so forinstance the button component has padding on the left and bottom but none of the right and top? <br><br>This is happening for every component I try to use.
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfC6PF2sjHNfs1ZFoUiYQC8qyXkHZcJk64y5bJrRlnazU4E4k_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPnAtg-2FcF9gsTaau-2F4Twcc02y9-2Ft7-2BGMv1RJFt3SQH0gQLfBHdOMxv1r7lur1gTt17aQ71ejKR9KD9mnrXhG-2FRr2fQAdmZWTkKrNlq8Ep1iaISLGRLasdcElWdboo4RBlxV9m0Z2YJQiz9PHvt9J8TZMCDnMuI310SCsQKhgRJsgVasBQVpUA-2Bx2sHzCDZ89rNhHZQdHVIwTO2ANs4DD0LK5FTkJw5Tf8j5wR2b0AX-2BpA-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
Another related issue https://github.com/mui/mui-design-kits/issues/204 which I cannot replicate.
