### ISSUE TITLE
Support "MUI for Axure"

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-design-kits#208]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Create a library UI kit for [Axure](https://www.axure.com/) — it might be wise to wait for other people to show their interest until we could take it under consideration.

### Examples 🌈

- https://axureboutique.com/products/material-ui-widget-library

### Motivation 🔦

It will depend on the size of its community, we can monitor https://uxtools.co/survey/ to know when it would be the right time.

**Comment by danilo-leal** [comment]
I'll close this as I think it's safe to say there's little to no interest in an Axure Design Kit. The number of people relying on this tool should be incredibly small (the UX Tools 2023 results already show that), and it won't probably be worth our focus.

**Comment by oliviertassinari** [comment]
A refresh from 2025: Axure seems pretty much dead, no mentions in https://www.uxtools.co/tools/design.
