### ISSUE TITLE
[question] When will Material UI design kit for Figma v6 be available?

### ISSUE THREAD

**Issue by tvpmb** [mui/mui-design-kits#210]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I checked around and could not find any information and the Figma design kit page said to open an issue.

https://mui.com/store/items/figma-react/

When will v6 of the design kit be ready? I'm starting a new project and want to see if we can start on v6 or if we have to start on v5.

Thanks!

**Comment by oliviertassinari** [comment]
Material UI v6 is still very early in its lifetime. I assume you are coming from demos like: https://mui.com/material-ui/react-slider/#experimental-api. You can follow https://github.com/mui/mui-design-kits/issues/135, the GitHub issue that centralize the collaboration around it. For the time-frame, I imagine we will only start to work on it once Material UI v6 is in beta, so I think not before 6 months.
