### ISSUE TITLE
Can I no longer get the newest version of the Figma MUI Design Kit? [question] 

### ISSUE THREAD

**Issue by Sisaka57** [mui/mui-design-kits#215]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

When I go to my order history and I try to download the MUI design kit I get the below error. Can someone help fix this?

"Sorry, this download has expired [Go to shop](https://store-wp.mui.com/)"

**Comment by oliviertassinari** [comment]
You can contact us at https://support.mui.com/hc/en-us/requests/new.
