### ISSUE TITLE
New comment on MUI for Figma (Community) by Ghaz Somerville

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#216]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3Dk1VK_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmM3Ue79-2F7dvAXRJ-2FwMjvrefc8VlU4FVQcSecSfbifqKqH4d6SrEdrqywhAKs0BZGNccz38IUBHnSffZYrCt8Zig7v2T5g0eOPdcOyWwTAy8dzcV3yuLk9-2BZ5Uzlb5bMH2QeG0x1Wf2m-2BL568Org7nQhtb3m3yk9VhfUzZNbSR0vLIR4TwMzzu9moIAP84tss0i2H-2Bgvz3qziPLyBkDdJC3EEcRa0io-2FIjKFkDhClInkKw-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro232ms9-2FCNGs78bFnJ6WmYMIb5hQOz8qfQHooqF9XtY-2B3WfI_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmM3Ue79-2F7dvAXRJ-2FwMjvrefFZ3VCqXej-2FgRwS-2FzzmSSaL3tSlYfS3N9hmJKBv3I-2BNfZKtx99dm8gWkpk6My6ypgH10GYQYeQCkjo9dVgQES5ud2eyVFOYqQHCssOJp-2FHBTGX-2FIHeLRaEDxyjwTY-2FHczabOFFQEf0g-2BBzKogZPBx1IDLaYQRz8-2FWTXXF-2BBqUH0UmiWJOVTtm2Nr-2FFDFVTwQ3lv5A8VPFZUWVJ8Xo6faCRg-3D-3D"
><img
src="https://s3-alpha.figma.com/profile/87e38940-b8b7-40c7-93a6-0bc825a6d381"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro232ms9-2FCNGs78bFnJ6WmYMIb5hQOz8qfQHooqF9XtY-2Bsce-_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmM3Ue79-2F7dvAXRJ-2FwMjvreff47WawmBkRfOHZT7mKpnKBkS5hICkCd5T-2BXW5ce5zewv3VVtGq3SL7YpqxaxnpV7E2HxBZuzUoEq4XFjOX2NYPFMmX27eePYguX3x5apqpg-2FrakKYBUHlKAP2GUEfUwN48522AD2X05fSpjB2UuwVb9tgpyL4FEJQmniqTkcvcZjAWZOdwth3pFToi8VDIuAWwHae1cys8ghdkibBCFOqA-3D-3D"
>Ghaz Somerville</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Hello, I have purchased the paid version and I&#39;m trying to access the variables. Looks like it is empty and no colours are there. Could you provide me with some guidance here? Am I supposed to create all the variables myself? That&#39;s not what I expected from reading your Getting Started guide.
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfB0qZCHlmXzYPqsgu57nitkwY3VzqckRRwW9RfXrkKLpqX4y_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmM3Ue79-2F7dvAXRJ-2FwMjvrefX4-2FscL7i-2Fivijws5Y7v7TGR3a-2FqBma35vfl5Y04-2FXD6rFgGuBW-2Bt7FzqaKIILHYuONIydsv6gZ3TwqBrN5NKjKmOociNEZt4veWvW69qhIPoDmkIfGTS2FqGvmbOvxVoHV6UCGrk4VNUoOJ1y-2FTUrLQl2h2ns9bC6KcWdJjb0EiFBry-2BvNe2Jurm47-2FEtJFJBJnOrPGriInjpRKt0dMp7g-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
Answered on the community channel.
