### ISSUE TITLE
[Figma] Bug with Figma

### ISSUE THREAD

**Issue by sir-dunxalot** [mui/mui-design-kits#219]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I recently bought and installed MUI for Figma. After adding the `.fig` file as a library, all the components are appearing a white  boxes:

<img width="916" alt="image" src="https://github.com/mui/mui-design-kits/assets/4495352/ee7110ea-4761-44d2-bf91-a8ea649d7618">

Changing options like 'color' in the sidebar has no effect. It seems that every color is appear as white/`#fff` in the sidebar:

<img width="231" alt="image" src="https://github.com/mui/mui-design-kits/assets/4495352/96afb762-8e64-47e7-91c9-6b5867778775">

Clicking on one of the above  colors results in a generic Figma error:

<img width="554" alt="image" src="https://github.com/mui/mui-design-kits/assets/4495352/11439e4e-edb2-4e01-b198-84cefcfe7abb">

I believe I have followed [the getting started guide](https://mui-org.notion.site/MUI-for-Figma-docs-4eb22360388047a9a31fc19d300a285e#6379420b4d5a4927b9ab20c83b0a4fff). Is there something else I need to do to set up MUI as a functional library?

Thank you.

### Your environment 🌎

- Apple M2 Max Ventura 13.4.1 (c)
- Figma Desktop App version 116.11.1
- MUI for Figma Material UI-v5.14.0

**Comment by oliviertassinari** [comment]
Did you try to repot the bug to Figma?

**Comment by adrianmanea** [comment]
Can you please try importing the file again? This is quite bizarre, I haven't encountered this before.
