### ISSUE TITLE
Tokens Studio for Figma is not working with MUI for Figma v5.14 - does not pull in base and component styles for dark and light mode

### ISSUE THREAD

**Issue by rachanapand** [mui/mui-design-kits#220]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Import MUI for Figma 5.14  (https://mui.com/store/items/figma-react/)
2. Open Token studio (I have Free Version)

### Current behavior 😯

Base and component styles are not imported in for light and dark mode.

<img width="950" alt="image" src="https://github.com/mui/mui-design-kits/assets/34417134/cf7ce69f-59d4-4ea9-98ef-4c7942b8f92d">

### Expected behavior 🤔

Should pull in base and component styles.

This works seamlessly in v5.11 of MUI for Figma. See example screenshot below.

<img width="1197" alt="image" src="https://github.com/mui/mui-design-kits/assets/34417134/a46931ea-f168-4398-b351-4183be018a01">

### Context 🔦

I wanted to upgrade my design library from 5.11 to 5.14.

### Your environment 🌎

| Software            | Version               |
| ------------------- | --------------------- |
| Design file version | v5.14                |
| Design tool         | Figma|
| Token Studio          |     v1.37.7                  |

**Comment by adrianmanea** [comment]
Hi, we no longer support Tokens Studio in the 5.14. Here's how to switch modes using the new Figma variables: https://mui-org.notion.site/MUI-for-Figma-docs-4eb22360388047a9a31fc19d300a285e#037c560ccbaa437bb87b8ee62718ea54

**Comment by rachanapand** [comment]
@adrianmanea When I open Figma 5.14  - how come I don't see any local variables unlike what the video in the link above shows us?

For e.g. This is what I see (See expected on the next screenshot below)
<img width="1392" alt="image" src="https://github.com/mui/mui-design-kits/assets/34417134/9d5171f5-5ad8-4b1c-a28b-dbd250b972c2">


But this is what is expected
<img width="1440" alt="image" src="https://github.com/mui/mui-design-kits/assets/34417134/2878aeaf-6b15-4198-b92b-19ad7b44a830">

**Comment by adrianmanea** [comment]
To see all collections click the collections button. Here's the in depth overview: https://help.figma.com/hc/en-us/articles/14506821864087-Overview-of-variables-collections-and-modes#Collections_and_groups

**Comment by rachanapand** [comment]
@adrianmanea I understand that. But as I mentioned, when I open the variable model from the "MUI for Figma 5.14" file - there are NO variables/collections seen at all unlike what s shown in the example. 

This is all I see (See screenshot below). It's blank. Seems like I need to create all variables from Scratch if I use MUI for Figma 5.14. That is very time-consuming. Do you have a workaround? I did not find any solution on the link you shared
<img width="1421" alt="image" src="https://github.com/mui/mui-design-kits/assets/34417134/7642e61a-1005-4df8-8d30-f8e22ac38a9d">

**Comment by rachanapand** [comment]
I assumed that the MUI for Figma  5.14 already came with all default variables and colors for light and dark mode. 

Instead of me having to create them. How come my variable modal is blank?

**Comment by splitloose-earth** [comment]
Hey @rachanapand , I might have missed your comment on you clicking on the open panel icon but I had a similar confusion about it, have you click on the icon in red circle (attached image 1) ; once I clicked that I saw a whole list of variables (attached images 2), hopefully this helps
![Panel](https://github.com/mui/mui-design-kits/assets/32595845/973efd01-1875-4da2-8910-0bcf946e127a)
<img width="857" alt="Screenshot 2023-07-31 at 9 39 42 PM" src="https://github.com/mui/mui-design-kits/assets/32595845/f5467993-de63-4dbd-9eb7-5916c47643bd">

**Comment by rachanapand** [comment]
@splitloose-earth I got it, finally!! This is a Figma usability problem with variable modal! Default was only showing shape collection and I did not know I had to click on  Collection drop down to see all collections!!! 

All set now. Thank you very much!!

<img width="394" alt="image" src="https://github.com/mui/mui-design-kits/assets/34417134/d0a46300-5345-417d-9456-faf01e7261a8">

**Comment by adrianmanea** [comment]
> This is a Figma usability problem with variable modal

I spent too much time myself finding the collections button haha! It is confusing at first glance, that's for sure!
