### ISSUE TITLE
[question] Can't download: MUI for Figma v5.14.0

### ISSUE THREAD

**Issue by Raphael-Hyde** [mui/mui-design-kits#222]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Where can I download: MUI for Figma v5.14.0? I have a year of free updates but the site is telling me that I have to pay for this version? 

### Your environment 🌎

MacBook Pro 2022 M1, Chrome

**Comment by oliviertassinari** [comment]
Hi @Raphael-Hyde, you should be able to sign in and download the latest version following https://support.mui.com/hc/en-us/articles/360008775240-How-do-I-get-access-to-an-item-I-purchased-. If not, you can send us an email at figma@mui.com with your order ID, we should be able to unlock you.

**Comment by Raphael-Hyde** [comment]
Thank you, when I look at the release notes it's not clear what files were
affected with the recent release? To benefit from the variables change
which files should I be using?

**Comment by adrianmanea** [comment]
The main file has been brought up to the latest Figma changes like variables, grid wrap, etc. You should be able to see the 5.14.0.
