### ISSUE TITLE
Updating my design system with the updated design kit

### ISSUE THREAD

**Issue by tjamjam** [mui/mui-design-kits#223]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I want to confirm that these are the two paths I have to update my design file with the changes in v5.14.0 (https://mui.com/store/items/figma-react/#changelog)

Option 1: download this new file and make all the changes to the colors etc to theme it. Then ask my design team to start using a new design system file and eventually sunset the old one.

Option 2: Take inspiration from the new design file changes and incorporate those into our existing design system file. Then any updates will flow through to my design team's files.

Both would take a lot of work and have there own advantages/disadvantages. If these are my only options then I am confused why this problem hasn't been solved yet.

### Your environment 🌎

I am using v5.9 and considering updating to v5.14.0

**Comment by adrianmanea** [comment]
Hi, unfortunately, you are correct regarding the available options if you come from version 5.9. This means that if the component names were identical (in version 5.9, we had different names, "Alert" vs "<Alert>"), one could use the [Swap Feature](https://help.figma.com/hc/en-us/articles/4404856784663-Swap-style-and-component-libraries) to save a lot of time when upgrading versions.
