### ISSUE TITLE
Figma Design Kit - Improve - Design Tokens Documentation

### ISSUE THREAD

**Issue by achord** [mui/mui-design-kits#227]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

In the [getting started videos](https://youtu.be/a-PtCSUYgtM?t=90) there is a section called "customization" but there is no walkthrough of how to get the properties of MUI into the Tokens Studio plugin. 

Attempts to import don't seem to produce the results as seen in the video:
1. `Styles & Variables` > `Import Styles`: seem to result in an incomplete state of the Token Studio Plugin. There needs to be specific documentation on how this is set up.
2. Export using `Figma Tokens` plugin, import to `Figma Tokens Studio`: Sets are missing tokens. Attempts to edit tokens crashes the plugin.

You could also turn on commenting on the YouTube videos so we can have a discussion there around best practices

### Examples 🌈

E.g.
Colors were not imported.

![Screenshot 2023-08-09 at 4 02 11 PM](https://github.com/mui/mui-design-kits/assets/945265/54065a96-97f3-49b0-986f-e1ca873c870b)

### Motivation 🔦

As a Designer, I want full control over customization of MUI including typography, colors, spacing, and so on.  Tokens Studio seems like a good option, but there doesn't seem to be much documentation on this, specifically how to work with the Figma   MUI Design Kit and Design Tokens Studio

**Comment by adrianmanea** [comment]
We've dropped supporting Tokens, the library is now fully based on variables. Here's a guide on how to use this feature: https://help.figma.com/hc/en-us/articles/15339657135383-Guide-to-variables-in-Figma

**Comment by achord** [comment]
Thank you for the update.  Will there be a way to automatically sync variables from the Figma MUI Design kit?

My current workflow:
- I have a custom file
- I'm referencing MUI as a Library
- I'm manually setting up variables that reference the values from the MUI library


<details>

<summary>Color Example</summary>

![Screenshot 2023-08-11 at 2 59 27 PM](https://github.com/mui/mui-design-kits/assets/945265/d82efb1d-f3a8-4173-a92e-fbc659d94d07)


</details>

**Comment by oliviertassinari** [comment]
Maybe https://www.figma.com/community/plugin/1256972111705530093/Export%2FImport-Variables could solve the problem?

**Comment by adrianmanea** [comment]
Closing this thread as we've dropped Tokens Studio.
