### ISSUE TITLE
New comment on MUI for Figma (Community) by Glenn Robertson

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#228]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DYPG7_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOinC2RuF5YMI9cjdhblz6JOtzaDz0oePSO1RgybeoNP9-2FEGtIAoRrzC-2FcIkxMrk0Q4H2eZna-2B3jgkJFMWckVNJfk7J1DIcgV0r3AKh6oaLLXfNofPTnv9By1534rFIg-2F-2FqrpikK38LuU-2B0uoRU88fAiXMVbFWrp7EeuwSZQ7Un2XHiL6C0kX1IV82B5oiXoOd7DBdkqK9CHOmA852jOzltoHXbJVx6dP748b5KRw483A-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kroxEsvsqwl9RXRyvAldaBaAUnHwflpKRX-2FQif-2FHD84k6AS_Nn_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOinC2RuF5YMI9cjdhblz6JAb-2FTwVA57QBuEQUMM44Sk1M-2FvV3cu6cF1DftyYsaLlFBE24hOslLCiUJHcgY0nCT5Y-2F92jkcPA8qTPEcdAX4PLlWJf7jzRAHlaJNx-2B-2FSrjulJfm3w35-2BiZBhGlyv4lYBA5QlJmI185IWpuRYGHucdNCnyKTybucA6K2SUb3XfAV2fw-2B2q2GJ0N0dtgASZovGNb-2BnqK3Uxw-2FFsywwAu4S5Q-3D-3D"
><img
src="https://s3-alpha.figma.com/profile/5f6e23dd-867f-4664-b8f6-57af3fc0d2ea"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kroxEsvsqwl9RXRyvAldaBaAUnHwflpKRX-2FQif-2FHD84k6ATErA_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOinC2RuF5YMI9cjdhblz6J5xjph4-2BFoSUKHZt3NGL-2Ba5e-2BRmMH-2B0wcoEuMnfVuPQHNYMoYE7qipE280x2r-2BhZnp5JVc6md63AopAFOjJQ6lYa6zEiUrdUI1C5ZAvUUDcNghSmRb2zAlfnjY7JyAQjwq5MtGOnn7clnryKiENHT2H-2F3t17W7VynQE6o7582DVR47hbijiWdux5NcNXhxkbkZMWuyYwjyUQLi1ipj0hrcw-3D-3D"
>Glenn Robertson</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
What is the difference between this file and the one I download from MUI? I pay for that file but it seems I can get everything on this file for free.
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfJzbW-2BTt1Ml3-2BjzggcX1xluWkul5teXI0qMfRGmbmRawvrkQ_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOinC2RuF5YMI9cjdhblz6Jm4aQl-2FKzlbqRfTouyLLXw8gqzM9UzjQWuWtjJ0lkhSpRy4FKBwBsom0kzE2U2wxeeBWWCwW5j6zOnMWFLdguNJSw91i9vb2UAIsGF4bm5ExTTMJ9NBzHqC1EJ1gViYU7QtdKZrZYpRnLKEJlfYbP7UBZPNG6u9K76HG40i8Ztmgnx-2Bgu9CHaoS0IYODssNqUwdC1U631DrUNoFSi1CyIQA-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
Answered.
