### ISSUE TITLE
[sketch] Rating should use outlined for a11y

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-design-kits#23]
The basic demo mixes the filled and outlined empty stars, this is wrong, outlined should be use everywhere.

<img width="267" alt="Screenshot 2021-10-16 at 23 30 28" src="https://user-images.githubusercontent.com/3165635/137602594-96bfeb19-a52d-4c5b-b200-67f6b229cf84.png">

## Your Environment 🌎

v5.0.0-alpha

**Comment by adrianmanea** [comment]
![image](https://user-images.githubusercontent.com/5917515/138230076-0dd1581b-4346-424a-8780-da43d5931026.png)

This should be fixed!

**Comment by adrianmanea** [comment]
![image](https://user-images.githubusercontent.com/5917515/138230287-4713e51c-12fb-4348-a96c-f674683697e0.png)

This should be fixed!

**Comment by oliviertassinari** [comment]
Half-full is wrong

Current:
<img width="24" alt="Screenshot 2021-10-21 at 13 44 02" src="https://user-images.githubusercontent.com/3165635/138270290-7910f61c-e4e4-4d0a-9c23-d78ec673c0e0.png">

Expected

<img width="23" alt="Screenshot 2021-10-21 at 13 44 25" src="https://user-images.githubusercontent.com/3165635/138270351-8db1c231-804d-4905-b590-85b6750efd21.png">

**Comment by oliviertassinari** [comment]
Fixed in v5.4.0
