### ISSUE TITLE
New comment on MUI for Figma (Community) by Luidy Lazarine

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#230]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DC9Fp_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMmFyE-2FlLesmlnpzDhZaShXCSDkj9DZDPdQFUZJnftKJJ5UsEMHds-2Fc1QFl-2BvQPZtWsvG9tQsxrJDgL8soZDii-2FqCrB3zSjYCTo5d2J2AzEulRGoKPvWQwbGgH0oF3sy-2F3gv2pOKCcnbebhP-2BiiBDxKXuJK1igM1iXoyNxFs-2Fr4Gec0PKAlvR1mSgScWxxFwwbZiiWfoTRyZCKig3Mzt3wMFS4W7T9kCVNU2T-2Fjwa43VA-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4iyX5E47Hlu1FmU5YJbMMRk-2Fh5fg-2FmPTBk64nO7Su526H9M_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMmFyE-2FlLesmlnpzDhZaShXCkhfaMSb-2BblIVxFDAfrBsAOhi1fMY95BAhvup-2F6tfdvmSGIWfO-2BxIQFs3TihGFCKiCfPZMQjyV6Ejh3Z1klOnDkiOmcyFj6Uzrgt4SFsHSWnN02cVH07NuXjTXZgqAez3hsPJ5Y8kMK-2FY6gKLlYTSO7OjzUxnCY42a5vIFb-2B6tGLsqQbo2qk3NSU2-2FGzU4plVMuRKM42Iv0PWKUqdrjdyg-3D-3D"
><img
src="https://www.gravatar.com/avatar/bef04741efb3cbaadb6fae63feddd369?size=240&default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_l_v2.png"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4iyX5E47Hlu1FmU5YJbMMRk-2Fh5fg-2FmPTBk64nO7Su52ppvi_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMmFyE-2FlLesmlnpzDhZaShXMrASmoovKYIcoszsjspDS4eP6Yn0aVIH-2FHoMg5sgPuDEc4MCglgD5Kmwl2roRNn0r1GpRkUxz-2B1TCdgmvMpO-2BJodwACqWx9YrPK5PeQf8YmgZbwgXLzT2onG-2B-2BqGT9TEMnrDJe4xJQmrnOpvOFWs4gDqFG3h8FT1SmD9uU0nT5tqwLM4woVla69ioXQWFvx31eDJBlt7iK2nNEiMux8hpg-3D-3D"
>Luidy Lazarine</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
This library is amazing! Can you send me a Coupon code to help me buy the full version?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfN5YUPyLn8tfkRF1v7yyMzo9zwY-2BOPDVIUoyKUgRGfX-2BIfm0_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMmFyE-2FlLesmlnpzDhZaShXSA7UPabeO3LDCHJY6fEPmIELKQBYM8EIDV-2FQKuRioAGx6oXCozfLkqhOYxUaikyXNq8Aphz-2Bq1RBP6DJeIpuKmAScV-2BmUbRyc7WDN-2BXJywamevFR2Gt-2BCHF-2FXWPB0Vt8kvgyyh78D5scND3x1uCk7Se4nGnDOnwZk5YVIDzIzgVAIkNr4RJ88QuzerlY9FhfH0pHTMG8LKP1yZ445nVdDg-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
Left comment on the community.
