### ISSUE TITLE
New comment on MUI for Figma (Community) by reem alhalbouni

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#232]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3D68t7_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmNSOUFOBDpji425nWxAof423VUQ-2BhMlSvYVawbR-2Bi29nbN0COmgR6lyvcyQWiCg1-2BIuoZzrnDGSfsXiShcvLQGJbqwUTKuD7C0-2BarMPwFFmOJe6ibI1srgMf02xLnNiOlufIQsSdx9hi1nIEktSdM9KV6rVL-2FepoAJp5Ivc-2FdT0FECe0jG0zNX8XFSvQU1MLoMiD5TON3mOM0fKNEVRUqu7Blk-2BM2uqMAxna6KKDm5qew-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6pY7BO46KZ0a173-2BXZnr6lW3MJP4ozxddXZJq9bMTx8qgmb_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmNSOUFOBDpji425nWxAof42FjA9M3vVln3d4b9r2dE77ltsyEbZp3g2rH25fW-2Bu2JEkO6L9XdtUJqSy-2F9dc6UNmJc34vMEmesaPAHwwJ9C-2F-2F8GptfnGtGh1dUck1ylP1l3D1hZEvDsTpfJ39-2FC9wNFhBh0aT-2FcAOGdDb47gMFiwu-2BUG1Pu60Cbr1Fy3mccF53NIpKGKkC5rFZ-2BRgoxki3acbz9P5HyQ5tpFDONbxmMwTg-3D-3D"
><img
src="https://s3-alpha.figma.com/profile/7a545afd-fc8c-47f4-92fe-bdf2abf3edf6"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6pY7BO46KZ0a173-2BXZnr6lW3MJP4ozxddXZJq9bMTx8ZbzK_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmNSOUFOBDpji425nWxAof42ofDXSkFYuPKnkLP4erY7a7mZY2RhjKGmuq-2F4IJH-2FmKMkSSVuIKrcMFU8NFzA4Uj50drhcVX7u4-2FUAkdqf7pD1ezfbn0vpFuJ7LC3v-2Bu3-2B4-2Bc1PJs33pyBxLQohEVRsd3Ktg-2F3vzUwU-2F45ZDUke0eLlHquanej4r-2FE33BG9EY2UVOGQJnDUNjD2-2Bv2euY4fCJry3IXU-2B23RHWfUvTz04AqA-3D-3D"
>reem alhalbouni</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Where can I get the full library?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfBTSUrbAhwpelVBxcIlklk9kPt4pjw6-2F0c9s1U40x16hHWKV_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmNSOUFOBDpji425nWxAof42Z3M-2B5K7oFJW4PNRAim890F8sk8WfvcB4HjQxeWqjFwrR95Xz4AsKaUTPycPHg6BiPmSIvDSPROYmn1AfehvFldlVUBZTEc-2Faw-2FdXRyJWxkp632mvAQ43zuFpYvaRtwCs8mlGcqfS-2BXf99eh2UvPMOmA8A28fAXnzZwuZm4vBLLv8m6OpVAHh3HE-2FbPXMDO8tOjthDsyDGVeNcnQFQzaEXg-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
Left the comment on the community.
