### ISSUE TITLE
How can I find an icon? Or how can I use a Material Design icon instead?

### ISSUE THREAD

**Issue by mmacarth** [mui/mui-design-kits#233]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I'll start by saying that I'm new to Figma and am struggling to use it properly.

I'm trying to use both the "code" and "full screen" icons in buttons but can't seem to find either code or full screen. I'm clicking on the Icon Instance under \<Icon\> and searching in the search bar. Is that the correct spot? 

If those icons are not available in the MUI components can I use a Material Design icon? I don't know how (sorry for lack of Figma knowledge).

### Your environment 🌎

MUI for Figma Material UI-v5.14.0

**Comment by adrianmanea** [comment]
Hi, we have a guide written in the Icons page on how to have access to all Material Design icons. In the zip package there should be a Figma file for each icon style. Simply add the desired style as a library which enables you to access them from any file!

**Comment by oliviertassinari** [comment]
It feels like something we could have in the docs https://mui.com/figma/getting-started.

**Comment by adrianmanea** [comment]
Assuming @mmacarth figured it out? I think we can go ahead and close the issue since it's already documented how to access all the icons.
