### ISSUE TITLE
[figma] component updates vs. customized MUI library questions

### ISSUE THREAD

**Issue by jgobyte** [mui/mui-design-kits#235]
HI Team!
 
I am setting up my MUI library for a project for the first time and I didn’t really find any resources about good practices, maybe you could answer some of my basic questions.
 
I installed the Material UI library, changed its name to ‘Custome library…’  in Figma and published it to access it in my project file. I duplicated the original figma file to keep the source components intact just if I need it as a reference if I catomise something and for some reason want to see the original component again.  Will both of those files receive components updates? How those files will be affected if I accept those updates?
I wanted to ask what happens to my customized version of library if I accept components updates that you guys sent over from time to time? Wont this destroy what I have customized on the components? How the updated affect the customized library?
Do you have any sources where I could read up on good practices when working with MUI figma library in terms? 😉
 
Looking forward to hearing from you!

**Comment by adrianmanea** [comment]
We have a more detailed answer here on our [notion docs.](https://mui-org.notion.site/MUI-for-Figma-docs-4eb22360388047a9a31fc19d300a285e#f4eba31f641f47a197abbce236972acf)

There is no update automation unfortunately, the library is a standalone file which comes as is. Updates can be handled using the [Swap Feature](https://help.figma.com/hc/en-us/articles/4404856784663-Swap-style-and-component-libraries). Basically when we deploy a new update you can need to re-apply your customizations and then use the Swap Library to swap the components from the new version. Let me know if that makes sense.

**Comment by jgobyte** [comment]
Thanks for the notion doc ! Couple of questions more: how you are notifying us about those updates exactly? So If I understand correctly I dont need to reapply my customizations to all the components I have already customized (it would be madness, but just to be sure ;D) I update my original MUI file and apply there my customizations to the updated component and then I can swap this particular component with my Custom Library file using Swap Feature? It's quite huge question for the Figma MUI newbies - it would be helpful to include a step by step video in your Notion doc :)

**Comment by jgobyte** [comment]
Yes thank you, breaking down to steps really helped!
