### ISSUE TITLE
New comment on MUI for Figma (Community) by Jenny_classu

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#236]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3Dn8or_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMjIcWSGgMQpSQJLax94GKM7z5Mp2M5WqSGmNb74tU195NLdAHLJvAO3nel2cSl14MKonVKrtiZPg39bcO3CuEFKSGI7dhhYUK-2FIOE9sxTxXuEoRHaH-2Fifg4Nt3tjfSDBWVS21qsmOdltu0sLowPD8l3qsPRKYDy1iV7pul6raGgibL4-2BbCDPP1lgF3pIE9oUWUJIKfavyt1uYsIHDg4dko9M6cUycUNgdu2svfePr-2FmA-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro0J2FDIiAewpanEfX1T8BxyNLlk-2BhAJGyB9A-2BwGpk6U-2BA_Ni_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMjIcWSGgMQpSQJLax94GKMxQFYchQaGFovH8t-2Fuqmyk7tk2Rw5YySvZ-2FZcFRrErRI3N3Nl7yMrWasMiMJ8SdbP7ycTP4-2FonC5WeN0cdto2D0eGprfnEx1fx2B-2BWhIwuT8BhVEr-2BFEi45-2BDzUqlxmXuAkMkOr4AWMk35OwoZ5QceGBocdDSfG4zeVswr-2FT6egAs1jd-2BjSDg0F4X6ZTmiVEGUVEJZWmm-2FyvSMAsfzfkONg-3D-3D"
><img
src="https://www.gravatar.com/avatar/02fb3acb2ef612865b16c02665b71b05?size=240&default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_j_v2.png"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro0J2FDIiAewpanEfX1T8BxyNLlk-2BhAJGyB9A-2BwGpk6U-2B1YjU_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMjIcWSGgMQpSQJLax94GKMS02wO0KTxDNuruT2Y5Zfo-2F2JrsFOUpCnu8UEjLE-2FI6yZYQ3bXzPnpgqc40iKx0Sqhk4BXBif9epXlQ4a9RjxzBrGkXPSlUXF9BhVSnC2jCtshT-2FMKf9tka8etqBTn9D2lC-2BGbVVE9jvodpYnMVCXbOrVYtbbjauO3c-2FbRg2EWzwnz7eQx0XechHLMwWqiIH-2FDHYe9U-2B1uoX7nXkOYM08eg-3D-3D"
>Jenny_classu</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Hello, I purchased the paid version. I want to change to dark mode and use it. I accessed the variables as instructed, but there is no color palette item. What should I do?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfCeEiZoEkELsI-2FfJt0X5wAqJxg4Ex3e8l6aKFDlfRKDS-dqZ_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMjIcWSGgMQpSQJLax94GKMxfGxAvmAbc-2BovtjXakn0kHjaT-2FRbijM-2BkiAQOjEw6RpOhsRSUipPk9-2BUUwvobm1CLw4u0Rw9dmm12uQYQHV0LtSzNjv3oFtZmWi2U0e3Vyoy6bqRSKnvgA6qy3N-2FGzjmsHeKD-2Bqmb84YhFR8sJ-2FesA-2BMSm3EXqjjS3CdS8xqAz9Pir7TSvuW1qiWcdD6-2Fbz2CaiSV7KWyWM1en13gWnUNA-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
Answered on the Figma page.
