### ISSUE TITLE
New comment on MUI for Figma (Community) by Jenny_classu

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#238]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3D-qQn_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPzbpQAoNj-2BfvZByxexKYfajZLX5gxSruPuKj7upApU1gP1YJHQztNZCIBzLQrHglvb8PIxthXxkbOexpsXJQTflshuIAf-2B4LYjRF3b9fVCQ75OhypnZCdFCFDXjDz16vDf3AbMaOXADRadpx78e-2FRuvXxjPUIuvuJl1-2Fq8gpU0u5yDKFOfoD1L2Bt4-2BvFZcp9-2BTqAwy7dqfZy0PAqnMPgT-2BoAHeyEggAOzmlCAXK7h4w-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro0J2FDIiAewpanEfX1T8BxyNLlk-2BhAJGyB9A-2BwGpk6U-2BgZST_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPzbpQAoNj-2BfvZByxexKYfaw8sLB4xxf501BwIi4kcqfDoKGqW1J5rnrg4wyOeqNzb2VaRxOFdI-2BH6Nv4BSuCdrrVylz0oGX2Kt-2BlpV2waQBeO1njB-2FE5Pa3-2FtR4XJF3dxFxa2-2BBOInPfYCgVfzf6s57pyIvRtzkg2ZZun2q4t3ptHkhRf56CVF61EajgLfhn7wt0tdtH5p5J1FgShBVYstXGpQUhdhxnkUkvTUr-2Fd84g-3D-3D"
><img
src="https://www.gravatar.com/avatar/02fb3acb2ef612865b16c02665b71b05?size=240&default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_j_v2.png"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro0J2FDIiAewpanEfX1T8BxyNLlk-2BhAJGyB9A-2BwGpk6U-2BRrWu_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPzbpQAoNj-2BfvZByxexKYfaPcF6nNNjumax1LtIabTVXvn2GnmGoQi9NAer3lKSRuFCZqXBpCk1ayiSNiuF28ZMgigIajI8dI2A8OU9izoSEx8uWt14Atgg3QFBm90fV8xL40tgPcC2yqaOSuzHbw23wrwHTOavhjmK1M133F7sU1cnLHZHYmLCz6IEIGdpvMgU2Nf5sVnymwr3ieY3RLl-2FAfhVG-2BKHhLyiKHFIEltcAQ-3D-3D"
>Jenny_classu</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
hello. I&#39;m trying to customize the color, but when I click variables as shown in the video, there are no color-related options.
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfC77O1SI6lq7DpE0uDjkO8cla1yYHclWXe1zFms4ixQjt5z4_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPzbpQAoNj-2BfvZByxexKYfabKqteyErtAbSzJSc1Dj89pfRA9O4iERRD4NZedDOjZrpLo07-2BpvQzcO83rJ-2Fj4EwqwJScqrH0rcpN50MNZGXXK-2FMAlM5iEgqJ4IXAIi-2F93OPdqMhlLViFl2VjqvLZIq6OrVAjz7o6eNda8i-2BDnVncRavrWKBE6R28NAt0-2BqpY0vdPDCWHSC0RqTEozdg3UiJS9OH9Qexvxn1YLV6PswH8A-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
Answered on community.
