### ISSUE TITLE
New comment on MUI for Figma (Community) by Karthik Rao

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#239]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3Dpbt9_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmM8SkU6T3Q9VHSuHzVLfipbKWPmly4cqlFI8Km1IUi0a3JypfmC95gLb9q6hWQnmWik4v66Vv3G-2FWqWajaLFxSmvQ7btwZV8hnoeRgpQ3ju9mWxa2jd-2FgY-2F-2FHGdPRlBTiGnZ-2B1Y6Msj5tbsKmmSy2MSJieLb2D8XeNhWuz9rOzLrAJmLW6uVe-2B44eypxJqXK8OCA-2B9L6U2tGiCY3UyDra8-2BAuEkFm6xuQtBMeMDlVvbNA-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro-2BpglstFuwQmaQTjJRWro0pf1I3lM9H-2Bm9BDt7cB0Pc4Wbuj_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmM8SkU6T3Q9VHSuHzVLfipbjipN3Hl1OFgYDeceNXAfMOzvY7drgI32FnHzly3c-2BYeb8tIMuR-2BntEIu2xLIPZhWvKIe3X2ruFpJBqAjupQuFANu-2FkJVu-2Br6H7XvfP-2BzjMqpRPpzla7qfn-2BESxhiFt1A4l-2B7PvIaemyIGH6bmWs-2FnMYeqG-2BjuO9vO3oMT3Wj2lw9-2BpImr3JD1ouadJFKEe3BXjSF4sV6dhbvCFDmGsYGGw-3D-3D"
><img
src="https://www.gravatar.com/avatar/a9ecf61b83f430e3ec6cf33d3384a02a?size=240&default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_k_v2.png"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro-2BpglstFuwQmaQTjJRWro0pf1I3lM9H-2Bm9BDt7cB0Pc4ttVl_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmM8SkU6T3Q9VHSuHzVLfipb9p9za9v3T68LepwW6dBH66GJ9UDDCzedyv3wmgMV3F1P3GgVYJzkg5l5LvjiL7Elpre4Zd7oWINIjML5lpyp2XiYn4h3AvUv4N5lSvBdUgTq2VSw-2BRRCzntEbYoSE-2BUf7UbvtqxxrdCywR3BgCYGvj7enHaILI-2BRzCPr-2FwzCNFT2M8CLHf-2B0oRkKA4bW95kk6B1MB7Tk3ugispK5yX0yWQ-3D-3D"
>Karthik Rao</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
hi everyone, so my team is using the material v5.11 paid version.  <br><br>I was trying to locate versions of the menu where I can add grouping and check boxes. But unable to find them. Do I have create them ? <br><br>* https:&#47;&#47;mui.com&#47;material-ui&#47;react-select&#47;  (for reference). <br>Also aren&#39;t all these variants of the &quot;select&quot; menu ?  unable to see them as that too.
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfBXHUzOxa-2BzaQsjrRHLdoMpB7b3seurzmdnTe5wURxWIMsUf_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmM8SkU6T3Q9VHSuHzVLfipbGqS6TTgY-2FTLPpA-2F4vMfoxN40gBzspiWCjb8e3SZ4bWF7dLIWUxb0psyU4VM5RFSgQibtCyPthLk4RQQavUxW0csphabxbGEcJv64iPLTK9LkHEaolPQpc3sohguiHIAv-2BjoHAhNCyfK2ERAyAmFLYQleVH39OQDhkZAg2Kk3ztZGjT5ACHqwXzoHrQFOZ4MkI0eAAytyexnXLu0W68c8eQ-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
Answered both in support and community.
