### ISSUE TITLE
[sketch] Add documentation

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-design-kits#24]
## Introduction

We could create dedicated documentation under https://mui.com/design-kits/sketch/.

## Questions

A list of frequently asked questions that we could probably cover:

### How to handle updates?

Sketch doesn't provide great mechanisms to handle updates. Ironically, some of the future work we plan for the Sketch library is around this specific pain: make updates easier.

Up until now, it works as follows. We avoid changing the existing symbols. The previous updates of the Sketch kit were mainly about adding new symbols. This has limited the pain around processing updates. When a new update is available, we send an email to notify you. You login into the store and download the new Sketch version. Then, you can link the new Sketch version of the kit as a library. When the symbols are used, you should get a "Library updates available" message button in Sketch and an "Update Components", for each symbol update.

https://www.abstract.com/ could help with this problem.

**Comment by adrianmanea** [comment]
I would add the following:

> Alternatively, we are aware there is a plugin called Symbol Swapper which might help swap old symbols with new ones but because it is not a native feature of Sketch we cannot recommend it and thus we do not take responsibility for using it.
> 
> Link: https://github.com/sonburn/symbol-swapper

**Comment by oliviertassinari** [comment]
Sketch is likely going under, closing.
