### ISSUE TITLE
Why in the figma variables of the MUI design system, certain colors are put in the form of tokens and others are in the form of HEX code

### ISSUE THREAD

**Issue by CharlieEres** [mui/mui-design-kits#240]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Why in the figma variables of the MUI design system, certain colors are put in the form of tokens and others are in the form of HEX code ? Plz :D [[enter image description here](https://i.stack.imgur.com/ohCDW.png)](https://i.stack.imgur.com/2qEKg.png)

I don't really understand the logic of colors in MUI variables

### Your environment 🌎

v5.14.0

**Comment by adrianmanea** [comment]
Here's our [notion docs](https://mui-org.notion.site/MUI-for-Figma-docs-4eb22360388047a9a31fc19d300a285e#f4eba31f641f47a197abbce236972acf) on how to change colors.

We use hard-coded HEX colors in states because the opacity of a variable is immutable.

**Comment by CharlieEres** [comment]
And why not use shades from the palette?

**Comment by adrianmanea** [comment]
That's what the design system is doing under the hood for the states (hover, active, focused, etc). Variables are not that smart yet to create compositions from other variables (e.g hover state is rgba({`primary.main`}, 0.08)) so that's why we cannot use a variable there.
