### ISSUE TITLE
New comment on MUI for Figma (Community) by Murat Günaydın

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#242]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3Dnj5y_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMJJpfXJfZGjrcZrzjHsiUb9Vewxru7jm7B4mU7w7iXT33E79QkWU7VEFpHZyq93X0n0NKVChAI6AffAn50Wuj69-2ButU4XuLv0TPAr6PgPTg7X6EL1uD0nF5wwGOBY-2FEjcSAXYSpq41yKXyQMVGLdsGfqjWnaEM0-2FhGqe5mF039jl6aUnjP3EMqhrC3rm-2BiUbD2rIp7VOh-2Fz-2Beg7jswlm1voS9ZwsrvjRrcK9rTG7iLgw-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro0OhfCaNq6tB1gTEb5CrKQiS9pNJWZsodWQSFSMuT8J51VjO_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMJJpfXJfZGjrcZrzjHsiUbcf6QM8S2KAMKbAlwdgdgKT-2Bgy4ACG6dZE8DBuiCkDxjBmf-2Bc-2BhTUpr656EfIo0vu3LwolJaZdabnv2m-2FeHwI7Cp1rmfj8pir3y-2BjHwlPksHv3kqk4Q1coYZERkxSxrNjMbKClEUwQuE3UqXqVHtrz7jrUKPC8AlbHCWh64V37dGdyNbyH2nP0IihJVc33fybkStBP0hzK-2FES3tiF-2F5S0ng-3D-3D"
><img
src="https://s3-alpha.figma.com/profile/932768dd-b81a-484f-8548-8979cde75e56"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro0OhfCaNq6tB1gTEb5CrKQiS9pNJWZsodWQSFSMuT8J5Hu33_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMJJpfXJfZGjrcZrzjHsiUbIRc3F9lI6VoAyNwOPeBpTGeZxi669Hr33FTd8tbeEnUCJnT6LUGWsmauLuoS-2FbfjYUov5kDncdD6WQlVdi0qoe3uHWHCEff8viMoTLaXgMRH3waqGlOSFSLgvIM8xl0Jcob1y9PkZUhW8lSWOZz3ltcIglb4flF2hP53K0dE8aVwESUvq4fOe6nY-2FwcW-2F6O78Lhc50-2BGSlVq9V-2Bs3Qwyiw-3D-3D"
>Murat Günaydın</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
zaldrian Hello Adrian, when I accessed the file, there was an error in the file. Some components were missing. Probably a problem with Figma. I updated my score.
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfARVOVM4JUsbH6Dm3-2BwOJwNrHz1AyMzNje53W8ECHUEP5MU3_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMJJpfXJfZGjrcZrzjHsiUbuid81zWN4-2BVCxaNx4AjCCKhfw6iDKtlRlcTs62jLH0STqTBb-2FJIuTx0WivKhlcledcq5a55y10IbTVwSrX-2BUSmESPO3lWg8w3XwL-2BCZQY1Qsr-2FGAhSqpZKzv53wwR50eWfD2R9ucmcdeogfWxvmKgtZoDCcnxlyWpnKVdRNg7DwMgg3guDTwItUj-2BqV-2BNCihKNzwvf2yw5HseMGcpC16HA-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
Answered on the community.
