### ISSUE TITLE
New comment on MUI for Figma (Community) by Natoora Tech

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#243]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DIZw-_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPHZDhJ049K9qErKD0q3DbAbPOwmMVGJWHNE4p-2Fr3HqIZRrw5FIZuPLP5zBoIfkiMi2TJtfytEhVVGcEHp5NlXMZQFMYk8fo-2Fj7D-2BZOcJqDj7u2tbOyBIxf56oyqPGCqghappx2ATqm6bmXlhGJV3Jx8ftE7ignOb8jUmMTfGGUZkvTllJd2Qr9jvQTsQWDfnrFY18knF4y3AA4gm02r8YH0VaP-2FDrvEdPP6ERtWUCvsg-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro-2BzgwbCXppSa7btbd9xBhNzZxQoBX8OWh5dOMjCRK7O8KqK9_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPHZDhJ049K9qErKD0q3DbAJ2UiuwtwxUEx78eTRq6wcUF86eBUOZah82eF3h2jl6ePQ7-2BhguaW0y9WkYOP4WgOSiUWusec0w7ikz-2B9mEtzqnuyihD6udNWN8ihxxfn7Ns53ihzVk7npfkxGP9sBEh5RRX47wbr-2FWLYB4U00nbDAQgQH-2BOQs-2FgOzgcsZzoKHfI-2F9Jju2IWN1xWPIKyMc9TEd8Jx8aOqX-2Fe7aPTGuC3umw-3D-3D"
><img
src="https://www.gravatar.com/avatar/97bd0f7ffe491328c845813bc0864985?size=240&default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_n_v2.png"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro-2BzgwbCXppSa7btbd9xBhNzZxQoBX8OWh5dOMjCRK7O8OfWz_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPHZDhJ049K9qErKD0q3DbARen0b114SjwbIlLUJFznnXtJDt9-2BwbQYsNPsyUM7INZjIfVaDAU-2BP-2B7Y3eWZXURTecOaTlSzclFGi7PKFfOi5Sp2CfkWPinbOui8NiQcn92jjY22xW6lrVSQFXJB-2BO6JnA5akiZxeL5JbEt9wpL24xqgGT6T-2Fxrxt5cOC7RkQdMTx15JNONEpAlSWxbBAL6WiIzgCJVlCTi73b8Ov6yM1g-3D-3D"
>Natoora Tech</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Hi, I have download the latest version of of the MUI and I have noticed that are missing all the dark mode property. Are you aware of it?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfICbXCQRxge2ak0cwwPMMPg6Oy672rFqodY8MrqH8A7zCqpB_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPHZDhJ049K9qErKD0q3DbAZKIUpITfVlNeGxCMeMR3b0vWozPh2-2FEUYAS-2F016gK1wv-2BKgPrT5f-2BoX6FzUr1hnKD1N7ufzbw0sW0068Pm2uDitGEvFGO-2BbzmcpkeBkAdj-2Brhd20fG8grd8i0-2FCzCyuIHKgmHmSCLGbgrbAc4kIwjcepr5O2fxAY0KDu326REoWc2PZcZlMDY-2B0ZJ5tLQJihwO9FPapLIoXnZbhZqFeBrg-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
Answered on community.
