### ISSUE TITLE
New comment on MUI for Figma (Community) by Natoora Tech

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#244]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DDdE0_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPrJQ7C5nzIKnXZxNGzAJy-2BRQUTh-2FT-2BTQLXodAg-2BkboV-2FDGZRYjMlasvNJS1NPpF8edpoz4xURaAIizcIsQF1rKBYkYCGyw7CsE1VHN2uptCWpcAml9AY0y3HxESJnvEaWzTEUQtNZkXyV3KfPpvswPKlzZQnJyID9gJRt2v26g4D1-2BXrjvWitrnhyKTkyROXmT-2F4cR-2BdfpIS1HtkmaMWNUvXJnHE1pc0Sp7KvS5LgoDg-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro-2BzgwbCXppSa7btbd9xBhNzZxQoBX8OWh5dOMjCRK7O8abHG_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPrJQ7C5nzIKnXZxNGzAJy-2Bv01T1p7QZmLGnNi0uWBjU0PO5TlY6bcz7aFDfc-2BX0MAv96ztY9xMzli3EseNGoZxla53tjVL-2BveGjxmpSLJxWqA7qbUT8R8NygilkYFhcOZUw-2BrEJPwm2ZpZwVqIwdDGm4GvjCs2n88gWtyEFC37RGWumxuPKeqKIP-2Bz66De198tvM5HQsxnKglc4ZK1vfGBOh2e3kBaWkXkQvjEY2fD-2FA-3D-3D"
><img
src="https://www.gravatar.com/avatar/97bd0f7ffe491328c845813bc0864985?size=240&default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_n_v2.png"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro-2BzgwbCXppSa7btbd9xBhNzZxQoBX8OWh5dOMjCRK7O8eHD2_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPrJQ7C5nzIKnXZxNGzAJy-2Btd2B2JgF5J-2BBOZaWD-2Fy8DYZz6L11Z3HnWmAjjf-2B6qVyuprck6VkKJaxVTYpV49KIRo5RyKi100aOOhmejfAYssKpTKH-2Fi2PMFGQ5xHGVeZ66vSXYvvCWaZmPymzpCnsSCbuhTTE3VLm98RzQaDE0Y3HjnOhUT-2FLsom0kVbNdWCm2bjLsnX3xAdTev7vY22BgnWNRTIOlyb0TyWAcQtwlzg-3D-3D"
>Natoora Tech</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Thanks a lot adrianstefan
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfPpFThRsro-2FgnngrsB-2Fln-2BvSz4ng-2Fuh7l3AKgUUkRwB30YeP_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPrJQ7C5nzIKnXZxNGzAJy-2BAAsCW234wz5-2FPct8Ch8DYUt10g7WgFKsy4gFhmUP9ERY5YvYkTPVaWJTv5dlLyPzVGBRrYsBW9gtaAyqHU-2BZWnlnb41FSLXArv2alU1h8aPpqnyV1UkIzTZ5bUxJ8LzVX3kGfm2cwjxSF69k9UmSAuBkbxgKXFi4s2kMaczTd8ngvAQxB3RrZk6vgTmNXDgih1Nevv6X59TjXjNtG6j8RA-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
Answered on community.
