### ISSUE TITLE
[figma] Add support for Font Material Icons

### ISSUE THREAD

**Issue by adrianmanea** [mui/mui-design-kits#246]
### Summary 💡

Add support for font icon in parallel with the SVG icons.

A solution would be a type-of-icon boolean variant: SVG and Font

<img width="410" alt="image" src="https://github.com/mui/mui-design-kits/assets/5917515/55a906d9-67ab-4ca4-8276-6b5ea07575a2">
<img width="225" alt="image" src="https://github.com/mui/mui-design-kits/assets/5917515/fa2c1559-ecd7-449b-a413-1e81c41f3d71">

**Comment by oliviertassinari** [comment]
What's the difference between SVG Icon and Font Icon? It's not clear to me why we should do this.

**Comment by adrianmanea** [comment]
Right. I believe that font icons are more convenient to use. You can simply type the name to render the icon, and it also includes the styles. Currently, we have only received one request for this.

**Comment by oliviertassinari** [comment]
So if I understand correctly, It's a matter of Figma UX. It makes sense. We might need to document this if we go in this direction, it might not be obvious for designers which one to use.

I also imagine that for Google Symbols, only font will work

**Comment by adrianmanea** [comment]
We're supporting font icons starting 5.16.
