### ISSUE TITLE
[question] [figma] Using Typography component inside a Stack

### ISSUE THREAD

**Issue by pulasthibandara** [mui/mui-design-kits#249]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hi,

Im trying to swap the default "Instance Slot" component to "Typography" in the `<Stack>` element. However, Typography doesn't seem to appear as a "Local Component" or not searchable.

I have seen Typography being used in the CheatSheet <Stack> component. Just wondering how I could get this working?

<img width="253" alt="image" src="https://github.com/mui/mui-design-kits/assets/8141799/acc2779d-2310-42e3-b0ea-8e5155d5e268">

Thanks :)

### Your environment 🌎

figma - community version

**Comment by adrianmanea** [comment]
Make sure you have added the main file as a library and switched to the new file you are working on. Then, from the "Local components" dropdown, select the library.

**Comment by pulasthibandara** [comment]
Thanks for the quick response @adrianmanea :), The <Typography> and several other components seem to be missing when I try to publish to a library as well.

**Comment by adrianmanea** [comment]
What components are missing? Are you using the commercial product?

**Comment by pulasthibandara** [comment]
I'm using the community version, There's several missing that I've encountered so far

`<Icon>`, `<Typography>`, `<Chip>`, `<DataGrid>` and probably more... These are the ones I see at the moment

<img width="286" alt="image" src="https://github.com/mui/mui-design-kits/assets/8141799/a3df7a0c-5b0c-4096-a019-b644c72ba4b8">

**Comment by adrianmanea** [comment]
The community version has a limited number of components compared to the commercial version.

**Comment by pulasthibandara** [comment]
Ahh, that make sense. Managed to work around this issue by creating custom components from the variants in the community edition. Thanks.
