### ISSUE TITLE
Is the sizing variables in the figma library 5.14.0 same as spacing "blocks" component?

### ISSUE THREAD

**Issue by Oscarf77** [mui/mui-design-kits#250]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

You have the "sizing" variables and I want to know if the "spacing" blocks in the Figma library is the same thing?

### Your environment 🌎

MUI for Figma v5.14.0

**Comment by adrianmanea** [comment]
Hi Oscar, those are actually the spacing variables. Good catch. We mistakenly named that collection "sizing" instead of "spacing". There are no sizing variables.

**Comment by miyabern** [comment]
Hey, are there any plans to use the spacing variables in components? Would be great to be able to change the density of components in a central place.

**Comment by adrianmanea** [comment]
Hi, the spacing values are indeed bound to the components. However, only a few API components, such as Stack, utilize them. The rest of the components, like Cards' paddings, have actual hard-coded values and are not bound to a variable.

**Comment by miyabern** [comment]
Oh, that's a pity. For whitelabeling purposes it would be just great to use adjustable spacings. But sure, making anything available in the Figma library, that is not the same in the actual framework doesn't make any sense.
