### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Subham

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#251]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3D1CV4_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOGIF12Fr0LAfZKcwIc-2F-2BXRVf4A370iOISddDIsUDbr7ndsj3fc-2FezveRekkiULdb87Q9dhFrv5Wp2qJAVltok3P-2BjiSZi1YSfgMUk98YHAOkCu0gPrBcYKiFzbiq-2Fzhn-2BADqid6y4jgRFpGBzdlWuLP7to1PLatDgN4kJaCTypQQzMBL8QjVfOlCj-2Bup1j0k5er7o0htcJ9ksGbNLEOCFZacFiQU0aMnbGPTUfjMLgXQ-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro7-2Ft9SzmG-2FNlVO-2FPtIa14esVK9M6pPAtVWcTfaZ0SHy39Met_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOGIF12Fr0LAfZKcwIc-2F-2BXRKExZDuhalKEJlxltAY2Hj19QaPHKL4-2BaBGXG77Gj7ivygA8qVKIvuZLNRA3lN6GG2DdiRmSpidpnveXbzN2RyUSc55AFBzKtT22UEl6fGhDuRD9qAccUWBAvcVXPhi6KY1q8Z-2BhtDk4jvwm073h9hEnc9F-2F4zSjtGw-2FNpt2OtsWxD8Hbte4NR-2F79rX2097j5AcjRhbqZ-2FrIOABlkLF5ilA-3D-3D"
><img
src="https://s3-alpha.figma.com/profile/cc93b6dd-c6c9-48dd-aefd-a7ecf5ff38cc"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro7-2Ft9SzmG-2FNlVO-2FPtIa14esVK9M6pPAtVWcTfaZ0SHy3RFBm_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOGIF12Fr0LAfZKcwIc-2F-2BXRYv4gsYaQ30U-2FjftT5iOt9YA9tnJCQMAIYLb2LJvu6CUhETcXmk-2BR8LHQWOTEVRjxw8PpOuwfJue332MOsjcjXKHnsHSqBEeEQCF1zjj-2Fls4mnsxfbohBhAIBnpYYmTARc4oG7Zr9h2keQfkKj7QJ7xtXyMRlhBxP-2Frf1CbQJI1hfCAGNOLqj74MTn3nG-2BNCPnvv5tvgqgN18NSDYI7nb2Q-3D-3D"
>Subham</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Everything shows blank :(
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfHyHQhTfoJmZIpGLa3ULbu2uXnBW0SjwKDSKOzdlHwArlA-I_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOGIF12Fr0LAfZKcwIc-2F-2BXRrJO7Ep9fUp-2Bq1uE6YPJiW-2FzQ5-2FIB-2FuKNrfRTkycBNctTVzlPZTZK4h-2B4fRkW6aOLWNDfYB86sotu6iYxqgn-2FkWSGuvUonIyW915bURPdrJDzpLUU3WT1g5mwhivhnvvKfTdwz9GjtgBjDEIaT9ZMGuZBmsl3dLa8aVY2LWWEMSouCqUlm6Z3ar4VhGF8Pf-2FWxrZ6vEG-2B-2B9hKG4ulCexdqw-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
No context provided, answered on the community.
