### ISSUE TITLE
Support in creating cards that work for my feature

### ISSUE THREAD

**Issue by vnssbelle** [mui/mui-design-kits#256]
Hi! I recently started working with the Figma Joy UI kit and was wondering if you have best practice or best approach to create the different card content and integrate it within the design library. I loved how the MUI design kits integrated instance slots to allow for this. 

Is this coming soon to Joy?

Thank you!

**Comment by adrianmanea** [comment]
That nice to hear you are using the slot instances in the Material library! That is correct, we haven't done it that way in Joy for some unknown reason. I'm happy to send a revised file with the instance slots. Simply write us a ticket at figma@mui.com with the order ID or the email used for purchasing and please mention this thread.
