### ISSUE TITLE
[figma] Add additional prototype interactions to a component that already has one

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#258]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3D-DCa_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPNrr3NNqEbkXhVufH6mzeRNTI8zQVOnqzwmUjpI6LHTnY7CuyKilu23k3mISBfVQ4DNLgXyMhKnxDy-2FiWXQUUCB7RkLbbrsVuOGUm2dCYiZx4vvxz0BXrxQR1yN71O-2FFgnA9V95pPgOGT-2FJxPEqf9IEk2C57nkZj7eNqjF-2F00hNUsGYHVGYsCTltiyQEpFJzQXmV6Z2Ssgsn-2BASXNUgRZMAboJy5RUSfworuRCjFjAmA-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro0OhfCaNq6tB1gTEb5CrKQhcCb6oqizyZC28eAdFmZvwhxPz_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPNrr3NNqEbkXhVufH6mzeRQAiOFhzK5J1KPd1X-2BZ1lOh-2F1U7BtR-2FCfNbvOl1WlO-2Bp7WiK-2Ffwh8LmAE6wDia-2FefaU8IPqUF8ix0VPpM2-2Bw0L9evwYYBtXgkgSkIpqTpDRWM1q26fj8ghr3d3KYdVkIliNfrvnqIgAz7MNh8gIuS5nFgkvaf1P5aLq7E7uugHXYgZcEtaVWj-2FnnvlcPqEGO-2BfxVf8yONKLLJSqRxReRwTg-3D-3D"
><img
src="https://s3-alpha.figma.com/profile/a9e06447-b247-403c-85a1-633fab22f17a"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro0OhfCaNq6tB1gTEb5CrKQhcCb6oqizyZC28eAdFmZvwPieb_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPNrr3NNqEbkXhVufH6mzeRyTGd9O3fuQY7RbYSg-2Bt8MZH9S7-2BRonzSpUrQ3zpUT-2FlnhZX8lrrn3-2F9m4TDxcXgW4Xa4LiIMCNlvPAqXS8-2F1omPvSico3GVUU3KzbXY1n2PR3H-2Bz30QMHkskNTTdPbssW-2FLRkSMNpK9fQ3StN0LT-2BTmZDcIbPdOoYXmdyl09jwqIIP0rY0jr-2Bm6QfjepMl7JMwjqIWU59OmsbFVRRNbE4w-3D-3D"
>Marcus Pedersen</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
I have a very technical question. I have a document where I&#39;ve used an asset from MUI. But when I try to create a prototype with a dropdown component, I want the opened compoennet to link to a new frame. So I&#39;ve tried it multiple ways but the one I thought would work was that I use both the closed and opened dropdown component and on the opened one I add a click interaction to a new page..but it wont work because the component just keeps refering back to the MUI Figma library which doesn&#39;t have this interaction linked (obviously). I can just detach the component and it works but I&#39;d rather keep my MUI components intact.<br><br>Also, maybe I should just remove ALL &quot;change to&quot; interactions that MUI have on all components? Would solve this I guess.
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfESKsee0093NpqYllahwhiIuhH0bR-2FA4D-2BCzDTORkXLvZR8i_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPNrr3NNqEbkXhVufH6mzeRZ0rjui5bUEg5PY-2F4jDg21UAQuHvc797uhUOL0AZHvvgaXpjvjDLeAVJy0oYKt2D77uanATcKqzC3FuCqNtN9SqYhxkSxcQsTGbbbFnf8cGr-2FNFWWfmn45HyGuXMYNhQjLUMawtRCEeiuvwntupilfTYulzRUGIktpbC5UPd0W18EizPczopVilEX4CL7SAQNS85gGlpzpcf3ugW4g2UQBQ-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
I've provided an answer, but I'll keep this open for 24 hours in case the customer needs a more detailed explanation.
