### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Pierre Monico

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#259]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3D0XBR_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPDS2EIYjOIcl-2B4QG43FnaXa5tKl2IVee469tHNvxooQdSwvYUKrli8nwn84gCh4rDEWQI4PyTokB1YOZBdTLRjvOIDPBIT6-2Fgf2KesdvBSZ1BT1j3pfJqPbMWacI3sR2dSvFuV7tQpZ47d90BQmsSXIr9Ho7KBxrex4-2B0PoTz2lNzaMh-2FZWGSzI-2BX0SG-2Bu-2B3zUMv8O6vFJuHM-2B1iO4EzLz6o7XZoi5UDs6aIzz-2FAAPnQ-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4krowNN0jUZoz3tIELsl7mx0jxNXo-2BZ7qmaWyoBt38TKo7BhwCG_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPDS2EIYjOIcl-2B4QG43FnaXWgPmveLWqzTfch9QObFm3ibd5-2BbN0PWotE4PBURZ8cHspTlC9cvzmzuL2VhDtQxrdOBCsj9-2FJxtoDdRK25bLiQKNYBb0WF0uL6tDH5IpI1uovir3uwRqA5QFGXe1h7vC-2FfTN1bQBpNGi3jFVUcX1XpzDbiiffVGoAC3b7-2FM8OAZEukAkf7hzljAWRj6QI5mjnWkHmWbJSgiC65uI7VdrIw-3D-3D"
><img
src="https://www.gravatar.com/avatar/ac6ff99e07a52268c54413a8abb2ce5d?size=240&default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_p_v2.png"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4krowNN0jUZoz3tIELsl7mx0jxNXo-2BZ7qmaWyoBt38TKo7B6GUD_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPDS2EIYjOIcl-2B4QG43FnaX-2BH0BTl1Jt8PkS9OZ5Yzh93jgw47Lhn3qFVoML1ZjTl3wVgmUSBXKa9T9rsFEIGLu6r95FR2aQXVKKhGKfj7Md7QCFn9Yqcy4166fGVVQa-2Fa3LEfi7QsRbosh-2BC3hroUqnXp3xZM8KJduXcbJkp-2Bh8-2BpBbWcAUlWKCjpfWTAZGteQFglaYI8askjKBox-2BQZWQf1pJTj4DvRgK4K8xYxzFAA-3D-3D"
>Pierre Monico</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
How can I change an icon within a component? I.e. in the &lt;AppBar&gt;, when I go down the hierarchy and select the &lt;Stack&gt;, in the menu on the right hand side I can select &quot;Icon Instance&quot;. When I click on it I can&#39;t find any icons though? (I think because they are from an external library)
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfOWpV7apSG6zhfPDbXgpRefHtXVbJMjFEXECL-2FrokcGhkcgl_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPDS2EIYjOIcl-2B4QG43FnaXxXuWv4ggXkXylkeZCGxUk6ebszNZ9JY3ut8toa2R6mSloVQSKFLE5ZWtvaARqOuXP5U65-2FmddpQ0a6D3-2F-2Balr-2Bn82q10AMEoraxHA4zTTSfWmaNltBx-2FmnF-2Fg8weAHdwlnTd9C8WiSCj0U76SurXYZRc6JVLnELvDHEzFQo9ce91fwXZsdWU6SxiaWuEZAQoKfMpL0pZHdOL7gGL-2FpLWbw-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
I've provided an answer, but I'll keep this open for 24 hours in case the customer needs a more detailed explanation.
