### ISSUE TITLE
Trying to import - Missing library with 169 components

### ISSUE THREAD

**Issue by jacobtscher** [mui/mui-design-kits#260]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I am trying to publish the assets to use in a different file.
I opened the community version of the file, moved it to the team and opened the library menu.
![image](https://github.com/mui/mui-design-kits/assets/44966038/ce188678-43a4-4bc8-90cf-dd4a848531e8)

There it says Missing library with 169 components
Am I doing it all wrong?
Is this how it is supposed to be?
Is this feature only part of the paid version?

### Your environment 🌎

MUI for Figma Material UI v5.14.0

**Comment by adrianmanea** [comment]
Hi Jacob, feel free to experiment with the free components provided by the community. However, if you require the full library, you'll need to purchase the paid version.
