### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by 이주희

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#262]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DzaNK_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPxGFaSFetxc0wQUaKCfC3W9I4vgW4AXsKNbzQ301RN-2FwDS6jxd0IlxKUGe8r5gg0prwMBagpFvWP5lzNDQsAlAf3JAh6rYs7l5vQUumo-2Bqig-2BE7NZWzr3Jba5b7NSKZNWviSuiO4nBwmqHdNFCEd1RQ-2B1x0tUaN8AUCEPoIVJ-2Fq4qmjTwQu25vwVXp4Pwp-2FKAWvJzuvR1J8p6iAKdXtaf4MzX-2FAXLMXgTijTUpQd4PnA-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro-2FjAk7exyPs1yRnVDNgp8AEne2vNp7VndFo-2BkX3pGg2At-dP_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPxGFaSFetxc0wQUaKCfC3WSnmuwKBnEeg3ysyeQytJ99hFoTvt40SMLweR4Yb8uPXIr-2BnZ-2B9Uqbtps8NLCTGF9onbsC-2FUyK4Hc204FB8wHHsa73YH6aFrmvIx6n0PI5iaIdj9NLJk0J5g3ZSgTrNxofjfxArCDL3nxurzf0qymZLYUMHbq570dBcbtKHGSSKghmBf7-2BaxZzt1mOy8RKkX2VYItzyi52iFFpo2CfNT-2FcA-3D-3D"
><img
src="https://www.gravatar.com/avatar/11111f45f49db81c283ca7d5c56058b7?size=240&default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_0.png"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro-2FjAk7exyPs1yRnVDNgp8AEne2vNp7VndFo-2BkX3pGg2A6g6C_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPxGFaSFetxc0wQUaKCfC3Wm-2B0HXZGcO6QH297mKnvnbDGo-2FFwfl-2FrJ096FQ1awS4NqFW509eY-2FKjX5WoCXZ7UGWldt0kB2o-2Fm0XLn1NZ9lpk-2FVz-2FFrIzIK4rQVFI7LX30yNn3WbmGqmbotiQVhq7KOzjYDyXUeGWFeDObdrZwb7AEY0Oq9Rr0gP3IAPkPEcGhaH28dAdGztpQyQ-2FRtNZB0Ia9yOXs2Hnm7XIJi250mug-3D-3D"
>이주희</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Hello, how can I change the color code of the color system?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfNHN5XUaT00CtOAvZMED4gSc25hHshaOlTZ278xRM-2FGmE2I6_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPxGFaSFetxc0wQUaKCfC3WEDlqfUqwQ-2FV2JjBhWVg2cG7VjxIdgYqqCi2V02vi6AIjQfF-2Fqe22y8u2ECViG-2FOJTVu293jKQt2SE8UYeY0p253m0Vm-2BYk2iMm-2F9rwrLZXeWMuWj7QOIB7fso-2BB-2F8ZCxYoVUQL5XmK1P1OE0PHWwrrCk1BsdvHp9ybD67UVK8UDMEWaItQgUGsuMu3qhUsq8-2BsiD6OMiaMudeqAnnswfrg-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
Answered on the community.
