### ISSUE TITLE
[question] Can I purchase an older version(5.11.1)?

### ISSUE THREAD

**Issue by schappeee** [mui/mui-design-kits#267]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I would like to use 5.11.1 instead of the latest version of MUI for my new project, because I would like to continue to use Tokens studio for managing Design Tokens.
Is it possible to repurchase an older version of MUI?

**Comment by adrianmanea** [comment]
Hello! Sure, please submit a support ticket. Include your order ID or email, and reference this thread mailto:figma@mui.com. We'll then send you the Tokens Studio version.

**Comment by schappeee** [comment]
Oh, sorry. I do not have a purchase ID as the product owner at the time purchased the MUI.
May I apply for the past version as a new purchase?

**Comment by adrianmanea** [comment]
Absolutely! As long as the order is valid (it hasn't been a year since the purchase), it is perfectly acceptable.

**Comment by oliviertassinari** [comment]
I'm closing this, the next step is to reach out on the support https://github.com/mui/mui-design-kits/discussions/84.
