### ISSUE TITLE
<Stepper> doesn't use <Step> 

### ISSUE THREAD

**Issue by chrisFinnet** [mui/mui-design-kits#268]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I recently purchased the MUI-licence for Figma. I wanted to use the stepper, but when I exposed the nested instances, I found out, that I couldn't "configure" the single steps. 
Then I found out, that the designed <Step>s that have different variants, don't seem to be used in the <Stepper>. Why is that? I changed one manually and everything worked fine. But I don't want to change everything myself.
Am I using it wrong?

Thanks for your help

### Your environment 🌎

MUI for Figma v5.15.0 - Material UI v5.14.12

**Comment by adrianmanea** [comment]
Hey Chris! The Stepper is meant to be detached since you cannot iterate a component. Simply drag & drop, detach the instance and add the content in each step.
