### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Heath Huffman

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#271]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DmEqm_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPiuInAVblucRLKO6DyC14VIz1m56Et7Hqps-2BRnel5mVIDZWL2xxtSzDksMC7rkyF14Fdr-2FeUzurIgEGmLDnGb-2F3EABVx7syxiFpVRTRRkCuvENn2PSgidM814peSsPr-2BimLgAWhB0YpqfC5Jf-2BglkI8iDHtN-2FLiXLQceA-2Fcrw7u-2BxM7ngtejhrb5a2Ss6-2FGd0LvOLPh7mDkv47Z7zWOxSzTZdi8Z5FH6jLoSiDOo3feQ-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro7HGa3k7oNwZQNXpGdYXK-2F4tXympFIgtOX6lnLdyYLRY4atS_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPiuInAVblucRLKO6DyC14VJ4ZfK0jl-2FuWgT128JF3MDKh7gwyJ2aPLSsu7NY4TfLzQtA2qjsrRNpzwyz1S0D7WdAaq5pbiPQbTU0agIhhza81fC2gOIPg2TuuwsQIoLpDMTmbNKKxI1FXPLkUWwxVhwDwhTh4JxPddsQ3mfIy3Mu0U6Vx5TfwcqGeKFvYI0ywwqA7fvsIjFVgL8OrqiHQsZXBT2DsHXlUn9KZ6Dewv-2BA-3D-3D"
><img
src="https://s3-alpha.figma.com/profile/a624c7d2-e4e0-4840-a5c8-32b0fe187f6b"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro7HGa3k7oNwZQNXpGdYXK-2F4tXympFIgtOX6lnLdyYLRYzIB__Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPiuInAVblucRLKO6DyC14VWBZBx5iV8K4oCnay8bkDv9M-2BNG0cwx1EH8WzPOhxAAuYNQfWO6Ou-2BDwRIlDI-2BXixvwyyUkDNr-2BamKHUmuKmaVNfCpN2cP2rS0acrSxkSOV3bTHyFWqV7F6Q2LnKfoODZl6OY6ANXuriXAOOgV1XNvh088oGDZsqgQQNi5vLxbzA77iMdMB2toN0CVg4wwfvXNZGt3udeJTVqGsG6iW886g-3D-3D"
>Heath Huffman</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
FYI, I found several questions here asking how to change the color system or change color variable values and why they don&#39;t show up in their Figma&#39;s like it does in the videos. I had the same problem and found this forum through searches where people asked this question, unfortunately nobody answered any of them :(. Well, I&#39;m here to answer that question for you. RESTART FIGMA. Thats all you have to do, and then the colors and variable will show. This has happened twice to me when I open up VARIABLES and its empty. I restart Figma, and all my variables are back. Hope this helps some other peeps out there!
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfFp3i-2BmgiwfVyUeFUvw5kDZpfgzONs7GbW0b2jG9tFfK5z4S_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPiuInAVblucRLKO6DyC14VeCPzlGXfbgnk7NOh7-2BepRebYmZBQBG1KpkHlBQBlfIrvDYwxCbogttCQwXp5Rfh87Un2wgRGqOqz5UQlwd7nQDDraJb6h6VEiAQdNhZgac7LluOp9gVWb-2F1U8vRTMy2b7tPIhwdaAtiSA66MXckc9Wj-2BwRYl3XrCHlnGBUNHSSgUEQb6QAuziYiz6mFUaSUUAdPJ5ypQ5XGnKDaPtqiDyw-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
Answered on Figma!
