### ISSUE TITLE
Typography in <TAB> & <TABS>

### ISSUE THREAD

**Issue by olivier-g74** [mui/mui-design-kits#272]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.

### Current behavior 😯

In the section <TABS> some text is defined as button/medium and other text is still as Roboto Medium Uppercase.
As we prefer to keep text in buttons and other components like Tabs or Header in Case As Typed (German language uses Uppercase for nouns and we need to retain this specificity), it would be great if all the text in <TAB> and <TABS> is following button/medium

### Expected behavior 🤔

<TAB> and <TABS> text follows closely the behaviour of button/medium

### Context 🔦

Write buttons and text tab not in Uppercase to follow German grammar and spelling

### Your environment 🌎

| Software            | Version               |
| ------------------- | --------------------- |
| Design file version | v5.15.0                |
| Design tool         | Figma |
| etc.                |                       |

**Comment by adrianmanea** [comment]
Hi Olivier, could you please clarify? Are you saying the style is incorrect in Figma, or are you suggesting we change the lowercase style of the tabs?

**Comment by olivier-g74** [comment]
Dear Adrian,
I tried to replicate my issue today, starting with a clean download of the design kit v5.15.0
In the page Navigation/Tabs I checked all the Tab and Tabs and they are all styled text as button/medium, so when I change the typography from Uppercase to As Typed it was modified across the board as expected.
Yesterday, I first replaced the standard font Roboto by Source Sans 3 in all Typography and then when I came to that Tab page only some had button/medium style and other where Source Sans 3 / font size 14 / semi bold.
So I am sorry for the ticket, it looks like I should have applied As typed to the button before changing the base font.

The design choice of Uppercase is totally valid in English, for other idioms where capitalization is meaningful or accents required, the possibility to have buttons and tabs in As Typed remains really a necessity.

I will close the ticket now.

All the best from Vienna,
Olivier

From: Adrian Stefan Manea ***@***.***>
Sent: Monday, 4 December 2023 11:27
To: mui/mui-design-kits ***@***.***>
Cc: Olivier Grascoeur-CIC ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [mui/mui-design-kits] Typography in <TAB> & <TABS> (Issue #272)

Hi Olivier, could you please clarify? Are you saying the style is incorrect in Figma, or are you suggesting we change the lowercase style of the tabs? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
    Report Suspicious  <https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!2S-qahVcoRExmY8xcOpvZXy6akmDc_cdPD9X_U9Ob7JgueWolB_OzoyZ6lPHCSIp6282pECPhJA3B_fnmdGkoiQVdTh_pIvxLFAn8vK_ekksnjq-$>   ‌
ZjQcmQRYFpfptBannerEnd

Hi Olivier, could you please clarify? Are you saying the style is incorrect in Figma, or are you suggesting we change the lowercase style of the tabs?
