### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by alireza a.d

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#273]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3De1Gk_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMmIoUDpt4-2FPvWKtQZfehyIeX1FVmEr454cKS1F7aKYzJ9tSlGU4MmqdcaXNzN0z6-2B-2FZ3NS7TrrEPcJdrrgPxsi1cx19cYlE-2BhGrLMWIZXbgHxUzOyPUF6KSwP-2B06Rmz7-2Bvm1dJoiKsI09mI1R0tSWbWr09dMcefOmdru4iA5Rde1ppe6oiD0tkWiafeyjNBQJgJA3tvdRlzvXEPdmikdCZ"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kroxmMz9XNfrI78EEYUIWo8AV8X6B2EcFORJD47Y-2BpPMbGncoP_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMmIoUDpt4-2FPvWKtQZfehyIKTojJs-2F0DU5dzN78OphQ32xFnK8oiNl3Hyw0zHUSPsX5a9N3F0KZQEyFV0onbM4EEbV3bBzFW1GyKCyto85nnTGQPYQNgs5ubVcMefzjwoY3HMfZgDNFKZVqD9eASUfOkPvaUsUEUn3ya11ybJfTgbmvMPjE5JvBpe4on5lETyZXstbWOna3QMJ2IuN98D4A"
><img
src="https://www.gravatar.com/avatar/205e59cacaeb8af14373297fbe0e94e7?size=240&default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_a_v2.png"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kroxmMz9XNfrI78EEYUIWo8AV8X6B2EcFORJD47Y-2BpPMbGbjo5_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMmIoUDpt4-2FPvWKtQZfehyItfiRisCnSpttzIqOyav8h5ZwJUNIDiZHX56pDODakuG3jlNsKr4wWFOlqvch9ih2ZUzszB2iEjP-2F37HsP4E7hEI1JWeTgslBMPPl8P6M0m9kApyDINnqJboa7ZPHGPaWdWyUR5uflfIgVIm2aB8iTF7889Y7f-2BIMRhT1T7X3jNVEf-2F-2FkaexbVhCLsVACaW5-2B"
>alireza a.d</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
hi How can I change all mui components for right to left languages?<br>This happens in typography, but all the elements need to be aligned
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfJ3wTnquoXw6NnP-2BTVZxOltfOUfiHKgzMBV-2FCxIEr0KaaBO6_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMmIoUDpt4-2FPvWKtQZfehyIuxh-2BeP5BUlqNMnFgDaduEkll-2FHQ8npe1iDextUi-2BJlR618r5sjUnbgHvG179UE7uYVLww7ocEdjJkbWlUX-2Fj6RN5qodvvmMiyHGwHZfxQpnuWnp0hWw9XjAWGvl2CZRJXis6LuPJDWKDhAXmpWTxOxa8lpOM92eoGokKu9mPVSgviB3v-2FIT6cnL6izs6NvML"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
Answered on community.
