### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Pulkit

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#275]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DoqZw_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPqGJgxEmLOgr3EakXpo5dUcV1QBSNVkfx-2FF1kuufe0-2BGnyz8pwVdCsjWNOxKKFbdx8JFORePRSU1JROhnIsg2q7LfaSfZx43ixEXCYENdHggz3Hu29k6q6ykIw0t-2FF1evCS2Y45nV9HyDG4SNcTq8FSar7vbF80FoCqWMBAGnf2BatcClv7dk4Nt415eB3Sqq-2BkS6jrvReTd08MGXIrZhYm5-2B3PQQA-2FKJx9laiGgVuog-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4krowNN0jUZoz3tIELsl7mx0jzM4HrM3VdzqssnDpK5TsahqmhV_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPqGJgxEmLOgr3EakXpo5dUSZ7jCnXmBjbOWwj5Bg-2BGF-2FX14djctGAPqtzOWT2D76t4j5VgR2ovgTcOycsJ5cA-2Bchp5RY99BYnJZcEVv6L-2BPQCdkhykJ3kATqcWVDMiuTOrH1OXPWRjqwxPEqyWt-2BR7byZlhnwOu494nqkv2bUFK0EzSvfSGV4HoH3ygWYFNBx7apk5vO0Cioj7yIcLda-2BzRq76mosKl-2FKlG1qObW7d-2Fg-3D-3D"
><img
src="https://www.gravatar.com/avatar/5ceeb30cf14a9b54fce873f0b25d546c?size=240&default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_p_v2.png"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4krowNN0jUZoz3tIELsl7mx0jzM4HrM3VdzqssnDpK5Tsah82Ms_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPqGJgxEmLOgr3EakXpo5dUgrEQgZ2Ha-2Fe0gB01VEawSiRvX4ez8zKc0rjXk3W0aAGovt-2BFX9A3h5n1SXERPPZ6-2FqQ-2F1vnKqpRWE0S3c1hXzG9uCkn85uemb7OT2flc0miVt1deQc4iWt5PrH1unwoZBYuNcF0d7hVLsHBKnO3Rr2XJDOROYPYar7EQ2XdKIm2dZyfkDXmp-2B4kx6Im7CUZpgvvOSKb0BkY4MhnPDa8BUg-3D-3D"
>Pulkit</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Are prebuilt-components free?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfA5fGo5DZWEF50CuwVlAVBKqZ8Cyxj6ocoiR58troK6nzVw6_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPqGJgxEmLOgr3EakXpo5dU41DT2yHDavE1Y-2BVEPV-2BcifWPCnlUEBM5uqMRB5NOu0AyS-2FGxKzvWNlTuRCtWpt060GOsVaQ3PMJSeGj6QWvCvAKyw9uMkkzyMp6Ud7Bl9KOMNcyNK3ii3SXlqpesWr5zbkBpwK8mKkKl-2F4JgcmST5ylIg9Xq64C0QVjelXCkPb6MlgfBwAitLDPwqTkQ2-2F2AlxaTveI3gpUhmKvNlifiwA-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
Answered on community.
