### ISSUE TITLE
Can I buy one licence for the UI kit for now and then increase it if and when we have more designers on the team? 

### ISSUE THREAD

**Issue by amyfourie** [mui/mui-design-kits#280]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

**Comment by adrianmanea** [comment]
Hi, yes, you can increase the number of licenses as your team expands!

**Comment by adrianmanea** [comment]
Customer hasn't responded back, I think we can safely close the issue.

**Comment by oliviertassinari** [comment]
@adrianmanea If you want to automate this auto-close behavior, you can use this label:

https://github.com/mui/mui-design-kits/blob/1e0816a8d063100c1ed13828933139e73ee8056d/.github/workflows/no-response.yml#L27

the GitHub action will automatically close and open the issue.

**Comment by adrianmanea** [comment]
That could be beneficial, but shouldn't we keep the issues open for newcomers who are looking for a missing feature?
