### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Clay, Megan

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#285]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DkYGA_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMEEcjDxHNSdPMYHogqgIShVtlLUwmscN-2FDJC9AWYeXI1HF2KxzfNa0ryjBDvkpjI2nZ2cNkPib92n2ElV8XHkYOWOF-2B2aCGCFFfrFpQgpzLrI3A0Ytt-2Bo9X-2FybALYyVM3ws6NVHd5-2FWSiDb4doTQ5oDlj7owRlrWkJXj73pfUaKdL-2FrS-2FLt6p9Nc0epxQV3xsd-2B3eG8xCzvRxilWMRqJeuYo3b9imZEGQwwqVUGt-2FOfg-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro0t2KyzDCcQRPlNp46oTglVK-2Bfmr56eSw-2Fpj4CeqO0e0D5-4_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMEEcjDxHNSdPMYHogqgIShqWbnrd7Bac1CWfMUn-2BDPd0J8-2BqxMGvUcVCKc-2FBpeii5OAMZTabT-2BO0nObrB7Nb-2BGO15ysfTcAuVkY20v7hJbWOkaFXMW2YfgNinWDHonWVRJxk4wyw-2B8G9tvBdeeIknfiJR4ISYGq6AwJJTEkm9vmuhAXIDBgZhtH37wdfQasgoFjiQurveXGM7fvkjee0IE2uc1Gh73Va4Rf-2Bw9sbzVww-3D-3D"
><img
src="https://www.gravatar.com/avatar/ea3b9480bdf661186f862614af0ee584?size=240&default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_c_v2.png"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro0t2KyzDCcQRPlNp46oTglVK-2Bfmr56eSw-2Fpj4CeqO0e06Dhi_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMEEcjDxHNSdPMYHogqgIShFqKsL5SUrCx-2BmNp6Q33B7GHyHUZLnP2KYVRBUUkaN5VSNbFP-2BZS2CQBoK-2BhstSUhEW7H85nKzyolSretyolGZlA5E2AT-2BujKVsgQ5DGdN5-2FBhj3nGfERhgNXflPu5dHDQ93owuOT5WFJmPaKg4etaRheYHHzwGZ6W5pRamyGDEcwk2p8dDydximCnJzq93-2F6hZuGJJZzRY-2BBx-2Bb8zwKxxA-3D-3D"
>Clay, Megan</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
zaldrian Is material 3 included in this library? If not, where can I find a library like this for Material 3?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfL6r1-2BdwAeIdGiQtgE9VyP7KJNQ5XXYudh3DHGkUBAaxJj0d_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMEEcjDxHNSdPMYHogqgIShYOpIEsZ0dw8pLi0XjqVGfccY6ESL4wtnzuhUzgp1pC-2BIp1ZfqdwWrKvvWrj-2FV18cXBZl5wzqAayplDu8-2FaDOiPhk8-2Bo-2BK0DusBHlK4tD-2BdDkQW5-2FFG7zUsjxr7v5tP67qDvQbGrmegzQar1Ef7kiWbQsgxibh-2BSA9g8gw544ZziBgMzsONB1929L3AUPLZIdSK8X0EVoni1OAmB9vyxgQQ-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
Answered on the community.
