### ISSUE TITLE
Naming custom colours in MUI for Figma

### ISSUE THREAD

**Issue by amyfourie** [mui/mui-design-kits#289]
### Duplicates

- [X] I have searched the existing issues

### The problem in depth

 I have worked out how I can change the colours using variables but is it possible to change the codes of the named colours or add my own? Ideally I would like to name the colours I apply as we already have a library of colours and I would like this new library to use the same language.

### Your environment

MUI for Figma v5.15.0

**Search keywords**:

**Comment by adrianmanea** [comment]
Hi, yes, we have an introduction video waiting to be confirmed: https://youtu.be/vpC-cMbjgpQ?feature=shared&t=130 — please review the colors section, it should answer your question.

**Comment by amyfourie** [comment]
Thank you! Huge help :)
