### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Gaurav

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#291]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DUXsv_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOXSdSN7zUbJxII4nJcMYTxTykRsXQikR66mvTeWWtho9jTwHBlFJ5XG-2FEukwRPIS25CbEO55zl-2FcotPOnZBRlJRHqcTRlQCQSggawGiRmC-2BvcqRrBcYyZmW00AIdYZCtM4iuLBB04eZsD6vLarQ99KbCj9tL1k6CCoYsyP2DOuLLhx7M-2BDsIM3QQRjEbLBdwclAB39HkFj62vI0uMXvsHflIWBR-2F8EY-2FA9FLrAIqQKaw-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro232ms9-2FCNGs78bFnJ6WmYNQExWV9Y6amLPQPbWsNkDgD28v_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOXSdSN7zUbJxII4nJcMYTx8ByAd-2BwurrcuEeBL6Pxwo2fqEPY8-2FUvQ6MGRft28pSzB-2FYR89Svk0I3jsEidr9lLQGsIvPRbS-2FLAV77iGJeJxpj3rLQw9xLR-2FrEQNAqKumxQttGsWeshMut5drIXEogJExNnMtNR7nFWMQxQ9D5TJ1bqzH8B9jTwwy78dRMjjr5Gm1EFlUncNR5iI3Sx57B6lXXLhZNnwerXkSUpOCNBgQ-3D-3D"
><img
src="https://www.gravatar.com/avatar/6ae5012c10453736077ad92f91df54fe?size=240&default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_g_v2.png"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro232ms9-2FCNGs78bFnJ6WmYNQExWV9Y6amLPQPbWsNkDgRDI9_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOXSdSN7zUbJxII4nJcMYTxXvOqKzdnsgEYaUW4RQYhlvnSOXO7j6iKoI2ameKUBKC3qTEz37gZQXLWiNhHKgsNvrzIwsTkxfKyAoi-2FLJYeIkRaIy2-2Fit2zEb3-2Fp3tTYNKmdIGbxn8Z8SWFTTR0L9vnYo-2Be0G1O1Iz9CnpeBczFb4dV741T0HRWzg-2B2aoucghTXWdzIdjl4c9zAgj3XRlH-2BD0d3YNpFm7gdEocbFFgIBw-3D-3D"
>Gaurav</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Hey guys how do we use this kits and implement it on design? Can anyone guide me ?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfH8gq1ajZCsMd6R165sXBvlB2S-2BZbXFra5S3AGZfDWMkjtgE_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOXSdSN7zUbJxII4nJcMYTxMpm6ZuttDHuGHojZ5EQC-2Blm3gkBxnovu8H60LhbXwP3EUrikpJ6Di5g5ATamg6WpWqF0z81EVobdOTINyGgAku-2FizmpGDbhEg1ulDuBo64mLTnXN6dtsEg4jARfx8ExQfdEYwfNwY2ntAOu3clmFNMO-2FRrDehKBRNmNZCnOVfpPMk3LcL8I8iXjUp-2B4gZ-2BJNhjwoTG-2BRekayrLPDwUxa4A-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
Answered!
