### ISSUE TITLE
[question]   material-ui has no InputBase component

### ISSUE THREAD

**Issue by faner11** [mui/mui-design-kits#292]
### The problem in depth

In some scenarios, we need to use InputBase, but we don't have this component not provided on Figma, what should I do in this case?

### Your environment

v5.14.0

**Search keywords**:

**Comment by adrianmanea** [comment]
Hi, you're correct, we don't have these components separately. InputBase is unstyled, which can lead to confusion about how to present these components. My suggestion is to duplicate one of the <TextField> variants, like Outlined, and start customizing it. Afterward, a developer can take over and apply them.

**Comment by oliviertassinari** [comment]
Agree, there can't be an InputBase in Figma sense, it's a component for engineers to start a new input variant.
