### ISSUE TITLE
[figma] Add the new components to Joy UI

### ISSUE THREAD

**Issue by atillaaliyev** [mui/mui-design-kits#293]
### Duplicates

- [X] I have searched the existing issues

### The problem in depth

Hi, 
We bought figma for mui-joy because of re-design components. But the figma  was designed beta-9 version but current version of mui-joy is beta-23 so there are some missing components like this Stepper, Snackbar etc.

Do you have any plan about these?

**Search keywords**:

**Comment by adrianmanea** [comment]
Hi! Indeed, the Joy developers are advancing rapidly these days - it's quite the pace to keep up with! We're committed to integrating the missing components by the end of Q1 2024.

**Comment by atillaaliyev** [comment]
Thank you,
