### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Andi Förster

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#296]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DdYME_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOk-2FP85OBetGno7l4z4VcEuHZVEB0cAalxSg0KiAwSkbkz5-2BFJ1q2f3ZlNDiqd41qNNCK2Lh0v-2BO44Ez0FDxdSOQVzKe-2BXICF5eG5ggp7jKB74dTRbpkYZmdFtAQxawBRx9nEQ8-2B6xDHUcnBeYMGxondYfzJCYj-2BF9eziBGj6HpODqKLWnS5UqVJtIys6W8FZKPHdkft-2FClGATdzggKeKGH36xkcrD-2B-2BSYbQYmpWNrh2g-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kroxmMz9XNfrI78EEYUIWo8AXdKubTecNQU2-2Bim-2FhLFm8vIfGU_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOk-2FP85OBetGno7l4z4VcEuecUKr4PiU2SBRYDT3DndGgkFtTKmczR0CXX8KYASIihDnCLSfOM2H4CoJKIlmB5ojn8na6XmLesgxpXuNG7vp-2FXNKCaJuTSyUn-2BnbLHe2GAT-2BrqAHH1AHXS43D2fduNmXnzMvknaCIbkUp7VfR3wl78wOGk0GuhGJfcapIaZ9mWvXxGOzUeMHb-2FUGNLnGjY5PerjUIqKy7-2FGSyZ90sVXzQ-3D-3D"
><img
src="https://s3-alpha.figma.com/profile/deadf898-2f0e-44a3-9f0d-69264799e854"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kroxmMz9XNfrI78EEYUIWo8AXdKubTecNQU2-2Bim-2FhLFm8vwEpy_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOk-2FP85OBetGno7l4z4VcEu7LTQ8SrHENJN11wQeLXdRpMDnvB7aDuvrcS9evpMsNpMYYztG8XevrdeNeJYRh1IYllrtPOfZUopxuI1rP-2Bz7t4hmkAGqk-2BgusZtr98BET2zIOmlp2gBTDbkJkTfF27oBrF4n3e9M8TWcMaCwMOHO9ZvEIYa0B8rK2n30UZhi20gTPxnpgilyxjQrEj4F5-2FboPnEa0H-2FBNMYTVIaYPLF-2Bg-3D-3D"
>Andi Förster</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Hi zaldrian! Is there a reason why the type scale only supports &quot;Desktop&quot; &#47; one breakpoint? I&#39;m on v5.4, did that change in any later version? Couldn&#39;t find anything in the release notes.. Thanks for all the effort 🙏🏼
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfItVESDvJsbpzh4HasZ975-2Bn1ri8KL2wOarrTSzy6UFoTyUm_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOk-2FP85OBetGno7l4z4VcEuVVDJuNYEuJqlHHXDXodDk1qYnDcEw3uAP2AlnPiXinGDruuLD26aKx56qEok6t15lWdh3gLIPGFCqIA65MeCYS1nB4DtfRDUexQZLZB4jVnWPKwlbslMmhcdrFrqnkfuSD06fq8JCq6oWv-2FA5P-2BrWSyUOOH5JXu1UEJxPvCoOgpzrk4XOUFLG-2BaQXujJXyrPrls5WIxZ2zQ3T0zEoX9gmQ-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
The author may have deleted the comment as I can no longer find it.
