### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Michael Martinjuk

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#297]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DjO4E_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmO6SI5LwsEpiOdRCSwyJpJNdz0NZ-2BiKzCniW20VTaXGYJic-2FO-2BFCl0-2FNPaYFhg0p1fFr5elUH-2FMTgr9ZohFMBCzkZ7Tp9JTkRSnUa5x4NQIe29Erk57kFYeeI3PvQUJvzeDp2-2FtmWLY2fZ6DyU9Blhc4duE5I-2FGwNopVJcgtyDugVLzeVU9TDeBmA6TFYv6ZC5GoE4Uoim5-2B8vnekkYwRVoaAiyus1oh41YLZw1m7hI7A-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro0OhfCaNq6tB1gTEb5CrKQitdfgXhvul3VUps-2B5S-2F-2Fu8xixY_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmO6SI5LwsEpiOdRCSwyJpJNwFVIwKDs76BcZpo5bWSAaIWxOfG2IgU4qjEBoCnjLnW-2FegwVWhuWcCpOCO0TFr1Xj36auHqqKZwRdrDNFp19vTnVzthWwthrM366RdWATJfq4TauNYNJMDtY6-2BRvLLLXYxAYRtDxQO5LVOLQT09maYhG5Z6Tu921zgOQOKggcdojG27svIuCzMqVrLhqjUpufc4Xu6SKKjJSlg91CHD3tA-3D-3D"
><img
src="https://www.gravatar.com/avatar/e0c3b9d734c3d669971d770b02d2deee?size=240&default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_m_v2.png"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro0OhfCaNq6tB1gTEb5CrKQitdfgXhvul3VUps-2B5S-2F-2Fu8fPWl_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmO6SI5LwsEpiOdRCSwyJpJNCgnzqUMK-2FxJaEY7PZ34b3wjppkZYEQENQE-2B3U4PLSRj-2FEK-2BtzOm-2B8rNqPBMrUNdWm-2BHX2wrvwjoAbUmo94xHgeLNKDO2L-2FO6aToSAiLSYSa3fW3R0lzdklAe29YJYtZDHVu3vsfimMKKfrX9-2Bm0bABzN8n7QC-2F-2FKjVhGUq3WJ6QDF2EvHJvkBF62Qv5ewDB4Mo5nzC6111QGuRlx5SJgHA-3D-3D"
>Michael Martinjuk</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Hey Mui folks, great library, on the paid version of the MUI for Figma v5.15.0 - Material UI v5.14.12 file, checkout the variable name for the Switch component, currently says &quot;knowFillDisabled&quot; presume it should read &quot;knobFillDisabled&quot;
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfOBBz6HNFilohoLHJASuqRzq-2BPeTPY67uYp60g3E46ZO_Tdt_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmO6SI5LwsEpiOdRCSwyJpJNqzO4QUU2M1y2XOEZWAh0I3Pcga6HzPWcbTkzH3bmO2E-2FteOHPbLo7ICzoMkW8cMF-2BpQfkH0Y67d0AnKNXf4yOWLMepo7F4nDJhLodeGxeZWS2MkXrL4dCQwNy-2BW49u6hDDRdmUMMkdD8ENSfIkwNI8N1kdTYdawZSMXwd06xqT0yAmAyrS4eGGWH17DKCYXZo3rdl-2F8FSr97SPLsgq-2ByAA-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
Answered on community channel.
