### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by FM

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#298]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DyAFt_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOL8UuiJ6lZIw3vYEx56tktwzamVeyVI03sbWR-2BtF9c3HSwQN34Rf6-2FVUi3YSXDLO-2F4zbmB1IwcKXGfRv-2FboTr0SoeoZmYa-2BrHLe1XZNr-2BdG6iYjZHooMtx7OBbSHC-2F5xpU5PMOFFm3TI-2FgLWzSA0FxebDxMKNdLHx1vhBYHDxJ5xHAIawGcpVRxgbQatSVliXEzStf6t3bE6OaQy3-2B5yXPLSUGEOAeyu5MQGypYyYA5Q-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro-2BXUC7deE-2BxmYfwd9k7O0ijtnCXVDu41fGpzT-2B-2FyXnliNa0m_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOL8UuiJ6lZIw3vYEx56tktG3pm5zFiPxm7hSzgmG1t9GvPzPBFDnIwPOgpAJkaamDMV5yzMSZ-2BxSuh2Mt7J5jZLS2LHh9V7N8Rcgx3LOM-2B-2Fg2XgIfwhr5NrN0KKmJrg19OnGqbDkpClmGaCFfO0tcGPV0FmbGdjsXgiqnV0UaM55aOWhPxWxkRVA4LLFiPla-2BwLCt4LWIdyGnjCnQwVCSfn1GBzTQyX70g0t-2FT-2FxWQfQ-3D-3D"
><img
src="https://www.gravatar.com/avatar/f3240681a5e11575be64461593b0ebb1?size=240&default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_f_v2.png"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro-2BXUC7deE-2BxmYfwd9k7O0ijtnCXVDu41fGpzT-2B-2FyXnlidXQt_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOL8UuiJ6lZIw3vYEx56tkt8jdFbro5XENlbLPJ-2B-2BWCePM-2BrCyKPdtgV1bh-2Blpq4UqQgFUigqTw1r6me0HQT-2BR7aCLi1RPTmladx1KhRyuGcs6ctwLKKu18PKdVOSn89VkVuEMjS9C7m1h08yVBwkDKZkJKmlpHR8GEWbrlDFCFK-2BNv1gzKxhuJzeGzJwVuZlXpoVc8NsNCAbMSPSCSdWx3YPnV3GT8BLrlvz7jPi-2Fb-2Fw-3D-3D"
>FM</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Hello everybody,<br>It seems that the Text Fields in the Components section don&#39;t have the &quot;Outlined&quot; variant but the ones in the Overview section do. Is that normal ? (Sorry if it&#39;s a dumb question, I&#39;m new in figma).<br>Thank you very much for this great ressource.
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfIEpyawwjNCQ-2BjcS-2F8Dj81qI7qxoNMwrEdxO-2BncXqdlyYO4K_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOL8UuiJ6lZIw3vYEx56tktRBcUGXkn1JEgcEM9lvIwuVX2Z7r7DcascwWmo8sklQTs5u7IpwMXc0Re8KUDHmWngUGeIhOEszVnC8XVaiu6obh7MNtUuyvjlKn9EDoO5SQWdoO67O6i4JpzaTt8EYO-2BreJ3rdhLmGZfoWbYSZPHvVgkGumWKqxEOSiu-2BqHAtYDWCmRxZMXnWMcHdWpa-2B6S-2Fq2vSv4XvM-2BHGr1au-2BVb6mw-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
Answered on community!
