### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Ioana

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#299]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DmyxJ_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmNFtajyI-2BIAAE00a4YIUJdpqoqRt63z8Ez3bMBHLd-2BLlSlplSSU917Yd2FfnRC2SR23vYfSP-2FPEM5nXXf5v7565zxmsKByjjHn0sxJjy8UDS6EtEsbL36FHn4ZyLns1ulkj92Qem0ZWyNXpkgwSOGKJBDsqKHZOHr1CBAkpNh82Y31n3gmcoaAc4WE-2BXsWYUW-2BJbSRD96wkf6BW-2BfKvuKkEIyTMSa9vI457vzVjT5B-2BYw-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro8cbwHF0-2FaSsTSUCNMfdXLVrP53yki1sgrEx1H3RqdjE6LcR_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmNFtajyI-2BIAAE00a4YIUJdpVbyeE1HZlYjd8QGV5NFwNbLnDIgaE4lOR2-2FmY3k7suqDAsBnLW9cmdB9a-2FypJx17jULIiJJb2jRsg7yCJUgebsJtJ48o9gyusogzoNZRdgpDozn5NVrLZAHQGiFf0pIk1VQ-2BBAfuHnqvP6RUA9UNXKQvhtljhdyS1hRILBxCA0ZNF1aRj79t535ukk6oa2h7OsA-2BlX-2B8Ek60NEvS4g7Igg-3D-3D"
><img
src="https://s3-alpha.figma.com/profile/a0cc74bc-8c90-4e5f-90f6-a0dca5b31c7d"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro8cbwHF0-2FaSsTSUCNMfdXLVrP53yki1sgrEx1H3RqdjESr5S_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmNFtajyI-2BIAAE00a4YIUJdpdp-2Flebh8P5vLj2tvm7D3G7M3NEhRqDyWR7CyhR6CNvUzlwJkPhb-2F7H-2FDz9vFJ69omcgW7xkn1gqFU-2BZoC-2Bdqhb1h7Gu9iZpsmR-2B8451lLL3qn-2Bq-2F31VEtIIHjE1EgCJf1V-2FEHhRlvHOSM9xSUvjJ3r19HbmbW7-2FS8XLwpJJ2TiMCF1kCRDV-2F4P8to-2FUzIk0J7wXLoNKRWdWZ4U1h8zTnfw-3D-3D"
>Ioana</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Hello! Is there any chance I could buy the right to edit the full version of the MUI v5.15.0?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfJeglFfIUr-2FUnpekItF9YPRiWA1gTvxg46XdC80YLNe0PvoA_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmNFtajyI-2BIAAE00a4YIUJdpGIh2ug8uzPfYgIzBETalgL-2Fadea4QbhwNnCJmGo95b5HgjzNLT9P-2Fq0-2Fab9su-2F4SjWtP5zlobuiZoYfTE54o5WAgajGqtq64SikEvkaPRWRF6PEKDNpaM4Etkntg2juPlR8kV5OHpuG-2Blsb46TTiQcnCqykaMQCo3QNy48F8Qf3RBOyKutWqsq04-2BCv8ypyK-2BFK82mAxiqHLQDiQ-2BXXI3Q-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
Answered to community!
