### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by anne.pereira Sterling

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#300]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DuViO_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPWHm0A2DUy-2F7QjU5c43MRF8ykleaEy0vlVqMgVLjPsCH-2FW9jd8vyj8LW-2B-2BwmJBhnea5lrVBXFDUh7spZ7UQuX1FhjwekAgay1oxzPbYlcQF0gF9avSKO5GZX4aGaFQdvee44JXfytWVh13tmjnpK7OWKgjHU3PT6y5uk21xhv0j2a1onVgL-2BpBywHMKUCDe8QRBfnj-2FScrZ-2FiI7FARGrHZ0z-2BRvRyVpa3W5qjT7QoCHQ-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kroxmMz9XNfrI78EEYUIWo8AWoVQfUJAlcRD66-2BUJTkGIY6Oy1_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPWHm0A2DUy-2F7QjU5c43MRFsaqq3XnEFD-2By30fZVYc01Ke1ZGTmR-2Bu5wWbm5bRGMlb7TOFH86lnE8rw-2BgVo-2BSmxQiZbxgKi-2B-2F4P57JTaRtpVb8ck9ID-2B5sGK2KPK3lRrYg8JCCTgw6JanwCdTKE9KHWi1LNYyB34l8x4Hodov81i4VAQN1tVGMU-2F-2BsGWFxbw7SyxOeqO3Dd7Nl-2FzH3uqfPRZqgT-2BfqhMPWa6z-2FRIpF3nw-3D-3D"
><img
src="https://www.gravatar.com/avatar/10d57094f28cbfcbc86fe3b84193a1c9?size=240&default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_a_v2.png"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kroxmMz9XNfrI78EEYUIWo8AWoVQfUJAlcRD66-2BUJTkGIYlyuH_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPWHm0A2DUy-2F7QjU5c43MRFBJXh6DAoOFWzU4Wftc9YepKgGAODPaPKwp0YAM2T8xhJNYMVcf8yVf6wxS4eAThY9Tu83mU9I-2BYagkl0PLsyJIwPWJBhPoyFO8w178v0csFIAfqUIv76k3DSx-2FSNQQHaFIsSgf7iSdDqZ-2B4Nge25wr3ANiP15Hk9Qn5N4VsWsIQWDHZY1l2kS1LNaCRWY5I6rX7mg-2B-2BTrksGAf4kxHTaiA-3D-3D"
>anne.pereira Sterling</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Hello, does anyone know where I can find MUI X Chart components?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfL5kgZaPKjbR-2FzulvRweQJjrwGvUGV-2F7Jxl0Hbecd7eXJEyp_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPWHm0A2DUy-2F7QjU5c43MRFkZQXxF6Gr5zbt4699NUeoSEPWqdZ9y-2BlMeddWVtRsaO9s1AAV63-2FMOMLwCMPmoMmePACLcAjGQfvzl0ypxGopBe70947jqaMRJQ0igxsairy0ZTnfyftTu-2F17Jv2eqM-2FD264nlrwgI9Vt9wQ4k6GW-2FRXn-2FqgwDHQYBfgErEm3imx1YszjKWOXknLdYkUgqbfij0InPZjjVnKYDfqxIHRag-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by oliviertassinari** [comment]
Answered 

![Screenshot 2024-02-08 at 02 12 25](https://github.com/mui/mui-design-kits/assets/3165635/f0098101-fe50-4f92-ac44-8d8a2e558458)
