### ISSUE TITLE
[question] What's the best to turn content to RTL on Figma?

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#303]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DvhEN_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMZw4OTjOATh0nf-2BU-2FpXa2mtNdOh3cx6XI1Y5KMvfOGLqcRNZRUz6xWq63-2BKvkYQYPp-2B0jaDwJiv51hwt-2BjXw12R7W5eWAxcN8nTKjqPYnQMZCe2LmyhFCGyOPOzjlQgS1W1ArON-2FUpFxLxbOaNXyODFz8sDQ8-2FVC9FhZyPhBdHEPc-2BlewO9tLRLmm4ej2-2B5oWoPK8A8vmqtJ6I1I0nqjH6122DpZ31iRF1GuUL588nBg-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4iyX5E47Hlu1FmU5YJbMMQx2XGsktTAPoiTubODDd5RTZj5_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMZw4OTjOATh0nf-2BU-2FpXa2m8sVpeDszQX4o-2BEIuIPtflBG5TxN6NgaLSkqBslGiFgbhgXrgsXjkqSMLNjdBhYVb8PuIxyPNhhCrMvUTIx-2B5Kmz7VBam-2BzFOHRCUJ4aZpsxvBN1t6z47bAYN1kBw49PzsgwUEsjGY90xu-2BEZdf1wZYwUoPwKgZCU27D-2FsQAAjrQdjJCBqO-2B5GZiuqlJto1PF0JAPDBUCH7oiMUnstuUMzw-3D-3D"
><img
src="https://www.gravatar.com/avatar/c4b6bd7b77840f897862bfe677b60f07?size=240&default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_l_v2.png"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4iyX5E47Hlu1FmU5YJbMMQx2XGsktTAPoiTubODDd5RSq5t_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMZw4OTjOATh0nf-2BU-2FpXa2me6mqpUraxQdjo89sWQZ2JMDYLk2fqiH330jg4IubJYHtiLyNZTTwOL-2BXrnU-2BNKqD23ekzA6JQpzTxC8mE8cTO1DSB2evTYgOp0gcGLA4E4uEMOifhmn-2FBw6RoZT22AaVsudOezCpsVe7-2BSx8XknBCc4Uz9aqdYXzO4dqWTCJiqGa6DjBrV-2FR59VI2ABD0-2FIUTjFkEyxD5NLExQVhsO3Fww-3D-3D"
>Lifeweb UI Team</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
hi, what is the best way to RTL figma file for persian language?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfBweZQj4aq78hyexpm4M8gBAeBKFy5JhTDC9h2uSfmJLawKs_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMZw4OTjOATh0nf-2BU-2FpXa2mImo8lM46qJYRrMplwffAaAbxgUClrjN1oYuLXzzeLqtvLOA-2BeKy8chw2LMD3jygcpj4CCTiVptGB0JsSdh-2F6PnRgIROgc-2BylmP5xoolu6d0xEbqS6rWl85qUk8Srb25PZtL2GX6Wto7i5Dz7uNsLcA0k6OKAl77zTLQnj-2FYnlaCADZAALit1grAd-2BfmKSYF7POWMFqLr5YYzonU5cVGisg-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
Answered on community:
>Hi [@lifewebuiteam](https://www.figma.com/@lifewebuiteam) unfortunately I'm more aware of any third-party solutions. Maybe the community knows something?

A plugin for this would be a huge time saver.
