### ISSUE TITLE
[material-ui] Blue 700 value on Figma library doesn't match with node_module value

### ISSUE THREAD

**Issue by FelipeDeCastro** [mui/mui-design-kits#308]
### Steps to reproduce

Link to live example:
https://github.com/mui/mui-design-kits/releases/tag/v5.15.0

Steps:
1. Open the Figma library file
2. Go to local variables > material colors
3. You will see that the variable value doesn't match with the value in node_module

### Current behavior

On Figma:
blue/700 = #0057B2

### Expected behavior

On node_module:
blue/700 = #1976d2

### Your environment

| Software            | Version               |
| ------------------- | --------------------- |
| Design file version | v5.15.0                |
| Design tool         | Figma |
| etc.                |                       |

**Search keywords**: figma

**Comment by oliviertassinari** [comment]
Joy UI in its current look & feel is being discontinued, we will resurrect it but we a lot more focus on it.
