### ISSUE TITLE
[figma] Date Pickers still using the v4

### ISSUE THREAD

**Issue by adrianmanea** [mui/mui-design-kits#31]
### Expections
![image](https://user-images.githubusercontent.com/5917515/139284971-9e6b7685-1d21-4824-add0-139b612cc089.png)

https://mui.com/components/date-picker/
https://material.io/components/date-pickers#mobile-pickers

### Reality
![image](https://user-images.githubusercontent.com/5917515/139284652-29906d7d-cac6-456f-93c7-d639f1a94042.png)

## Your Environment 🌎
v5.0.0

**Comment by oliviertassinari** [comment]
@adrianmanea We are resuming the work on the date picker, @flaviendelangle is leading this effort. Some of the problems we might work on:

1. Match the Material Design spec
2. Make the date picker dense on desktop
3. Stabilize the date range picker (that we don't cover in Figma)
4. Introduce a time picker for desktop  

We will let you know once the design of the component stabilizes.
