### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Casper Eisma

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#310]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DDvwm_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPiKvYd67iyEG6XuBtNoi-2BMNSGQPKUdgCCUCBX-2B7EBrWzykBt5NOCeNbR0zVNgwVFgq4anNxWcglPU1uZx3SNhF6BlUMmz2YoxYie7nPPwdLcjuLvkx2YV7y9gkB67JmbFUGn7NkilxWOmyYeyjegTmJ9ChEwBEAgz6l0bTDZgRgREWgnTJCYGCsTXzPskLb2yPZl4pU5N20JrBpxqdT-2FmC6Khaf5Do-2FnEMm0klrvjT2g-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro0t2KyzDCcQRPlNp46oTglWuPEiensdEZBX0MJTxozaRuyJ7_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPiKvYd67iyEG6XuBtNoi-2BM6mgnoPaY5Wqm-2BUcBDau2DHd1HtGg3lA20duXYddUgWaYvqQRmwA6NvZxX-2BIXmKIn4-2FV9rU9Hm8jqXOUO3bLbG2ODRgzZyFY8gH8xZ-2B3VU-2B1xDT-2BpJXUyx34RRJChEXmszkKxSjoPVn-2BJpx3Cki15ySk0HGf2K8Y3JOFKZrns5p61KZiP2fCckLTKMBw25ai4U5uPfRk6ehkUbnDJovwk1A-3D-3D"
><img
src="https://s3-alpha.figma.com/profile/1433f6e0-3aa6-4798-9fe9-b0019db108dd"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro0t2KyzDCcQRPlNp46oTglWuPEiensdEZBX0MJTxozaRAd4p_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPiKvYd67iyEG6XuBtNoi-2BMt8wxptlEsSBJ3uhfZNYPBQdFVkFHKogy7gV7hsPmgVX5mM9Nufm03TN-2FCgyewEh14YOeHVHKKiY3tf89SQR5eyLYVpE3D-2BKRiXq9L1kMPhhY9GQLI8wbIUSwqKnJEI9s8FOoPRimSPq51Je3OJblJzVt-2BDZepNMqo-2BG-2F79Jl33MziFvN8riwd1afqxvnf4wQ12q1tYMpgMDea0n3B11B-2FQ-3D-3D"
>Casper Eisma</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Hi goadrian the video was great and was exactly what I was looking for. So this allows me to support up to 4 themes&#47;brands, each with a dark and light mode. Thanks and kudos to Masha who made the video.
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfPkmL2JJYCOU5pWximbXTuk1mATIbcNSD4NuAvJ-2BS6qS6pUG_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmPiKvYd67iyEG6XuBtNoi-2BM98-2BhcB4PopTKFNTpfWwE4mlMiuLuitmWlKN34Fc-2FuV7J671KnN9gcpToJqX4nWFU6oj4IMRRc25MfNzx-2BLxG-2F1CwtDnkecBl-2BdhAYKergkVtLKBZXQqC9fJ199HnI5-2B3eStxRG-2FS5UkBRzIbZ3KhZCe882kcFvRtB2WlVsH5PrKS8EGqv6uAZVDxiLaekvHA-2B-2BaKXQnH2XHW0nUfQCLVag-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
Answered on the community

> awesome, we were actually looking for a solution for this ourselves. Thanks for confirming!
