### ISSUE TITLE
[question] List Item: How to change the margin from icon to text in figma?

### ISSUE THREAD

**Issue by koray44** [mui/mui-design-kits#311]
### The problem in depth

Hi, I have a question about the list item. I would like to reduce the distance between the icon and the text, but I don't see any options. The autolayout is strangely not customizable. How can I edit the component?

<img width="2560" alt="image" src="https://github.com/mui/mui-design-kits/assets/135217179/e4ea55b8-2264-4c35-afad-7261960fa8d3">

### Your environment

v5.16.0

**Search keywords**: list-item

**Comment by adrianmanea** [comment]
Hi. To reduce the width of the Icon container, simply select the "Left Content" container and reduce the min-width of it from the right pane.
<img width="293" alt="image" src="https://github.com/mui/mui-design-kits/assets/5917515/ef78776a-ab59-4a2b-b86c-268e1c7592a0">

<img width="231" alt="image" src="https://github.com/mui/mui-design-kits/assets/5917515/5bb26bae-5fcf-435f-87e7-4aaf4d470660">

**Comment by adrianmanea** [comment]
Sounds great!
