### ISSUE TITLE
[material-ui] The color variable for orange 900 does not match the hex code defined in Material Colors

### ISSUE THREAD

**Issue by ivanbachev** [mui/mui-design-kits#312]
### Steps to reproduce

Link to live example:

Steps:
1.
2.
3.

### Current behavior

The Figma variable for the color orange 900 does not match the hex code defined in Material Colors. 

### Expected behavior

It should be set to #E65100 according to the table on this page:
https://m2.material.io/design/color/the-color-system.html#tools-for-picking-colors

Instead in the Figma UI kit it is set to #EF6C00, which is the same value used for orange 800.

### Your environment

| Software            | Version               |
| ------------------- | --------------------- |
| Design file version | v5.?.?                |
| Design tool         | Figma/Adobe XD/Sketch |
| etc.                |                       |

**Search keywords**: color, variable, orange, material, contrast

**Comment by adrianmanea** [comment]
Thank you for reporting this, you are correct. We need to double check all colors!
