### ISSUE TITLE
When using components from the imported MUI library it feels like the component controls are not working

### ISSUE THREAD

**Issue by TMITS74400** [mui/mui-design-kits#313]
### The problem in depth

I just bought the MUI license and want to use it for my work.

1. I downloaded the figma files to import
2. Published the library
3. imported the library into the file in which i would like to use the components
4. dragged an instance of a button into the page
5. when trying to change the size using the drop down it has no effect and the drop down remains the same.

It feels like the components are locked somehow.

I'm assuming this is a very basic thing that I'm doing wrong. Any help appreciate.

**Search keywords**: imported component controls not working

**Comment by adrianmanea** [comment]
Hi there, I assume you are referring to the community file. To access the source components you require the full version.

**Comment by adrianmanea** [comment]
Hi, attaching a quick video on how to add a five items variant

https://github.com/mui/mui-design-kits/assets/5917515/611a87fc-528f-41f6-a0b1-7434c6f3b754

To duplicate, I'm using CTRL/CMD + D

**Comment by TMITS74400** [comment]
@adrianmanea Thank you very much for this. I didn't realise I needed to update the main library file.
Much appreciated.
