### ISSUE TITLE
[question] About the Chip icon size on the Joy UI kit

### ISSUE THREAD

**Issue by sippenae** [mui/mui-design-kits#315]
### The problem in depth

Hi there, new to github so please bear with me. 
UX designer trying to restyle joy ui for our product, but running into issues with chip icons. Looks like the lead icon is sized correctly for 1 chip (success/leading icon) but is oversized for every other instance. I can't seem to edit the scale of the icons anywhere. and all of the widths/heights are set matching the correct instance. Please let me know if this is a bug, or if there's something I can do. TYIA

![Screenshot 2024-03-04 at 1 50 52 PM](https://github.com/mui/mui-design-kits/assets/162203417/7e6ad922-2b8c-4ab2-a85f-4e1f280d0231)
![Screenshot 2024-03-04 at 1 53 49 PM](https://github.com/mui/mui-design-kits/assets/162203417/b2fecc65-a55a-40d7-b43d-9bd44bd9bc4c)
![Screenshot 2024-03-04 at 1 56 40 PM](https://github.com/mui/mui-design-kits/assets/162203417/fcbcc45b-dab3-4b1b-b24e-a33410f8b74d)

**Search keywords**: chip, icon, sizing, autolayout

**Comment by adrianmanea** [comment]
So, we're having a bit of trouble finding the component causing the icon size mix-up. All icons should have the same sizes as per the Icon component. I think you are right, we should swap out all those icons in the Chip with the ones that come in those pre-defined sizes from the Icon component.

<img width="960" alt="image" src="https://github.com/mui/mui-design-kits/assets/5917515/cef8c728-dd65-4010-bc22-89f9ec8b98eb">
