### ISSUE TITLE
[material-ui] Missing Image Lists component from the UI kit

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#316]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfK7-2Bc-2FvyTtgXEWluQ-2B0JSYy9UVc7R80pVwZOI5JuN0p13g51hdAPvAl-2F0vrualIBcJygMBzwyKIORfxi0JaeLN0-3DWpJx_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP3rNbo5encOsbkYGUCwIZBFGBSdjvhnAexxo2lnw-2BYcG2Oqhrfy8Ztu4UhNsSmTAXf7dOKqGU5QeiO5omlzikqSZ1Xylo4Lb2h-2B2P-2F21buYwL8MQN9-2Bg0j5I2kk101U3txIZHTK9sVtbYaYD1ZLb1A-2BZwxj9BXhq2IF0Ji54n4tqqMjehE6QXlt9jGb2n7qoc2o3jHFckmEnxGoeH5FD3UI"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfLzVDp9QHi4iw78NcZJEram1RDqXUMqsMtWzaO-2FZqA1DIrtb_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP3rNbo5encOsbkYGUCwIZBFJKCVdOMIlNai4HIKxqa73DChDnB0eznKcBepx8DJrYtdaBnAubHEWAhCuUMSR7xBS9Zr6vDaTIEZ2YQp-2FWN3lPvFTummc90xjveIYxNS1P7-2F9qNv0itkIZBFAuUz9ONqk2OlfCCLb5wSoNndwZqwCXnE8R-2BXjXDxAfK5X-2F2TzPPoIwAVf5vjK2MR4B0S31tP"
><img
src="https://s3-alpha.figma.com/profile/0be372f1-026a-483b-961d-7a4638fcaf70"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfLzVDp9QHi4iw78NcZJEram1RDqXUMqsMtWzaO-2FZqA1DjAwc_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP3rNbo5encOsbkYGUCwIZBF2XC9o39EkH0vF93IoX3mzq0rg3KOhaSmYbclJ8VX5Fj1whUgMRohSHjC8x7x-2F9BEfLZMbg09ftMWvyDNKZlkEo6kydPgGndwB0SLYkpJ5S9nZzcBeNNcpf7ED17Dgn00-2BjqUbOmDRz1u9VjGHHc9QZCHr2-2BsE5d5beZb2O1jWJ0WD3EIWNApLJx-2BoywxyS8K"
>Alex Patrón</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
🙏🏻 please please please make components for your Image Lists
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfKIZY6q-2FLhdz5Eu8PgcuW6iIDdKv77x76gq9gdMxo54FtkUiOM1IWJhe2wn6UH-2FS6bxZ0Bvz20L4WLopI-2BKyzOebIzbvTDKl8r-2BIfF-2Bieb3xVcGd_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP3rNbo5encOsbkYGUCwIZBF6k6e21XSmgOkSuFQow0GkKuYgakX4fCKDy5RFMCgnmt4wpR2O6OKb19x4zxmuD4ZU1a3ICu3Npo5KL626LCO28oxhfEqpl9-2ByRofvGwUws5GvkFPkhi0Uy-2BkH4Ejc7d4WjH1tkqdG0vZ74J4KHSMTweEbK2Ar8ZXJPpaAiQ2jVRQMEnCPMndQMuVEXb8tjSC"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by oliviertassinari** [comment]
Weird #248
