### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Kate Oh

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#317]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfK7-2Bc-2FvyTtgXEWluQ-2B0JSYy9UVc7R80pVwZOI5JuN0p13g51hdAPvAl-2F0vrualIBcJygMBzwyKIORfxi0JaeLN0-3D0qR9_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP3bTzFf-2BqRMFHqw45gTpQzykBum4301Edq0ghUTsGemsSxUMH2AImHpWEaW1u283Q8iRKztTKouBmdrAU36RtowM7u39oZ5jHL4RUJ5FmY7hxnMOpu-2B3IyMvd1Wavnn-2BQdG1YkYAK4sauFuKbjGeLKk-2BchZS8JpGIthWZ0tcF9uyr6L98muulmCcz6kkUoLAtK1Bo954ts6jx5vZh8gguq72PfJmFbaRXQ58EPehYbBUg-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfDB7elYRKalCknWNZZzi1blvQeT-2FWHdYmKebFKJ9nvrjaYfd_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP3bTzFf-2BqRMFHqw45gTpQzyjVHBUFFLLkncTaSp7ksJho-2FOgS2YK-2Bgk-2F5ruQ0AAeLbclruTBbJLQOISHLFekG9pd0BT-2B6v5DwTnWdgea0n8m-2BmeZeJKOuGtSliKDt17kFO-2F9SOs3WWfqSYPs-2BftocSVaap-2BZUOnP-2Bg1RgPD6A0cEavMg84Mt-2FLxi2XE-2FVgEEgncHv0LlOmqvlxiNr3ZpYVPUNoK-2B49tGh7QD4MTGsac5A-3D-3D"
><img
src="https://www.gravatar.com/avatar/f70cf4d7f3a1c84c0afe17a281b7fd34?size=240&default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_k_v2.png"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfDB7elYRKalCknWNZZzi1blvQeT-2FWHdYmKebFKJ9nvrjvLLH_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP3bTzFf-2BqRMFHqw45gTpQzyGdWlC5qZd7ldjHm8mRKWQpVrojgDHfmQ32dUQcNn0tl8dsisrJ99QKKEU1ajRjFsNsoOXs3tjsr67TBIr2uhGYQg7Df-2FYbpQoJ6abXWB6vrtpH7suQOtyIvJPFchIrNantzzw8e50gpBfrs2jyZmC3Gwvpv6WD9aKPtEKFVsaXEtsRfw535c87AKhMBoWweeAqvU1CXVF5Kw8BRYBJG2Ig-3D-3D"
>Kate Oh</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Hi, my team bought the paid version of 5.9.0 about 1.5 years. does that mean I need to make a new purchase to get it updated to 5.16.0?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfKIZY6q-2FLhdz5Eu8PgcuW6iIDdKv77x76gq9gdMxo54FtkUiOM1IWJhe2wn6UH-2FS6S5aq31LKz-2B-2F0MetHXolNo9ixnKLeAX-2BSEUIg7o8-2F1-2BRdoDa_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP3bTzFf-2BqRMFHqw45gTpQzya2KVIHxqeeA38YaLPmdJtcJETtypqMLo2Jr74CRfCz4KD-2F5cwAvJUIyTjL-2BCb93zlyZpeRadI9VM7r1qa0icSdLpQBsGMYjRmwxKlJnmMFae0Px0qC2rkpD7DSMxgxq97Gy0RnjkRKS4-2FEBqrKWqho7jOY3Hyy7dO9M2D0HzFu7mfQRxjgPq3ToxWkq56Vjkg0nv2WmKO5qAvvV9NaBtUQ-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
Answered:
> Hi [@kateoh](https://www.figma.com/@kateoh) that's correct. The access to new updates is one year.
