### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by James Meyer

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#319]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfK7-2Bc-2FvyTtgXEWluQ-2B0JSYy9UVc7R80pVwZOI5JuN0p13g51hdAPvAl-2F0vrualIBcJygMBzwyKIORfxi0JaeLN0-3Dpj___xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2b0V4RVmcqBo0n5C-2FVLpnPEEcBMAjssvWkl3iBgm0ozqr-2BTrBkGb1Q7ZPmV3uULT-2F1Ib51RR8xwewsHvT3aeLzoHAcFStHdLqBxgxOSA-2F8PuCUNFEEyFInXjILP7Vn4sU0OBHSffWlhfaPfimMlJHA8MrDGqUrkqcJxuqsD776BuwpZLcrDUtctuP-2FePC1m2TcIyZgrb3AALWtGXWp4lylOt36V6QS22HvC1xIK-2FzYZQ-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfEp1eEoqmbWuwgP42K8-2FWDPcLMu3CbIiZdqxUCPJZEwGUtDD_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2b0V4RVmcqBo0n5C-2FVLpnPLaLquUg6h-2FXm3C-2FrUbXTawkS-2Bbd8ftj5tFo3-2Byegui6yB-2BLZsZjcCNbWc6r2W-2FcSUbd5XxVT5oj5iqw1v3l7qUe-2F9cIbp57X8HkUBwQQMrQOOm2pWy7AU-2Bcr-2FSHtrH5KtzyQKXsyZOmrG5VOJ48hlo0IF6nKDiGVTSecMCcOshb-2FSGxWLxKexo34cyvsE-2BHoiwCl36XfQJXh7rRTAddo8w-3D-3D"
><img
src="https://s3-alpha.figma.com/profile/0c1d97ec-8532-4146-bf64-09d94f28e036"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfEp1eEoqmbWuwgP42K8-2FWDPcLMu3CbIiZdqxUCPJZEwGJNo6_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2b0V4RVmcqBo0n5C-2FVLpnPD2HEnB7ngyZWxYo8a7ReIOkVNN70NleOssBo69MLSJGacqk6h5DifputZ8Wt24mtqerdcQBxADAZaes29TsjqHcvk0BxeAJwVCHcP-2FGD3Y3hgh92cf1J6rm6wbt3Gna28NziIKKOlNWIvnJzWhDDvp41UIfMvO0sB0KsPJMqx91xQwC-2BobhetL-2BnQk-2BkhKzVgKdoBHL4Mj8QC-2BcRkRuLTg-3D-3D"
>James Meyer</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Hello! I understand you&#39;re developing a plugin which will export a ready-to-go theme structure. That&#39;s going to be amazing - how do I get on a list to be notified when this is done?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfKIZY6q-2FLhdz5Eu8PgcuW6iIDdKv77x76gq9gdMxo54FtkUiOM1IWJhe2wn6UH-2FS6bMA5gItzKXGzH9pYWMCEeitBW7jxlqWgdzzdLWX5svHRBz3_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2b0V4RVmcqBo0n5C-2FVLpnPNsUzfL47PnrKseGcTTAMltYdp3-2B6jgHbm6rWdQmPqe1-2Fe6UlBpz3rQ4Zk2-2FUgnOfLWxlpnUbSWm0iqNm3FTgbKxISXHSxdBrADfdLSvzHpTy3lL12zluthg8dctC0Tv0X7gZ5o-2BppPr4FoODfFY71gAHJV58GaL-2BIIqc3qIcBlIdqotnfiuEfr-2FxBc81SXzJtQ-2FaDIW07FVcrLH-2Bh30Swg-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
Answered on community:
>Hey [@jamesmeyer](https://www.figma.com/@jamesmeyer) the team is still waiting for the Figma's review of the plugin. Thank you for the interest!
