### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Julia Wester

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#321]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfK7-2Bc-2FvyTtgXEWluQ-2B0JSYy9UVc7R80pVwZOI5JuN0p13g51hdAPvAl-2F0vrualIBcJygMBzwyKIORfxi0JaeLN0-3D6nTR_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP3RALvr882lIp4CRNwoXl7Ti-2F3zxkC3Ur4OVfMnU-2BYco-2B4KRfFpybE-2BqDVtyr74OpQhBHD3bXGgt4J-2BLBqYDdlccem7Nb1s9ObrQbVupG10zuu9VAiD8jQ2nG4Meii8WDndsZc4EkczgcZyrNr85cANehocLx0bJ0zPljaqVisYjy-2FUdO7INp9sUWiJS9D6lK2RRRA8stu5Awa6E9F5fz-2BkzymS5vWs3gafs4OVvLmBZg-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfEp1eEoqmbWuwgP42K8-2FWDOrI0a4pLheodFFaO-2Bc0aW3Tz9-_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP3RALvr882lIp4CRNwoXl7TLUFjznnAAwX1mf2qqcBuAmZMg5zOTkzTrN1RIgVZIQY-2BYhOaoL6xNEZZlw4JtJtSk3liNYCq7eEbx9X30Mn-2FB-2BhdclREHrwfqb4t9y55YkYtcUAx7zu2-2Fc9PbV4w-2BA7WDYvbozJ-2FxyjVSMFIBG0pNi30-2Bgi7SobAksCWsRe80xG828OKJZIYpf9BaPCDlJ4Aq3SJX82TWWOj6rGqxiuuBQ-3D-3D"
><img
src="https://www.gravatar.com/avatar/881945c45fffea4cb3854037c85a03b5?size=240&default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_j_v2.png"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfEp1eEoqmbWuwgP42K8-2FWDOrI0a4pLheodFFaO-2Bc0aW3yqHC_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP3RALvr882lIp4CRNwoXl7TAZdCU5jAlEN5xRRMfeb9y9fAF8orPJ88PpOs5pEMJg04HkBd67Nf0peCdwsK18SCmgZo-2BfoK-2FXHpyWvlcoaorXD1FsDWEWn2CYOFlPDgWbch2yiZMO7io4s-2F5RpNOYLSmP44aszmqqD6vr4h9We55yXwX-2Bc0KhKkVHofWLcN4UXPWPj06YOFCQIvfBMRIQgqQsheqeOjG3WO7HCkQnaJyg-3D-3D"
>Julia Wester</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Hey, I&#39;m a relative newbie to using this design kit and figma overall. I&#39;m wondering the best way to manage updates. When I downloaded the kit I made a copy in each team (we use teams for products) as each has its own themes, etc. What&#39;s the best way to ensure all the new goodies&#47;fixes&#47;etc are integrated into the files I&#39;m using?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfKIZY6q-2FLhdz5Eu8PgcuW6iIDdKv77x76gq9gdMxo54FtkUiOM1IWJhe2wn6UH-2FS6RHA90WPxxtGH1OEERGNcj-2B9TtWQiZdy9D69E8giNL5YM_AJ_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP3RALvr882lIp4CRNwoXl7TTEhB-2B2ai5fARaeK5OnVvY20hF7-2FX5P-2Ff-2Fs2cfPhWft2lR5SJ5cVM0bK54PiFZ-2F49QPQGWSnFW2JjVVrW5nWfYJ5NY8ZC6ixLnAEU8KpQEJVJm22GS3fjQ-2BxtTqaqGjvmyTGyzm0Oju8Hxvnri8803QIIrUn2jnk-2FrjtWXsSBOTeNkR8a47QfjYMGz8CMD7UDtE-2FJMor91I32fF3UE0nlXQ-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
Answered on the community:
>Hi [@juliawester](https://www.figma.com/@juliawester) updates should be manually handled, unfortunately. We ship quarterly updates and we recommend updating when it is absolutely necessary as it requires doing the process of customisation all over again.
