### ISSUE TITLE
Design Kit 5.16.0 / Select / Focused Inactive state 

### ISSUE THREAD

**Issue by olivier-g74** [mui/mui-design-kits#322]
### Steps to reproduce

Link to live example: ![image](https://github.com/mui/mui-design-kits/assets/110830121/fcfac951-6422-4dc4-b28d-e411ec36f66c)

Steps:
1.
2.
3.

### Current behavior

The chevron in the inactive focused design of the select is oriented upwards
Issue similar also in Has Value=false section (not show n on screenshot)

### Expected behavior

I was expecting it oriented downwards for the closed state, upwards for the open state

### Your environment

| Software            | Version               |
| ------------------- | --------------------- |
| Design file version | v5.16.0             |
| Design tool         | Figma |

![image](https://github.com/mui/mui-design-kits/assets/110830121/fcfac951-6422-4dc4-b28d-e411ec36f66c)

**Search keywords**: design kit / 5.16.0 / select

**Comment by adrianmanea** [comment]
Indeed, I've just tested it, and you're right. Pressing tab to focus on select doesn't alter the orientation of the icon. Thanks for bringing this to our attention!
