### ISSUE TITLE
Can you let us know if we are eligible to download 15.16.0. MUI Figma Design Kit with our annual subscription?

### ISSUE THREAD

**Issue by cambridge720** [mui/mui-design-kits#328]
### The problem in depth

Can you let us know if we are eligible to download 15.16.0. MUI Figma Design Kit with our annual subscription?
> Edit: I've removed the invoice since it may contain private information. Thanks!

### Your environment

> Removed

**Search keywords**: Figma

**Comment by adrianmanea** [comment]
Absolutely, you can work with the library even on a free plan, so no worries there. It's definitely compatible.

**Comment by cambridge720** [comment]
I was provided this link https://mui.com/store/items/figma-react/ which seems to show its 79 dollars? How can I access this within our current subscription?

One of our users asked about this:
"Hello, the Product Design Team uses the Figma Design kit from MUI.com. There has been a new version released Version 15.16.0. I am requesting a download of that latest version. I am unsure if we are still within the terms of our yearly license, if we are the download should be free. Thank you."

Please help with next steps.

**Comment by adrianmanea** [comment]
Hi, of course. To download the latest version you can sign in into the MUI account (with the credentials used when purchasing) into the [mui.com/store/sign-in](mui.com/store/sign-in) and you should be able to see a 'Downloads' tab.

I can also send a copy over your email if it's too much of a trouble as well. Simply email us at figma@mui.com and mention this thread in the email contents.

**Comment by adrianmanea** [comment]
Closing the issue, seems like customer solved the problem.
