### ISSUE TITLE
[figma] Changed primary variable color but does not update across components

### ISSUE THREAD

**Issue by brianhippomac** [mui/mui-design-kits#329]
### The problem in depth

After editing the local variables on the MUI JOY Figma files for Primary -- none of the components linked to Primary variable color update
<img width="1106" alt="Screenshot 2024-04-10 at 7 48 13 PM" src="https://github.com/mui/mui-design-kits/assets/165154606/ae2e23e6-f530-4a99-a7d6-493b5fe3109c">

### Your environment

MUI for Figma v5.15.0 - Joy UI v5.0.0-beta.9

**Search keywords**: change in variable colors not updating on components

**Comment by adrianmanea** [comment]
Hi Brian, the colors can be changed from the "Brand" collection. I think you may be using an older version since we have the colors from 100 to 900 range.
