### ISSUE TITLE
[figma] Add the "tree data" feature to the Data Grid

### ISSUE THREAD

**Issue by olivier-g74** [mui/mui-design-kits#331]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Checked the Tree data as presented in https://mui.com/x/react-data-grid/tree-data/
2. Purchased the latest Design Kit for Figma 5.16.0 at https://mui.com/store/items/figma-react/
3. Looked for the component in the section Data Grid: rows

### Current behavior

The component for Tree data is missing

### Expected behavior

I would like to have, like it is available fro Row Grouping feature, a component for TreeView

### Context

Leverage tree view without having to detach the instance of Row Grouping and change it to mimic Tree View

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### User requests 

- https://mui.zendesk.com/agent/tickets/9011

**Comment by danilo-leal** [comment]
Heya — thanks for the shoutout @michelengelen! I moved this issue over to the design-kits repo so we can better track it in the context of the Design Kits. We can try to push this one out for the next version.

**Comment by olivier-g74** [comment]
Can you please note that the Cell 1 that contains the chevron and the Goup name is currently "Align top left" and not "Align left" like the rest of the cells, so when you switch Density of lines from Standard to Compact or Comfortable, it creates an undesired padding.
![image](https://github.com/mui/mui-design-kits/assets/110830121/3a1a112a-38f1-447a-8b3b-e8d9ff565b95)
![image](https://github.com/mui/mui-design-kits/assets/110830121/18076df4-7c49-4d7c-8137-345da2a7527d)
![image](https://github.com/mui/mui-design-kits/assets/110830121/73f1509a-8cf2-4432-944b-5e020b2ef1c1)

**Comment by adrianmanea** [comment]
Noted! We'll do some tests for this case, but it's rather hard to maintain order with so many variables in place (especially undetached). What we recommend is to see these as starting points and undetach and manually adjust Cells.
