### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Yuri Cavalcanti

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#332]
<tr>
<td align="left" style="padding: 0 0 36px">
<a style="text-decoration: none" href="https://u3302489.ct.sendgrid.net/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsXQktFkKkRmHBuf8gQGLsIfCB36BmwRRLzh8ERIeDrounnYBDnmr416igNBAW4XT0w-3D-3D0L0w_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP0LuIXCYkByYz2rTY0wW0zU3PH-2F48CU5BPf1sMw4j5h0KeIJqDsHCPYESqD3Z9Ro-2F8eL4EXaVq7D-2Fw2IyUQvOa7QlgfGgWPDTk7ywg82VjPCgmly-2BOH5X1KYUyS-2F92uW1GzpWeh-2B5G93VuasqdYLaOG8Sa0NHaBliqAMfW7B0eSFlgsgwNaDkaXOYcrjqg2veXE08JtkbXZ62zeNpS-2FZkRBL-2FV9H2X3FyAWpoPsQn349g-3D-3D">
<img src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390" width="65" style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
" alt="Figma"></a>
</td>
</tr>
<tr>
<td class="wi-100p pb-30" align="center" style="padding: 0 0 52px">
<img src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792" width="392" style="width: 392px; vertical-align: top" alt="">
</td>
</tr>
<tr>
<td class="pb-30 plr-8 fs-24 lh-28" align="center" style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
">
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td class="ptb-20 plr-25" style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
">
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtscqPHae-2Fz4wez9t-2FP1hVwFrdXq1WZ-2Fy77AmdAGfDHQKG-2BCBmdkBLZbt-2Bz6NSC5ggoA-3D-3DM0dk_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP0LuIXCYkByYz2rTY0wW0zUDsAgQeRAeB4b1RvQpVzRrvej1cS3ewOb4bpnUOfDdVHA8wklCLpZamZomIjdAmi2j8Wiuw6ppASQJRdkcQKnSxXplAj-2BL7ftptKzLkjsUiaZqzZ8j58lCsx-2BjhlaUDpxJhrY6G2lE4Qix85dD-2F3eoEPabRW3s9RmX-2FJc-2FZTb42F4iOntdTnk-2BCErgFgZxJMdTYiEB88ps-2BvtsdlPSks36w-3D-3D"><img src="https://www.gravatar.com/avatar/45cb48e5f16b705b24a921f4b27855c0?size=240&amp;default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_y_v2.png" style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
" alt=""></a>
</td>
<td style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
">
<a style="text-decoration: none" href="https://u3302489.ct.sendgrid.net/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtscqPHae-2Fz4wez9t-2FP1hVwFrdXq1WZ-2Fy77AmdAGfDHQKG-2BCBmdkBLZbt-2Bz6NSC5ggoA-3D-3DSWAZ_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP0LuIXCYkByYz2rTY0wW0zUleE3GmMSYNfxaWGazXr50DntQ5upus23r8UAgrBpDOtMdYb1oq0zzTlFXEehRBjrK1ypMmb4e9Pvm4XnvSo8tm-2BjmMEyL7jHPJxIXZdq-2FW-2BFiOVWxKHTyrXriZb3nu8jePSTld4C3AGJ6LRcEm2h3oDwzqiUAjpD1WZLOmTzbP1MMuMujuyD35bJjJLBIaCsM3MRWL8EekNIoebG1o41YA-3D-3D">Yuri Cavalcanti</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
">
How can I apply this UI kit to a page that already exists? How do I install the libraries?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table width="223" align="center" style="margin: 0 auto" cellpadding="0" cellspacing="0">
<tr>
<td class="active-t" align="center" style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
">
<a style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
" href="https://u3302489.ct.sendgrid.net/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsUaqRoYaAqeRVuEiEhgjy88PHLBNIzrxma2r68Ep21ac-2BhYSGvA8F2EyamDSvWZ-2BPg-3D-3Dx58N_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP0LuIXCYkByYz2rTY0wW0zUwiTd1s-2BS-2Bk3NItC4nLUNM6xMpFrCqbq7aYCNSIrZNeIYFqrmHsP6w0U6mcevB-2FmhJMkFdeBAyR9hpYZz5yzOHO4CtQ8oACeINZZxKwxHr60swVj9m-2BpDdokNcVxacy2mUesESU8Qa6mkhcrcYgGL2m-2BE2WCzV-2B32gVT0b3-2FBCqnbK5FRRRMXzUQ8aNc-2BmTXmDz7IN4GeTVMwpv9zmr6wLw-3D-3D">Reply to comment</a>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
Answered:
>Hi [@yuricavalcanti](https://www.figma.com/@yuricavalcanti) sure you can use different libraries in an application. You can find the getting started guide in the first page.
