### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Karina Hinch

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#341]
<tr>
<td align="left" style="padding: 0 0 36px">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsRyIRFtnfwZwMsadvavo9IaDz9FG0tJzNujmZYm5bFVZF73-2FBzvv-2Brc3XJlgceo2Yg-3D-3Df1OI_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP3Fh-2BsHOhuLZCFU56Qg4xe-2Fi-2FOugEPVVTP8Eldetg3-2B2k11v9SgBwpiZ65RrbhbR0DSpDurL5GVKlx64O-2BwTv0oRwSEAzJVZ51yAaiejhtQthbWTeH2XxJqYsBGmC83RLo3E-2FlrMFb6PHN3wD0-2FKDKrWxzEVWDQDQulNnUXryL401jPpD8Q-2BHXM6q-2B-2F86d8RrLvOcOn-2B-2B3Od6pRZ-2BkeSPdSzuNiu5Twt6mUDaA1D6o3YQ-3D-3D">
<img src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390" width="65" style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
" alt="Figma"></a>
</td>
</tr>
<tr>
<td class="wi-100p pb-30" align="center" style="padding: 0 0 52px">
<img src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792" width="392" style="width: 392px; vertical-align: top" alt="">
</td>
</tr>
<tr>
<td class="pb-30 plr-8 fs-24 lh-28" align="center" style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
">
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td class="ptb-20 plr-25" style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
">
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsbPNt3Z4SDglv544k-2FQdHHrQTF6VF3fakp24a3vp2Rw9VE3oRkFhArqMFdkFgsd6-2FQ-3D-3DFpht_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP3Fh-2BsHOhuLZCFU56Qg4xe-2FszF7xbmHu0mvR-2FPUumEdnQHhrii2YoRpgmKY5VSldJ9R7yusLW1NcBLX8fYmpFzNapBuwGXbTK38rWZzfFlmXYz-2FjDy12qUmtBClu3V4oCssbOHwQqDCDPiH2Hs6mUQEuUekQ-2FljxylUN-2Bhn4pUGCwmqVPk-2FaaTdHf78HuQPvLIJN0zoowlzmO8Pj3kmSpeEh17AcOze869YD95ArY21SA-3D-3D"><img src="https://www.gravatar.com/avatar/693b58868f9a454522b40597e9a2dc28?size=240&amp;default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_k_v2.png" style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
" alt=""></a>
</td>
<td style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsbPNt3Z4SDglv544k-2FQdHHrQTF6VF3fakp24a3vp2Rw9VE3oRkFhArqMFdkFgsd6-2FQ-3D-3DkIUX_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP3Fh-2BsHOhuLZCFU56Qg4xe-2FuR9YPZrQGo4-2Fg5V19uKfkDdBHiK23QnKBBz5YapmdtgeXg-2F6-2Fi11rke1Odyv-2BiFAST1rEl-2FHp1Sr4uNq568ScZd1KKpgnux9sDMngmNfVIQBrosYVIJFtkWpUNy20NIbneQKDrrh-2BpKFAzUmITLSmTi6yO8RbWSvDvUmI1MYNorgYLzqu75OUqjIcWCD7bXuFm0615GZUM5Nib1MgavKOQ-3D-3D">Karina Hinch</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
">
Thanks! Which version is this based on? (sorry if I missed that documentation somewhere)
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table width="223" align="center" style="margin: 0 auto" cellpadding="0" cellspacing="0">
<tr>
<td class="active-t" align="center" style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
">
<a style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsdnEayq3onbB4K-2BFYrHWsDfnxlADiPQyshluYHky5wUyeKEWgwLwfg-2FTAeJ0txnj4Q-3D-3DNAfr_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP3Fh-2BsHOhuLZCFU56Qg4xe-2Fe9oK8IshxQUbufMVlpPm8WnCaJmSYc5CJbenQhYZQDzESgzxSe3N4anvNQYYsmt-2Fy0QiMW8AgIMoqKiIHEJUb-2BfbRMfBh-2B3Lk6SpPreg2l7QihAwHJJoc-2FfwqB9AGwizuGeJ9n67Pd3n069vtwoaniU9nQRJdr0Ed-2FAAkhk7Lbwc0TaARwMrh7j4uRdu610twQ79HDch-2F2X-2BaLepJ3yK4g-3D-3D">Reply to comment</a>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
Answered on the community:
> Hi [@karinahinch](https://www.figma.com/@karinahinch) the community version is based on the 5.16 (the latest one at this moment).
