### ISSUE TITLE
Nesting Stacks - "Components can't contain instances of themselves"

### ISSUE THREAD

**Issue by johnlahut** [mui/mui-design-kits#345]
### The problem in depth

Using the latest MUI for Figma, I am trying to design a UI using the design kit. The design requires me to use some nested Stack components.

When I add a Stack and then replace an instance of that Stack with another Stack, Figma gives an error "Components can't contain instances of themselves".

How can I put a Stack within a Stack using the design kit?

**Search keywords**: instances of themselves, figma

**Comment by adrianmanea** [comment]
Hi John, unfortunately Figma doesn't allow nesting the same instance. If you want to replace the instance with more items I recommend defining a new component with your items. You can find some examples in the Card page.

**Comment by johnlahut** [comment]
@adrianmanea  I see. Thanks for the help!
