### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Ahmed

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#346]
<tr>
<td align="left" style="padding: 0 0 36px">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsZ22MvndV6DSJLgH-2BpXo3WVwqadYdo8wsTUIre27z8QYnKp6mIe700puvufnEhCCXA-3D-3DB-0v_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP1bTqQVABYA5iCU5BfEGlcwVFGChWr7EsuwgHO-2BTEtXYhAxtjXrrQRysnUk5xavoilzRiPptSffXva8Hczbumcushxbl9v9UUsAaAVAWA2rZ8gfm3MX4Q17oCtmdLH1rjaBADHJFOA3jdEWl9FYgRhRCBpVUrLpn8xvCKpAF8jEv5bfBymAfdtmp6jBh0kViprMur-2BCdaInJIakfqs1-2BOcl-2FmX3sDo41p6XGxj1m-2FAH8Q-3D-3D">
<img src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390" width="65" style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
" alt="Figma"></a>
</td>
</tr>
<tr>
<td class="wi-100p pb-30" align="center" style="padding: 0 0 52px">
<img src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792" width="392" style="width: 392px; vertical-align: top" alt="">
</td>
</tr>
<tr>
<td class="pb-30 plr-8 fs-24 lh-28" align="center" style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
">
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td class="ptb-20 plr-25" style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
">
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsXpSczO0YnbSxH7moZXC1ogBkNBflpQsxQf1sJ9cRVAhOTcWHgJqxMjxdnQJJ-2BZQBw-3D-3D5lVM_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP1bTqQVABYA5iCU5BfEGlcwZ2vqmEgfM9x3KRTEpphIM-2BS-2FuZhzKYtNFquzEGxnBDp2wrwir63a2hwbR7cIvOEZoUEN34CwVdcL4yIa5KSQLb7-2B5qgbGaVmk2J9k5rHx-2FasLDgeJY2qzfMx4vCdQzaEbWruIKKEyb3J7OKKhpdDiuMBAdR-2BIVB1oMhm-2BioLCtVRogWwVHtQKOOIlWVZawtQ7wDsgGly6TvU06EzqUtNsQ-3D-3D"><img src="https://www.gravatar.com/avatar/787fe37925c5ee69f6050e5dd09c2932?size=240&amp;default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_a_v2.png" style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
" alt=""></a>
</td>
<td style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsXpSczO0YnbSxH7moZXC1ogBkNBflpQsxQf1sJ9cRVAhOTcWHgJqxMjxdnQJJ-2BZQBw-3D-3DPbDz_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP1bTqQVABYA5iCU5BfEGlcwS-2FH-2Bt5V8qsQRE05780sYVxR08Neqnsv0-2FZG4UHUsyvMF0gJ1-2BKjecrtuQPEQGxnKi9j69BaGMSFhw7PgTcOiKMZbFVf2T6MCfnq7UoyTQFLmrgATWzaHJnkb9ld88HKGjGID5T2ZpCyLG4HAb-2FGv181ZNYkJN6jdWadeKzXsQv-2F6JJCe7irIKEc6mXJ9liQKMHc1ROGxA3zlTH5OFB3-2BFA-3D-3D">Ahmed</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
">
Was someone able to change the theme colors? Im just can't edit the color-pallete.. did someone have the same?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table width="223" align="center" style="margin: 0 auto" cellpadding="0" cellspacing="0">
<tr>
<td class="active-t" align="center" style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
">
<a style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsWkrShfQwwMIrwoE2ImCsCk3tCtiUbiZ0MoFRNQtkdH-2FFGc-2Fs0-2B1plWf31ZVC4-2B4eg-3D-3D21z-_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP1bTqQVABYA5iCU5BfEGlcwjkH3AAD6v3dizULpLOieZaVVVB5Ghf4oYxUPyULYctqzXxKcjF2Y8T0g7hU1A5GRrE-2FpvXs1tlpbcHZNTGcPWTU-2FBCHCLiL4qL4RWkyYb7m8H666tOJ7RLZHOGla9CRJZZVI4bZ-2FcGQSmf7aveVmsMJpTfAihQgER2kuGZDa34VtU-2FPK0LhI-2BDB3hgGxObW1O5BRaIdMGrKpQ7JcrHKSzA-3D-3D">Reply to comment</a>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
Answered on community:
>Hi [@ahmedjmatar](https://www.figma.com/@ahmedjmatar) you can change the palette from the variables panel.
