### ISSUE TITLE
[figma-pro] Invalid assets on publish as library

### ISSUE THREAD

**Issue by smith558** [mui/mui-design-kits#349]
### Steps to reproduce

Steps:
1. following guide at https://help.figma.com/hc/en-us/articles/360041051154-Guide-to-libraries-in-Figma
2. download the full (paid) version kit `MUI for Figma v5.16.0 - Material UI`
3. import to Figma
4. press "Publish library"

### Current behavior

![image](https://github.com/mui/mui-design-kits/assets/44023416/1410bdd1-a4c4-4db6-9b7b-9924f80e7b74)

### Expected behavior

No invalid assets are expected.

### Your environment

| Software            | Version               |
| ------------------- | --------------------- |
| Design file version | Material UI - v5.16.0                |
| Design tool         | Figma |
| etc.                |                       |

**Search keywords**: invalid

**Comment by adrianmanea** [comment]
Thank you for reporting this. It must be something new, since all the components are processed by me. Can you check which unused properties are causing the issue?

**Comment by smith558** [comment]
> Thank you for reporting this. It must be something new, since all the components are processed by me. Can you check which unused properties are causing the issue?

The unused properties were the only properties of these respective components I believe. I removed them for now as a temporary fix.
