### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by trexgameaz

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#353]
<tr>
<td align="left" style="padding: 0 0 36px">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2Byqtsds1i449-2FfFnj1fGooppZAs-2Fga7ZfhXcrM3XqHHP2AHwG7AwGrrZGZCBJXV7PcFT1Q-3D-3DsSgW_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP1GQIbhb-2F22a8yGBjVjjzk8LQS0xIy5pgE99iHRaOXqnJ3MfY6snpzUPk1jMUbso0DLpnofo-2Bb8BhOGHsgNMB2Q06EiF1fccLBZK49ULC02phjOmwP-2BR26rMKdjYBpNbW0txXZFFiXa5-2FTF1kw2XDByQCUNBDHYfu1EI-2FQKhWiAMfuZWZP32vUgBD7V4aDhhurvd8q4d4YG7RqCyIKdroGA-2Fl8ESvOrCZyGu-2FZMVMR80Q-3D-3D">
<img src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390" width="65" style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
" alt="Figma"></a>
</td>
</tr>
<tr>
<td class="wi-100p pb-30" align="center" style="padding: 0 0 52px">
<img src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792" width="392" style="width: 392px; vertical-align: top" alt="">
</td>
</tr>
<tr>
<td class="pb-30 plr-8 fs-24 lh-28" align="center" style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
">
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td class="ptb-20 plr-25" style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
">
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsYzNhk3uHBgzTV1uZfO8nlI-2BgNEP8cG5g1m27TCsEW4J6zPfhlNQMn3NoDClvHr5tQ-3D-3DzVoE_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP1GQIbhb-2F22a8yGBjVjjzk8gUsJzU59afifHa1gG-2FvtuvQ9bsDI6L8J3z6qneixoWNOXzkRGUY5TK6TqV7gu3-2BsZQgJkjzTA2mma79gT-2B3C8bhcfjp-2Ffr-2FjnTeK4-2BqSYViTIVCiCIqRSWIerFtcb3wZs8WFmgntUFjHGNk5fjwyCC6dNycjq6HbQmp3qkfmLeHUKNnO-2FTKxCt-2FnYQvmqKRkpDlCrygjlf2By3wG1bayLw-3D-3D"><img src="https://www.gravatar.com/avatar/99afc88c437c7200ad618142b248aa2a?size=240&amp;default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_t_v2.png" style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
" alt=""></a>
</td>
<td style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsYzNhk3uHBgzTV1uZfO8nlI-2BgNEP8cG5g1m27TCsEW4J6zPfhlNQMn3NoDClvHr5tQ-3D-3DriVD_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP1GQIbhb-2F22a8yGBjVjjzk8VANQDSqcLhijGME0vusS4zeV0584aF48hmLAG4FXM8LYdGqkVmvsY9FbHb7cwSp5q6ZdJXuWTMWDn0qBB3-2F2w5fKpsCj-2B61KNfpaS8l4I7HP3EV8ckZRv1dBCVurNg6jnZEATDj4OiGFrNBY9eW2TJFC-2BO9XTRu1CW4PkmXi-2Bar6AfKn-2B26Duid3eChBWwts2nsEqhqNldtgASmzkwgjbA-3D-3D">trexgameaz</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
">
These days, we frequently engage in https://happywheels.one play. This is due to the fact that our children are now older.
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table width="223" align="center" style="margin: 0 auto" cellpadding="0" cellspacing="0">
<tr>
<td class="active-t" align="center" style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
">
<a style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsQWZdxqk4HqH4yfDMcL1HF6FF5vHjPiX-2FyuSlVhS9PBOBPLTAQz-2BChBWzWdzavY12w-3D-3DBA1F_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP1GQIbhb-2F22a8yGBjVjjzk8ssUZFrb9wojRKF7i0ZzhhmiyKSh1sxwYmgvGQWF5MJ-2Bwj1ARYwFFm1TkJYuLK2T80kWqHY2eWbF0j6vW2mdc2kgLhl233bE-2Bw7cwdD57QFCugQHkMrgiznDbqCZxD3TqDJfHIuV5GQKUZWYl5BlpiaCCQmrEK0okFaLdA1J5fnmJH9IhzCKRYKhWFRa3DvC4XmEzx7UHWCEagqcyicU8lQ-3D-3D">Reply to comment</a>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
Looks like spam to me.
