### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Abhishek

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#361]
<tr>
<td align="left" style="padding: 0 0 36px">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsfkYl5HLt-2FK6IHCa2FCMV8z-2FuU94XHFs2pHCxdaH8Z3VQuJgg755OsnLxCb0frhBng-3D-3DaDHY_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP0ZiMHTLD5BXjrIwEj-2BETeN2yzGea2vJQyA7o8givEw1xAGdAG4fmYfNV40UVXzJ7M8QnIZMAJqjE-2BAPGp5EVdwHg43YKfPVfblte7hkSgEp63HbTKJa7KzRgF3Wr04Dc13GRncLINvLrLFOkQxmB6a-2BGC2Np9O776BMgZhqGSTDM82HgqTCGs5fNP1nj-2FORe3jLP5-2BLY-2B1HLHy8UwNGxqGSNPu5HB1Zv62-2FExgqYqKyUhf70-2F-2BRuERobOd2mydDcjiSY-2BCztlyXTBwTibnaimiJI5CtN-2FDMKXx6Q76JVvLpQ-3D-3D">
<img src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390" width="65" style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
" alt="Figma"></a>
</td>
</tr>
<tr>
<td class="wi-100p pb-30" align="center" style="padding: 0 0 52px">
<img src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792" width="392" style="width: 392px; vertical-align: top" alt="">
</td>
</tr>
<tr>
<td class="pb-30 plr-8 fs-24 lh-28" align="center" style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
">
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td class="ptb-20 plr-25" style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
">
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsV9TsHUGhKyNepzmABSJ9eM-2Fsz2NEgCrOqgEHCSrhzCNVPhy35z-2BSGQf6YF3-2BDNMgA-3D-3D58GC_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP0ZiMHTLD5BXjrIwEj-2BETeNNNp0HsuvOQy1Q9yTjxmgA5TvIeSDmdN7fiK5s25FpnuWxb3FxjZ6G6tQSDPtVX899VUD0AQ8FzT7DThCgl8Y4EuuAheUe49tE3ox7yGjAata9YVq0-2BFiNkfxSfwpxGiJGoltrVal7pc-2BVWHAnFeR68PY0ANgRx-2BQX78Tz9VTNrSPLigLiTpbQlF6lnuobFPxW3kTa0EtwLOFtBue-2BU2r34UffB9Tj4A-2BzxEpPv0hOfG0HPP6jSW0nOkKyE91imSmTqVchDHnc-2BIpKgwAoRujAw-3D-3D"><img src="https://www.gravatar.com/avatar/f41118209b491bebb14e6a0c03731ea1?size=240&amp;default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_a_v2.png" style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
" alt=""></a>
</td>
<td style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsV9TsHUGhKyNepzmABSJ9eM-2Fsz2NEgCrOqgEHCSrhzCNVPhy35z-2BSGQf6YF3-2BDNMgA-3D-3Dlggh_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP0ZiMHTLD5BXjrIwEj-2BETeNupkMjeXWrR1ocszulwD6J-2FOXb4qYQw9PfZDd1fz-2BK81HxEbBXE24lVyWqxSh2V69qcTajBhEvuwKpGUrQQI7ifIOqSbYifu9uh8tChLVv5d-2FIvi4mrXXZ2l37kl0jkgTfw-2FQ2PHHsu1m743xtEH42bY7LVmF0ZVR8fezVDM0a4KX6tFUh-2BJjd9PEGdnwGeAr5XHLZdwRl7-2FtLjXhTmgyN4HgUh80lO2-2FmB6REXPlU2WR1trxfGXBrcRpat0FqVs9nmFkS0nECh46vKufoFazug-3D-3D">Abhishek</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
">
Hi, I am planning to purchase the paid version but before that just wanted to know does it contains the mobile app native components in the kit? if yes, then which version it supports M2 or M3?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table width="223" align="center" style="margin: 0 auto" cellpadding="0" cellspacing="0">
<tr>
<td class="active-t" align="center" style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
">
<a style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsXlmo1zF6ZBTpQmCdSoOlZcIyA7IrU2ZxS5F6eWDq8r60dgQo2su4ZKX76ZPK5C-2FMw-3D-3DjZYy_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP0ZiMHTLD5BXjrIwEj-2BETeNMR94YGDgIvpTit474Low2x57HI0sDdOfF8hz-2Fd03bijdXnayndIqnmvMcswdoRh8rBCSWeJn12XZ7Yc3KOW8MCDzMGwyWSYmfQV1gksZVGNMdMGBMExgULXdEaTYuUOYOw8oJ774QFY8I5xdPfS9M4X2B9v70dv-2BThcayigUz2PWLeSFgeMaYcFSsUEpLdpljVF87M2vGSW0yF6NICAPpwlAKhpGeDkoMqJzmmCtFLNzm0zP7e1KDdAmuF6QNV6eoIcoMIp92eA8MynzrRSqZQ-3D-3D">Reply to comment</a>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
Answered on the community.
