### ISSUE TITLE
[sketch] Add Card component back? 

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-design-kits#37]
We got this review:

> The quality of the library is good but i must admit it was more easy to work with version 4. Within version 5 you are missing the cards. Are they comming back?

@software-vision.com

Should we do something about it?

**Comment by adrianmanea** [comment]
That's correct, somehow we mistakenly removed the card's components! Damn it. We'll have a revised version by the end of the week.

**Comment by oliviertassinari** [comment]
Fixed in v5.4.0
