### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Fraser

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#371]
<tr>
<td align="left" style="padding: 0 0 36px">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsYPTj2f25ykfcnaYAZNG6dJPDqcZu15zcCNStKAYB0T0EBj2oQYyLKL-2BQF4bOqXxxg-3D-3DRuxQ_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2-2BD2Oh7M7mQsas0iR-2BGBQ30bAJhRx-2FWydQmQSKtbsvOj1RPTG7ioyCAFEC35Kdau9kBxkdsuX1vDW3CQkY8eAW0ImKauTB7fyGokPKdhRnMIl9-2FnyT79L5ZaJps-2BayTJyyLQPlBN4dRuw5R4Yt8OETnUiUBJI9-2BWXdhBDjqUoYBKRXtaw6-2FIAmlNvgtAGFaTjwXDYzHAOOQFGWa-2F-2B-2Fc0hJg8opcSteZHJw-2Fj47CNUuLHRRGgLkGhO8uJUwVhLfFbl5tDM3ATeFVfNhLwM-2Bu9sYfpoiwk2AcTnaGPV2GTPaDw-3D-3D">
<img src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390" width="65" style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
" alt="Figma"></a>
</td>
</tr>
<tr>
<td class="wi-100p pb-30" align="center" style="padding: 0 0 52px">
<img src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792" width="392" style="width: 392px; vertical-align: top" alt="">
</td>
</tr>
<tr>
<td class="pb-30 plr-8 fs-24 lh-28" align="center" style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
">
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td class="ptb-20 plr-25" style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
">
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsfMAEGiX18iAeKvGzK7KslhcFymTH1yMFlOJbDwgLtmdU6j9Ek5IX0p9LL-2B9seU9Lw-3D-3DNybi_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2-2BD2Oh7M7mQsas0iR-2BGBQ3ZJMTaYxrDd95QlsSEK8G2gyIqlks-2Bv-2FS-2FObEXGR0GxqlrB8KpiAyQ5iZyGESSZB7HsPsQ4dKiLd3W-2F2so9E74-2BCA7ZeP1-2BafLX3uapBR2Iq5jLI2akbc2Yn0dE2KmCjSKE1hUdLWAVc53b6LDucYw8IDv8yxL7X0qD2UYY7UyZbufeKZsM6ZY-2FXbQWY7jxuNZQm7ZdMg-2B1GKKOFApRwnBm4n9gW8aDT7V9wS3oaFfRSUEOY8RZmUBNGdOu55SJVQhe-2F-2FJTyeDd5JgsrvGGvnIg-3D-3D"><img src="https://www.gravatar.com/avatar/4752eecad4d27bb49ddbef7cea0f2ea5?size=240&amp;default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_f_v2.png" style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
" alt=""></a>
</td>
<td style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsfMAEGiX18iAeKvGzK7KslhcFymTH1yMFlOJbDwgLtmdU6j9Ek5IX0p9LL-2B9seU9Lw-3D-3DVg0C_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2-2BD2Oh7M7mQsas0iR-2BGBQ3Gb07AuaU3qyQeZEk-2F9eM9YHxXppmOxOgWR9kaS0mp9ODzo4ArGYFYpuIfWNlWOLXK1KnrXcj8g0t6cdIsQh-2BrBD-2BESYmynt5VfTU-2FnlMMga5ux-2FMypFT9rglDncC5JV8qsmCmpMzUohgpmXbL9r7tLM07Dd0E-2FOo1zvHKWuaSBUTaiPf21x2EnnRaPcilZ-2BbjVSHcYYNb9nFmJKV9O-2B3WAmgbrOEwhZyhlRPwdWxRLPIfplObz-2B4tTwskwRUKyLNbbJtbegmPgwKheDEgSnSqg-3D-3D">Fraser</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
">
Hi MUI,<br><br>Can you tell us when the v7 version of the Figma library will be available please?<br><br>As per: https://next.mui.com/blog/2023-material-ui-v6-and-beyond/<br><br>Thanks...
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table width="223" align="center" style="margin: 0 auto" cellpadding="0" cellspacing="0">
<tr>
<td class="active-t" align="center" style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
">
<a style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsVCyU-2BkhU7-2BwJehAZH0h0FDP8t66oX-2BCDt4XPp2rKofIeHVWpG4LPpiZ2ecxQnSC4w-3D-3DD9t0_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2-2BD2Oh7M7mQsas0iR-2BGBQ3hvyE6E-2BkZGhu5vNmrvvOaQEOLip9h3wMuykWoANDwVtBBjTRwRVRuu7RjPVhrGsr19Bj2pk0xSBulVH5jA2rK6W8I0reUSaOxj6gdqbi-2FDWbHX1McA-2BUF6fDJmCbq-2BuK4Kj3QfMyPNe7Qbq1NicxcGdPrv3M03yNjXT-2BCNECW-2FG9sBist-2BJ4xbtxs8D0XADRpbqDoXxRfrJhYvhcRgLVoydE10VzkEbq3TccMt-2Bat0RMSKz35V1ZxD1viyoSPc1o-2BTynYnBmZFM4jXNVy5KE5g-3D-3D">Reply to comment</a>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
Answered!
