### ISSUE TITLE
[question] Select component dropdown/menu items

### ISSUE THREAD

**Issue by dkeulen** [mui/mui-design-kits#374]
### The problem in depth

I am using a copy of the master select component (3 in total) inside my own design file and i was wondering how i should use this component correctly.

The dropdown/menu always shows the master menu items with the "Menu Item" text instead of the text i have given the menu items.

Do i need to copy the component 3 times with all 3 their own menu and items? Currently I am able to give all 3 their own label and default value and/or placeholder text. it is just the menu that always shows the Kits select menu with "Menu Item" text when i click the selects in the prototype of my design file.

### Your environment

Figma 124.1.16
Mui for Figma v5.11.1 Community

**Search keywords**: Select dropdown menu

**Comment by adrianmanea** [comment]
Hi there, can you please share a quick video demo of the issue? I'm having a hard time understanding the context.
