### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Juan Cruz Hernandez

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#375]
<tr>
<td align="left" style="padding: 0 0 36px">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsQ7JNAUQRCiBRd00Sm0Q-2FqiPM7KVW14dmVFwexmf4JZ-2B3db5WN4LbeHAvYzyPEiFlw-3D-3D7YLn_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP1-2FBrtG-2FgvrlVYuxbTmdKVHB5-2F99g9LRiQ-2B89UddjqB33TIkb8D-2BzQbU6Cc-2FZLrjwgD6JGYadtzxKcrnG2dvPKPQ4eqre3AoWQITkcYaJ2QeN98FIuxVVAivLDv0TTxph878nrZKi-2F2a0RGWfGHK2TEW-2Fv6XioX1rX6CQJUEzrtuk-2FpYX6-2FYGq9wSugj3PEP-2B1fBBPxIMddH6X5rGetMn4uu-2Fn98FGNNE78a0xCgtFK11QQgyJtAOhYQyJEGvr-2FiH82YtT0VrUHsLSljShWQfWR7necEdISEBdXPyc-2BWl79Mg-3D-3D">
<img src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390" width="65" style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
" alt="Figma"></a>
</td>
</tr>
<tr>
<td class="wi-100p pb-30" align="center" style="padding: 0 0 52px">
<img src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792" width="392" style="width: 392px; vertical-align: top" alt="">
</td>
</tr>
<tr>
<td class="pb-30 plr-8 fs-24 lh-28" align="center" style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
">
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td class="ptb-20 plr-25" style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
">
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsRqX3DohtZvgZMeU10GRNwW-2BVJmRBJYUMeDfDeka6-2Boot6Sffrd3QX9I-2B-2FGnShwijw-3D-3DrYDc_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP1-2FBrtG-2FgvrlVYuxbTmdKVHkZzm-2Bv-2FcSB1ktJ8SMhTIRmOdWcsClpIActda5sfulhqu5CSkeXbwZ01rQVF5YmwQ77x30vLGzpDCtRNNX5EEXS1fNEQyOrrVjHDX9-2FhuE50kEbVhh7aWwg0jQyezKT2GAgqccgkcojF1nqNSKIrxcIgiYfZZ-2BXr1vuryT4KuOhrB66GlGaIL6MXmNvyE4t-2BlINbpF7U9pBovqhy3zk-2BzMe4Hqu34r0irn3mpxpjKDeDmDEqSTeoStUho9mj5fW6TVtnxHhEwiz3sdp7Pmzv1OA-3D-3D"><img src="https://s3-alpha.figma.com/profile/1f495f9f-bfee-435e-81f6-a424a22bfa66" style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
" alt=""></a>
</td>
<td style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsRqX3DohtZvgZMeU10GRNwW-2BVJmRBJYUMeDfDeka6-2Boot6Sffrd3QX9I-2B-2FGnShwijw-3D-3DoN9f_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP1-2FBrtG-2FgvrlVYuxbTmdKVHeUpfROhoo7A4ss-2B-2BY8nI-2Fj1TOnrRat6QXXhGSAkSgYVXZrAZ2XFdier-2Bpw5zdrp3ouHyv5daFCh9KUUBivwVYVDbgw75kDO1d-2F7mdGQdMZlZxNuLqT1b5W-2BlZMCBCZU8l0pzf2w-2FWwzj7CbMIVSH741txlA8AfB3Rt-2FxlytAJj026lGEGcS-2FAMFogOyxqu9ENrpQA-2FJaSIPFKrWvLXZTaT2YvM05loD8-2FLIkGuNQyhWMYKJmOz05jLl4MNwoFBxPzzfZ6Zf5s1-2FCJu-2FILbgX2w-3D-3D">Juan Cruz Hernandez</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
">
Cant believe it doesn't have any text area component among text fields...
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table width="223" align="center" style="margin: 0 auto" cellpadding="0" cellspacing="0">
<tr>
<td class="active-t" align="center" style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
">
<a style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsV3ppVdm01Q7uDbV0KwU9ANxfoJGOeole00gCmsihLt4sbyfkEgtcX2xBvtTpdN3qw-3D-3DicM5_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP1-2FBrtG-2FgvrlVYuxbTmdKVHLCsthlNFgCS1Q2keEc1BqScnai4RsfAbMBQ2p9V-2BAX9cgaYxyhxa7a-2Fbqnr-2Bwm2jPYK4a9cmFS7yLZSQIYX3i8RUhMh-2BcM5QP93k2pK0zdd7k7T8K4h4dnyeErfBIrW6ciOEdjTteuRG13PHprZxO8yzOQX3oWVbnWebzulXFFi9JBx49ulx9DXpnWrSDIRYRbJ9PS3dShd9DEJLzyWzumn-2FghmMjqyOL7GZL61DVPq4-2F7Q-2B1-2B-2FWyX3MZOlAiILeJHDGy89kkiOnE8C4TwaTlg-3D-3D">Reply to comment</a>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
Answered on community!
