### ISSUE TITLE
I can't import MUI .fig file into Figma. "Unsupported file format" [question] 

### ISSUE THREAD

**Issue by pawlo8** [mui/mui-design-kits#376]
### The problem in depth

I'm trying to add the MUI .fig file to my Figma org Drafts but I can't. It says that the file is unsupported. I double-checked the file format is fine (.fig). I have tried both the desktop app and the web browser version. 
![image](https://github.com/user-attachments/assets/f3063f76-1bab-450c-b126-677a7f2d610c)

### Your environment

Windows, Figma UI3, Chrome, Desktop app 124.1.16

**Search keywords**: import, figma, unsupported

**Comment by adrianmanea** [comment]
Hi there, initially I got the same error, but then I tried importing the file again from the "Import" button which opens the dialog and it worked!

<img width="480" alt="image" src="https://github.com/user-attachments/assets/dc804714-ada1-475b-86cc-8fdf823c2924">
<img width="187" alt="image" src="https://github.com/user-attachments/assets/05591d15-6d11-4210-a473-9326ff2dd040">

**Comment by pawlo8** [comment]
Still not working :(

**Comment by adrianmanea** [comment]
Hi, have you had any luck importing?

**Comment by pawlo8** [comment]
Hi, unfortunately, it is still not working

**Comment by pawlo8** [comment]
"I have tried on another device and account but it hasn't improved anything

**Comment by adrianmanea** [comment]
Can you please send an email to figma@mui.com with your order ID and the email address to which I can send an invitation to a freshly imported file? I can then transfer ownership to that address.

**Comment by pawlo8** [comment]
Yes, sure. Thank you :)

**Comment by pawlo8** [comment]
@adrianmanea email sent

**Comment by pawlo8** [comment]
@adrianmanea Let me know when you reply to my email :)

**Comment by adrianmanea** [comment]
Problem solved!

**Comment by jazcid** [comment]
> Problem solved!问题解决了！

how to fix this problem？I have same issues

**Comment by adrianmanea** [comment]
Hi @jazcid , can you try again? Have you solved the problem?
