### ISSUE TITLE
Component of Text area: Comment box not in Figma

### ISSUE THREAD

**Issue by jaySmplCo** [mui/mui-design-kits#377]
### Related page

https://mui.com/joy-ui/react-textarea/

### Kind of issue

Unclear explanations

### Issue description

IN this related page we have different types of text area. Will we have the examples such as Comment box as components in the future?
![Screenshot 2024-07-26 at 15 14 50](https://github.com/user-attachments/assets/961dca0f-ec17-4d31-97d4-62a7ad4c9005)
![Screenshot 2024-07-26 at 15 15 43](https://github.com/user-attachments/assets/6749d034-66a4-49dd-8b08-c7eecdb5c6ff)

**Search keywords**: Figma Component Text area

**Search keywords**:

**Comment by oliviertassinari** [comment]
Joy UI in its current look & feel is being discontinued, we will resurrect it but we a lot more focus on it.
