### ISSUE TITLE
[Material UI][Icons] Different shapes in the same icons (rotate_90_degrees_ccw and rotate_90_degrees_cw)

### ISSUE THREAD

**Issue by fil146** [mui/mui-design-kits#380]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Go to MUI Figma file v5.16.0
2. Search for rotate_90_degrees_ccw and rotate_90_degrees_cw
3. Look at the shapes if the icons: you can find different arrow tips and different rhombus sizes in the same icons

<img width="1091" alt="Screenshot 2024-07-31 at 15 20 03" src="https://github.com/user-attachments/assets/5478e816-d1c0-4b9c-8567-a03960602cd4">

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: icon

**Search keywords**:

**Comment by adrianmanea** [comment]
Hi. I don't think the icon is from our package, it looks like Google's Figma file. We use different layer naming, but I think it's the same issue with difference gap sizes.

**Comment by fil146** [comment]
Hey @adrianmanea!
You're right.
Any ideas where to report the issue for Material Icons then?

**Comment by adrianmanea** [comment]
I think this is the right repo: https://github.com/google/material-design-icons/issues

**Comment by fil146** [comment]
Thank you! I've forwarded the issue there.
