### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Anthony

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#381]
<tr>
<td align="left" style="padding: 0 0 36px">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtscZQQyouBDG7hJei7w885fbx0m5vQjZ5QUiZCbhvoB32R30OfapoBwblQLXT6q-2FWPQ-3D-3D3y9D_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2PqYOAKjZnO2e9inhqm2Yn-2F7iBsKCVU2vsA4co1kn337fmIlhNMvFKOhfXW7JoooUz-2Fg3FUGFuxCdOIui2O2D-2Blpt2QMFWQ2-2FmMAXgGE-2BZ82A-2F2k00VtsoR472OCoNDMBMLZKfZ61ZpDnUn1MnkwjvWsTuOya7AClxz59NM-2FG9H7-2FVGgEFLCYiouWfwSXC9vJtH90kQiym7gOXBok9TKhazMrJWNoD6ZhdXAejbx4ZFjXhvYvPdveJblf0I8-2B-2B-2BvelmEF9FCQP9kd60DI4e-2F0D-2BkPbkTCYl7m9UZdQPTRORg-3D-3D">
<img src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390" width="65" style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
" alt="Figma"></a>
</td>
</tr>
<tr>
<td class="wi-100p pb-30" align="center" style="padding: 0 0 52px">
<img src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792" width="392" style="width: 392px; vertical-align: top" alt="">
</td>
</tr>
<tr>
<td class="pb-30 plr-8 fs-24 lh-28" align="center" style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
">
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td class="ptb-20 plr-25" style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
">
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2Byqtsfqz7b-2BFBtEQ-2BnB3He4lQkXHc6a3T3kCc0X-2BAdQgOQFKCk3dlJslAJssC-2BNwPHJk4Q-3D-3DwWrY_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2PqYOAKjZnO2e9inhqm2Yn0MOBLxBaZEV0Q7OJT5CP3o4bPwM5cpOHFyCx67p63Nc2VbeStWi8lmGCM9wk-2BI-2B1EgXDRbB7UcYXuNTPplsYGgvmXjyECMb2CB5UVBDUtA-2FLwhUcYYaItUsmIa0au9WQApsk8VxRLOEG37vofVEAsMOaS0XpS-2FWjpM6a19Lnq1DH9dh4mHkZ3LnwmG38MlSoBc6p4-2BfK4rPMplb-2BFRHLTRNu7PyMkzdmzdP2o9jkCryPoaUJ6HaPM-2B5zVKnbdij71sdHb1-2F10Kd7pDO62zc3pA-3D-3D"><img src="https://www.gravatar.com/avatar/668a9742a43ed92317c0fe2ba902051d?size=240&amp;default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_a_v2.png" style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
" alt=""></a>
</td>
<td style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2Byqtsfqz7b-2BFBtEQ-2BnB3He4lQkXHc6a3T3kCc0X-2BAdQgOQFKCk3dlJslAJssC-2BNwPHJk4Q-3D-3DekdH_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2PqYOAKjZnO2e9inhqm2Ynebmh0i1JCEjE-2Fxlh-2B1mbJVbJpoXX3UeZmHZt8bVAZ7qSi5h8KO33TxD3tC4sPXCs4pIwqcKqjdjGLs-2B9v69dRX6ptkbb3SkwCM8LEZ3X-2BM-2BI6OBYj32v3ib5ywFZIX-2F-2BFmYyIHTsd-2Fn-2FrRIfdeVC5Xt9nv553ZKN9eXPWrB9PwoFsdkv-2FiB-2B4yzck2AhLzEe-2Be6ZdwBeukV0dwYuxd8-2B3nDdQipkeSvxoVnmAAEFz6OCXdB5Hx9c9ZlGhiNQBCE5TerFhJ-2BE6iuOd-2BTd9sI2xA-3D-3D">Anthony</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
">
DataGrid seems to be build incorrectly. When the DataGirds is set to 10 columns the header cells no longer align with the table cells.
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table width="223" align="center" style="margin: 0 auto" cellpadding="0" cellspacing="0">
<tr>
<td class="active-t" align="center" style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
">
<a style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsdXbAhU9vBmt3kqoMVGAa1ENV-2FlMbCLWtERFjYvpTO9hNrubCilgj4N2FNiSAcQ6qQ-3D-3DsZxu_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2PqYOAKjZnO2e9inhqm2YnPMiKr7nUq9ZUXuXbCTGQ0ppnHFCeE2dc6gYGgI8eDpI-2FFXxqCF0lfn9QML-2Bp7xYgcQwlVnMAE9LVoVeQoiRAUQun8Dq56NlHWCtJmvnM6MlfPn87nEcKPMFilFKQ9cgCWEXcAZPS-2FYTcohSB24j6uold4zpEWAMZUr8mIW4I4WnHcb4OFt0HSzK25C1AA38q27rvXbIKLD1EJysTo3Bk6uuWl7HW6ovJXT62yWjPrVhGNbpEhZ5oSrveEIhsUu9c-2BKKEu0UuSm2SiefKXmy43Q-3D-3D">Reply to comment</a>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
I don't find the comment anymore, maybe it was a confusion as I checked and there is no such issue.
