### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Javier

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#383]
<tr>
<td align="left" style="padding: 0 0 36px">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsRJzybHX-2FTQYGX4cl-2B0lkzgA0GLX2018v96NnpX8sx7VnQuCT3UCg-2FoDmLWAxopXoA-3D-3DHCZ-_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP00TGoOBc-2Br0Gk2yZXVHts11Iex6GqmFOqJ9azDhwF7xUm0wgrxcKvdq6RkY51UTEeh5kpBN3Yrz-2BBSErdwE7flaEdRsCy9unC4MLOh48KfaHEw1WaldmHws1vYPWvGJp6HKGGwQorayn0SBYXtObdm6uQvwaElUT5-2BO9ANMAYvFzyZ4SCIz1ipHGchDIC-2FHhveWVS0emPi8EOx0A-2FKZLfxQbGYl6WONa0q-2FgAwxuPvImO-2Bxwupau8OZbF6k-2Bna6fkfpD-2FE1sGuTjCsvdiHK1bnqG3oVYbZLMLLYnU4jtNmog-3D-3D">
<img src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390" width="65" style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
" alt="Figma"></a>
</td>
</tr>
<tr>
<td class="wi-100p pb-30" align="center" style="padding: 0 0 52px">
<img src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792" width="392" style="width: 392px; vertical-align: top" alt="">
</td>
</tr>
<tr>
<td class="pb-30 plr-8 fs-24 lh-28" align="center" style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
">
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td class="ptb-20 plr-25" style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
">
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsRdBkP9w45-2FcD2ong9-2FXeJvHMMx1xfYqL1fblG-2BaQTydvmo9hsP0h0mW7rpvSt8dXg-3D-3DpuaL_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP00TGoOBc-2Br0Gk2yZXVHts1zzm3xc4eLabwXGA-2BDBiTVVdF3rqEsK3OkTow6V22sxYFxQGIEEyZjNoQzFd5zsaRDf3-2BfeeSAIpwXKMy-2BGRyZeqLQaGgtcYAdK5xsjeREx8Ls0hhmP15lMmwS-2BRA0RrFFcU8WZDxF78oPZA9tCfQZ7ynYgqqUFemXZQDZhPWi9SfNUKJiAK9Cy7s-2FjONvJAosXXa1dvcPytT1UJu97kj1hfUZZpKuqPOjU-2B430c0amGGARi7WS9NeIpjLIPv8aF0fwgU9L71IbJtEk62hfSMGw-3D-3D"><img src="https://www.gravatar.com/avatar/f9f2742ae3055099ba31026c871d1edd?size=240&amp;default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_j_v2.png" style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
" alt=""></a>
</td>
<td style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsRdBkP9w45-2FcD2ong9-2FXeJvHMMx1xfYqL1fblG-2BaQTydvmo9hsP0h0mW7rpvSt8dXg-3D-3DcQh0_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP00TGoOBc-2Br0Gk2yZXVHts19Bxa9pHPkjXHf5ujmr-2FY19iR48gCa15r-2F7AblwyAvk-2BU-2Bezk49kJuXvzoZXxmmVhPS1skyF04zRmHy-2B3VOpaTN8DHvUzKmhpCX-2B3-2BzXnClR8lctzs8N7MxSzQJUWbZdpe7W9dBvlZR-2BTs1ph0GX7WdtngYfvNmtTH2Q0jsJQBWHLlxGPYudyQGpZkmIxUBARE7-2FRnRRtKZ2-2BLp-2FwLzmxMF9jx1z0WT-2B5JhyZ9m16IThAga5vMWCCJusfuhsO38q2NdEM2NW96sJMWmrn1kK4Dw-3D-3D">Javier</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
">
Hello there!<br><br>I have made the purchase of the library recently and I am having some problems with the autocomplete component. I try to change the values in the dropdown menu in different states but I can never get them to show up in the preview....
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table width="223" align="center" style="margin: 0 auto" cellpadding="0" cellspacing="0">
<tr>
<td class="active-t" align="center" style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
">
<a style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtscSy672Kh3VlWq2KzzD8H2KuvD2Q3wZ8bcMdxqKht9A4L6itGJSfxQ6RuYF12CWkPg-3D-3DT4Gj_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP00TGoOBc-2Br0Gk2yZXVHts11YZ993P5QnoA8Sxvp0vw-2FWnDlI5wiAChhr2Dg3AE-2BK85ToBrtBcBAiVEv0oxHoAmyo3Zb2Ffrppkq-2BtkxXM-2ByD-2BKDVeWuxHGaDH8zY8qx6Ta6U9rwjpFQq2E02P0fVj5FIubCN5AWC9U5YL858QJ3QO35yTTHsKS3zJO-2BCmUQBuZ6N-2BdhZRw1GX58Kt7Rr9jP-2F6D4-2FFMG-2FLXfuBbA-2BfgG3NGn8iKWeh5CRkObmZNkTy-2F3EIgd7Jq-2FBoSpLfLCsvpS-2FqIyp6TIGU6sudllBb-2FQw-3D-3D">Reply to comment</a>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
Answered on community!
