### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Samson Eriksen

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#384]
<tr>
<td align="left" style="padding: 0 0 36px">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsYfHlpsj7vvdzd1HUdup29JauKPf-2FSXcm9PCKqluo2Reg9iO-2BY9e8XKhq4RCYC3EpA-3D-3Dimcb_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2s3ewCgZ5yHCWrvvTz4IkzDbWs8CUi1HDvuiMoI3mq28nzk0LDaNZfxXiKgWieSR5Ec7JIDt7MSflAYeuXKF68wKrfhLjwSWwc7R1gq-2FM8smhDKU9eIMDvQItMj4savS6uA7Cq-2B-2BObrprGZ7WvDR1kHCq4Iz21lf1GJd6R4Gcdlh2v6usAVBGyGlzAKHw17ZFJ4DBuILBGdeYNG-2Fqc2AXmmN7crlf8uFI2RH9I3-2BjLqGEnuxcaOWcvP2lyV8sBxQmSyC7IOg-2FQl1pVVuZemNqViCLuh7tKdh69Al0jNB1hNQ-3D-3D">
<img src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390" width="65" style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
" alt="Figma"></a>
</td>
</tr>
<tr>
<td class="wi-100p pb-30" align="center" style="padding: 0 0 52px">
<img src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792" width="392" style="width: 392px; vertical-align: top" alt="">
</td>
</tr>
<tr>
<td class="pb-30 plr-8 fs-24 lh-28" align="center" style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
">
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td class="ptb-20 plr-25" style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
">
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsenaKklur0-2FXHaYlJVn-2FHkgSfo5-2Fv8Qszwflb76y1UGgALC-2B-2Bt8sOEZHNw67L29jhg-3D-3DPeCV_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2s3ewCgZ5yHCWrvvTz4IkzXS-2FyrVebhJw20pWImsRBsuHIgYo5BxMW13ewNUyGZ3osiOUaVEWvkWw-2Ffb3dnY7mMPPUQJqy4YUU-2FPTcw4PzWqAT97syDJRhl92ufjQkezBiVsdvV38uhrmUNfldAy3ngNKlM2UuhAYwPRlav34Z5nvOSScnbLEL9m6WnAdnRyj9Ocat9Q7unDPwCehRsfO6zUAeRWQo1-2BEOlKsz6CsU508A5fm1wO8MWaOexpC1RM15v9atUmKHLrZP-2FuEye-2F31q7EXPnG-2BJuxK63rk17FBFg-3D-3D"><img src="https://www.gravatar.com/avatar/6aa442a74c7829d14e2bea6e7a413946?size=240&amp;default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_s_v2.png" style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
" alt=""></a>
</td>
<td style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsenaKklur0-2FXHaYlJVn-2FHkgSfo5-2Fv8Qszwflb76y1UGgALC-2B-2Bt8sOEZHNw67L29jhg-3D-3DhnF5_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2s3ewCgZ5yHCWrvvTz4Ikz2J1eB7aPbXgP14gUn1eV6yjMX6IbynZn6dQH2e-2FrYUUg1z1mb0r-2F5hzB8UxdkcBbtxcCFZflXflQaGg9Z5E5VUJM8VrKM6DP3DqTRFyGGv4wstNP3b-2FlctGSVoq-2FYnU7MrneqQMt7TEz1AqfUK3eyknzwn8NV3bfSeTDmu-2FGSNliANSO73MkJRCfWNFdF9alkeuY-2FqyVUJK2NhipsFPJI1jj1Q7G0cMewr1ihqy3ZYbdaX-2FjRNKVK34cRwnQgUZLVgoc95bMRGwBtajFQjlkEA-3D-3D">Samson Eriksen</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
">
Hi, earlier today I opened icon library for "Outlined", but when I try now I suddenly get 404-message.
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table width="223" align="center" style="margin: 0 auto" cellpadding="0" cellspacing="0">
<tr>
<td class="active-t" align="center" style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
">
<a style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtseCQloc5i5TsPdzOPFQi8o8dzWNc1Eax0mkINQLhMWv5BkWmqUigh2MimBRxqZ9azA-3D-3Dbi6L_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2s3ewCgZ5yHCWrvvTz4IkzRKm2gDN2cD-2FiX9S-2ForrKeiTa07OdHCYuwFHZVixn0FlBVChMfP9XKbY-2FjpyJNGcKTDE8DfUvmLbm2-2BCungKIEwSRz4w037SzFjFRMz9m1eZG8T6-2FfeLuOXCnx1a9Zp-2Bjl9orvcEqjJEqElAJeOoGF-2BtvQrGk3mtahQ4TuEg1dzNNz3BtGkz-2Be5sF9JeZGvvoBbHV9K-2BonxLyjOqrif3kTS9roH7yGGtH-2FSB6haoxT8UP-2B-2B-2FzOYcT-2F8pZbi5yiwT9E1uAoSXd9jXxYsSaQw7VTQ-3D-3D">Reply to comment</a>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
Hi [@samsoneriksen](https://www.figma.com/@samsoneriksen) were you using the version 5.9.0 of the icons? We archived those today since it was 2 years old. I have now restored it. In the future it's best practice to duplicate and have your own copy to have control over!
