### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Samson Eriksen

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#385]
<tr>
<td align="left" style="padding: 0 0 36px">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsXX7kSPJCQ7QadSDra8D6J4B9dyi3K3asX52wdVn91tGtvd6tZn52DzH2s-2BfZGHx9w-3D-3DmE6f_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP1jRvH1qEhDs0ZbOActM2wCV3HoYc73O2e5Dh-2BAW209Ia8y-2F3LF8gmjzLVkCeUPQAXzfcXqiEP8b2kK60CZrcgIxSRhy-2F-2F0m5GHpL4cxJ43p20W-2Bra-2Ftyc5Wr7s0pUYoGCd8x-2BBvN05x1Leb2ULfvVAZUikuwdctbXjWmMsl16ZI9-2B0TIE7Iis4HvAMg1doi9YX3OJRcqr7ulDFevRzosjjWURe1dlRGOY12HILl7oNu1VTBQZaXhkpIMLn6hAtxTBM4iCJklb18-2FFguJZGsvp-2Fldccx3SxKrXXl1JIMikCog-3D-3D">
<img src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390" width="65" style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
" alt="Figma"></a>
</td>
</tr>
<tr>
<td class="wi-100p pb-30" align="center" style="padding: 0 0 52px">
<img src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792" width="392" style="width: 392px; vertical-align: top" alt="">
</td>
</tr>
<tr>
<td class="pb-30 plr-8 fs-24 lh-28" align="center" style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
">
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td class="ptb-20 plr-25" style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
">
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsUHzRHnqzNn8iFXQhl-2FMa8PV5snRMHT-2FX4O8C6t4F-2Bgar9mhnqnykFPRqSCYYQT81w-3D-3DWurd_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP1jRvH1qEhDs0ZbOActM2wCpxhrpcbs0RzfkGme4PuSG3VtvXntQTgJc-2Bt0dez6YfgL2NLhaRk4r0zjkbtpFjKUX5oatp5f3FPATGbhgcw8C-2B7P7SWHqYv2yJbdiseZeO5UHZG1LUqWL8t-2BBwdah5S28w9vSkcnNqEV6UEm6rUPN6T-2FoPgOIQUhoJOEqWnb8mf1inggnEviDY7iaF7lhV4JQDZ-2Fft0gEtuKtyhOcZKfxjMQ1WNUq2qEa1P-2B0g4wH3Flg5H3tBgOrCMRZecXRvy2vR-2BaGaA4-2BM82C6VFyvUXbA-3D-3D"><img src="https://www.gravatar.com/avatar/6aa442a74c7829d14e2bea6e7a413946?size=240&amp;default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_s_v2.png" style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
" alt=""></a>
</td>
<td style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsUHzRHnqzNn8iFXQhl-2FMa8PV5snRMHT-2FX4O8C6t4F-2Bgar9mhnqnykFPRqSCYYQT81w-3D-3DFu_v_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP1jRvH1qEhDs0ZbOActM2wC76OE5CIKYiqhNEZI-2BqauJmu3bNwakL6YYv3HC-2BZOkOpcMmLZz463aaREZukAOfDoZXawTKxW7gNhycYi6-2ByxXecHIDQs9L3CuKDA7hnk99-2BufahfT8fCFlt5wORCJzxuDBszoH8BqEvNdNMIAHbobbf4wf2uf9WaWK1V-2FXlmGxSq0NOCNjeheiZdQnlcbYkzUP5sIvzyQXUGTQbg-2FyeeetfNAUkCG5SAeCjZF39YYzVuwp1j32j-2BoEHEJfxSeqWaYh0nimhWq9fF-2BjpvtCHPGA-3D-3D">Samson Eriksen</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
">
goadrian Wow, that was quick action :) Works now. Thanks!<br><br>Yes, I used the 5.9.0. What is the latest icon-version for Outlined, and where can I find it? <br><br>PS. I still use the 5.14.0v MUI for Figma ...
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table width="223" align="center" style="margin: 0 auto" cellpadding="0" cellspacing="0">
<tr>
<td class="active-t" align="center" style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
">
<a style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsUIW5oErs2HDIg071CK8yhVpLvT2WM9j7VMfNIb77r5svMC-2FcjE5Eu5Fku5b6ZrAOg-3D-3D3htL_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP1jRvH1qEhDs0ZbOActM2wCk4kKWxxiUa-2B73Jpziwo-2BAokLkjz-2BLa8fVbHezwzzlX2lSqYNTchNcQKt-2BbZ6179GuTC53k8Axef9jGCQkDIGcFPM0MdBxnb2nRMRC2LWnengNLkS6dvubSvswqw-2FFOeI3Pyv1m9AFAwXnnhAX-2B1QSHkQfZDgy2yxoosse1LAfKyTz9tlNiKKE6Mc7AGw1QkfqKHh-2F8vxxdwWcxcXFGvtzVch7phsG7KLb0wxkxlUXroYPgFutSt2jFYngK6LOziOzJsQ-2FeLRoyuDsHWEhit8zA-3D-3D">Reply to comment</a>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
Answered on the community channel!
