### ISSUE TITLE
How to resize pie chart?

### ISSUE THREAD

**Issue by x-merlin-x** [mui/mui-design-kits#386]
### The problem in depth

I am trying to make the pie chart smaller in figma. Despite entering different size values, the chart itself will not shrink. 
I am also wondering how to add more then 4 elements to the chart in figma.

### Your environment

MUI for Figma Material UI-v5.16.0

**Search keywords**: figma, chart, pie

**Comment by adrianmanea** [comment]
Hi there, we provide the base elements and some examples, we recommend detaching the examples and build your own charts.
