### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Esther González

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#398]
<tr>
<td align="left" style="padding: 0 0 36px">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtscIQNIz9pzl-2BHeDMrvUE-2FA3qbUKONdT8BVgTf-2BBI1j2861PlgUkN9ALjChPTxX4gfQ-3D-3Dw2D4_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP35f4QyD0Sl2xbPFbjn4ZPth9EEYEgyTtEV8LwHarDyWOtkWXXrjYedgfN-2ByO4T3S5qG0hZdtPKxMPj8F528uKS1o79B7d8n-2B-2FuXdIl3qNF3GEGlzA3vdb-2FhYFMtf-2B47VvdRVSOq01fOmN4DWHlpxQLsc6hZ3OVvpSXN2YwvX4FIUxE3I5X4Y2l0Q2BnxZKIgkZdrMmo49-2FHDY6UV328iBh2Sdahkw9sumeH-2BJZOzBy10Ne68gNi5j0v0VlsEo7SAurOiW5vttr31ZGSbVrMC6lIPcfWCAdRe56gQ2a5UTq3A-3D-3D">
<img src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390" width="65" style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
" alt="Figma"></a>
</td>
</tr>
<tr>
<td class="wi-100p pb-30" align="center" style="padding: 0 0 52px">
<img src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792" width="392" style="width: 392px; vertical-align: top" alt="">
</td>
</tr>
<tr>
<td class="pb-30 plr-8 fs-24 lh-28" align="center" style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
">
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td class="ptb-20 plr-25" style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
">
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsYgpGMpUhoPA5tLXV6vkAgEaVy0RfqPiMzOyXlV9fW-2F2ciOJ9DdKZbGYTbdlC8jJ-2FA-3D-3DRK-m_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP35f4QyD0Sl2xbPFbjn4ZPtv38tI0C5dK2PYcImYSr8dzB3sAb1KVniYcqpLa2CvX2UPrVMGt4yW4Sz8uKWC-2BSVbasdjowBu6ZbvpKRHhydFhm-2B9BiacSAUey3J9B1w9LClLjsYbVgJ66RAsOs4Vro-2BAS7NsL6xscaWkkTCr9AOzBG5kQCG3TENb2yQ9xYRlwOZ4oE9Fx-2FWIPgqfNnmRnzyp-2FoxyeeB7hz1vBItyyPxMHoGbMfbtRug9ub6dvxtJ1amXUYk2HPy3zRqVr0FoAIHANSnILSdJ89ufF8ENqCCfg-3D-3D"><img src="https://s3-alpha.figma.com/profile/c47130ac-ff58-485e-91b3-918a6ac774e4" style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
" alt=""></a>
</td>
<td style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsYgpGMpUhoPA5tLXV6vkAgEaVy0RfqPiMzOyXlV9fW-2F2ciOJ9DdKZbGYTbdlC8jJ-2FA-3D-3DHPzB_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP35f4QyD0Sl2xbPFbjn4ZPtIOr7JLdadjGMWk5KGmEvkU-2BLMwUoM-2FhXRnmVKD-2BrbNGaVIsQ4It3ChLo0EQzqDQRVxYdXUGkscIyATZArM0HnPfZGf6c7ZXRbOL8trV9s3vd8c2O4YSg7f5jX2jaMP-2FmUPpKXlExFZ4hJIRLnmRnoMXEB89d0jTf38i6hfIJsDqzAu3B1SQNcUoudqNG8YtHLZpyY7r9wCPZry0Lon3bz5CciR0VsUtHiDH6I7pKdIHO7zw0ZyDD5a3QR4P8XBKxJ9NyZP-2Fy0Pfifyjjo5filw-3D-3D">Esther González</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
">
Hello, I'm new to Figma, and I'm trying to pick the library color for my project (to change the button color and stuff), but I don't know how to change the color variables. Can anyone help me?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table width="223" align="center" style="margin: 0 auto" cellpadding="0" cellspacing="0">
<tr>
<td class="active-t" align="center" style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
">
<a style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsSOs2iTa1M2VF5e8i4XqL3pU3HAKbUFbnXy8Z9iwHhx9N3g33pEbf-2BCKy5npuejjOw-3D-3DCvSg_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP35f4QyD0Sl2xbPFbjn4ZPt3w4NIJRkGHtNIxrmen12W10TojCUkuxNBj-2BtcNPvXEq-2FKi02KbjnsYAMv0GLVjv9vcX1Q97dZxwztQT0cDrs60PF5OU9rvdzmP66pZ6BWDlT3nxONmlctWWQ-2BnuMtOjGZ78P5-2Bvzj79wKqdFMyzyP4hWbi2xd2PCjTSOZU4XEo4lE0MPddqtO4MFcsIoeBxUzS6h8hLxfQ9atCuA19gZV6ZgmqLc-2BCFrPf-2Fayj27Kdo2QBajwz-2FOTVpIPgI12E0oy5GnIu-2B7b65TqBzOD0A9-2FQ-3D-3D">Reply to comment</a>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
Answer on the community:
> Hi [@esthergonzalez](https://www.figma.com/@esthergonzalez) you can find videos on getting started on the product page https://mui.com/store/items/figma-react/
