### ISSUE TITLE
[question] Updating Figma library

### ISSUE THREAD

**Issue by amyfourie** [mui/mui-design-kits#400]
### The problem in depth

I purchased MUI's Figma library earlier in the year, we updated the colours to match our brand. I have just downloaded the latest version and was wondering if it's possible to update our custom version to the new version or do I need to rebuild the colours in the new? I hope this makes sense! Many thanks

### Your environment

Previous: MUI v5.15.0 - Material UI v14.12
New: MUI v5.17.0

**Search keywords**: update mui figma custom

**Comment by adrianmanea** [comment]
Hi Amy, unfortunately you need to re-apply your overwrites and use swap library feature for quicker replacements.

**Comment by amyfourie** [comment]
Okay, thank you for your help!
