### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Cameron Dunford

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#401]
<tr>
<td align="left" class="pb-32 darkmode" style="padding: 0 0 36px;">
<a style="text-decoration: none;" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsRtvSapcHtz41OPeuINElITty-2BSnrvOfp-2FvVHk8S-2BxI8CGON9v-2B3-2BIFT80MVweozFw-3D-3DfGOU_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2-2BHY5Dik9w7CNzl3qoPpl2u-2BIRFDGyGepe-2FwJWRJ0tewNU7A3h5uf5C1XbUd-2B-2B7j8ZLiunUHXVIzNsn0r-2F4dw-2Bn4vZI-2FXiMDt7znvrYIlzvkyRUf9BieX2goE39N4aZO4cwHM0IqvkY3k5JwY9apWsHNE2rXUl5LACZ-2Bco3VI4-2F4V-2FGGkkdz8HjlwQ4h6DL07WLBMJ95cn2AihT5it1XiOQgc98nEx0plrJjykE3xJUUE3qmbpTs68RdXkMdjk3ASSG5FaWf5kOPPSFr3zicMJ1kztk3vD8yCuRYf-2BLaIswgrdiY1fS2DFK44sCD-2Bn3fU59vIO5OYus8nK9UHT-2BfgJ">
<img class="light-img" src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390" width="65" style="width: 65px; max-width: 65px; font-size:22px;
font-family: 'Whyte', Arial,
Helvetica, sans-serif; vertical-align: top; line-height: 24px; background-color: #ffffff; color: #000000; text-align: center;" alt="Figma">

<div class="dark-img" style="display:none; overflow:hidden; float:left; width:0px; max-height:0px; max-width:0px; line-height:0px; visibility:hidden;" align="left">
<img src="https://static.figma.com/uploads/c2698d9a70dc8fe5ec7bc50d0141f831bf2ab2df" width="65" style="width: 65px; max-width: 65px; font-size: 22px; font-family: 'Whyte', Arial,
Helvetica, sans-serif; vertical-align: top; line-height: 24px; background-color: #ffffff; color: #000000; text-align: center;" alt="Figma">
</div>

</a>
</td>
</tr>

<tr>
<td class="wi-100p pb-30" align="center" style="padding: 0 0 52px">
<img src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792" width="392" style="width: 392px; vertical-align: top" alt="">
</td>
</tr>
<tr>
<td class="pb-30 plr-8 fs-24 lh-28" align="center" style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
">
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td class="ptb-20 plr-25" style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
">
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtscjnwE2GOyqKBrX4FOAikrEN6RIqyQkbgbJH7CEA1jyk8FHR7-2BHDP1v9suHuTlg-2BrjDaw3AiRetdajT5Wsueiw3iHJDaZtdhqeYAhzAjffqyNKrf_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2-2BHY5Dik9w7CNzl3qoPpl2VF0IEBXU0HwSKUGZ-2BKcXyWpAtZXtagCOKot5bL4UhYs1rOzz-2Fx4wqz99cwwcGD2UaXMdTN31lROIDrGzbxgyCkQjRUopfgBjhSFitO3MdscPLQVI6r-2B2Vx2i7qI-2F3y8juyBckOO7GzjesbsiAeiSyBV3SvHthoac5U4p9DSd6TAgXmb8Uo-2ByM4BK9DennJZhXK-2FGcdh3PSBhhsE9C4sPThRETHA6lEogQXOvBpnZdDy2GBhnrg-2FXc-2B02pE-2Bj-2BTLaoMV2o9wRMndMQODjW8ljzx46toy47Lt4lCCe5UywH9mBFFWJUIns74TMnFA-2BiHL5"><img src="https://www.gravatar.com/avatar/d125e7e0cd4a4bd4d918296bdeaedf77?size=240&amp;default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_c_v2.png" style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
" alt=""></a>
</td>
<td style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtscjnwE2GOyqKBrX4FOAikrEN6RIqyQkbgbJH7CEA1jyk8FHR7-2BHDP1v9suHuTlg-2BrjDaw3AiRetdajT5Wsueiw3iHJDaZtdhqeYAhzAjffqyjGQL_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2-2BHY5Dik9w7CNzl3qoPpl2hhfLrd8fsw9zKn1Fii6EeTJQ07B0Tu9nfANqYx-2F04QdAVWE-2B-2Bfshv4m5g9V180a9xF46wb7apqcnwKn01LvG-2Bxh1-2FJw4rkkvW23ChdSQ9nMDxvYWd6D754rsdu5mn8fOc1y4zk8-2FvpEbwzXW6GxIPT-2Bw7QfI9MsI-2BO3RmhZHAYIMsMmYn0YzIZZEyabDj7W-2BH79KXCBINOnTv66NazdIv3Y0wWIB-2F4XEULxd-2FTzbuA9eEQhXbKwbxnTlwekz0GdZb3HzQK4MIptHCxzMVcaXxgk6SV1dcIKCEnX96jSR4iyR8DnuN4yUAchaxQC-2Bbufv">Cameron Dunford</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
">
Are there plans for a v6 version of the Figma Kit, consistent with the current code package release?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table width="223" align="center" style="margin: 0 auto" cellpadding="0" cellspacing="0">
<tr>
<td class="active-t" align="center" style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
">
<a style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsUBpC0Pzg-2BOd091LgqIhUpubTlMC9s7AmMJRtUDeRBMz24Q1z52sjz4c6asubGEPbtOwKkXJLAkfW-2BTe1sY7xVc-3DftP8_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2-2BHY5Dik9w7CNzl3qoPpl2v-2BB-2F1-2FT0wxuuvwz7ayTBVuG5jvuBdLa-2F0NmbIfdhowdenI4P1v0-2B1ObGjXOPy13ttqwXy4qJQELm3YhukPBk-2FhHSBFRUM12hL8BpaZ2rD7qZAt9VxJFVxZBZ7o7O18wJ4X7jNVAeIKlTi64oe0O-2FPJSoxkQU-2Bpjxoj0iIR0pRs84YHPrEYAEuqxyS-2Fmt6ZBQ1SJ6hBGnRtG4e2gZiQmSTJ1uVMJnDLjy4Hh6NUonWZj-2FU7eJENj0NyU8gkaHrZydwF8vA7pEwDzOJyk7bm0tY07r6zYNEiP1JzzN-2BGjhrAWwBqT7UYF3mTG3j35oHTdS">Reply to comment</a>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by oliviertassinari** [comment]
Answered.
