### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Remco Bakker

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#402]
<tr>
<td class="wi-100p pb-30" align="center" style="padding: 0 0 52px">
<img src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792" width="392" style="width: 392px; vertical-align: top" alt="">
</td>
</tr>
<tr>
<td class="pb-30 plr-8 fs-24 lh-28" align="center" style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
">
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td class="ptb-20 plr-25" style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
">
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsR1AYFQIbf9qSu-2FAWJt12hkBSeylHj7ZgOhUlQ3ZGNuPYsngx4uIGDZ5ZKwUJmCePaxzunxzxPTaJNmre0N9tHQ-3DepP2_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP3FqJyI0rtc6kyY71HoxtUGj8BhuZfbH8fIMwTHTcztDI5pnWziN4m7H7cj6vhdk74dEN-2Ff2JjiLm6f-2FnKGFbFIyvv2fEqh-2FyaLE-2BbOxLbStaRsBWrDa-2F-2BMwU1T5XP2d-2FDDWEfBZqlM4I5H2m4do7YzJFzk-2BKkVbzZ1rIe1mZhg2JmbshTTTX1yWniMvNYFwIgIA1-2FZAPkAd-2FKbm6ZB7ADNOWh5WFAiJ7wmdaHBYtdpMpCDk-2BJQbVOmJmgUaPdynxCRSggqSgOTU2nNlkeWWxbXDuEyjanLcCb0NQ-2Bn6oniUerDKngvbJkazM76WcxQEDkb-2FqrgutLXnFUQLgdmo661"><img src="https://s3-alpha.figma.com/profile/a222ce45-de36-4f5c-85b6-e3d1b44bad50" style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
" alt=""></a>
</td>
<td style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsR1AYFQIbf9qSu-2FAWJt12hkBSeylHj7ZgOhUlQ3ZGNuPYsngx4uIGDZ5ZKwUJmCePaxzunxzxPTaJNmre0N9tHQ-3DNiBy_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP3FqJyI0rtc6kyY71HoxtUGPVHW7jz7uanBSsxdmhyaxCcI26F4jQX0x5XTKX7qc3ElICSJPr8kO7i-2FtGXFxPmB2Y3Y2o6XEqnVEoj1o0GiOnJHnl6xP8fIj8u94I895u-2FGwsKlDR0p8sfLervKGx8van1p1FazazT4RG7TLuMfXnlSIKZxOU8Hxbl4k8ws-2FbLvxgHRqO8wM3dCZBji-2FWk1hLkEV-2Frczuk1fH35TwCwiFR6-2F7EPBRk5XkcvAH1URIpM1Qp2wtJXIpIW1urbNcgcxwAaQ6ue79erzT1fU66FWBul0SF-2F1W0ceT-2FxOhcpsJNKtXzLeYAiVlKokIcz8vpP">Remco Bakker</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
">
Hi everyone, if we would use MUI as the DS for our new products, how easy would it be to customise the look and feel of components in figma? Is it built using variables or adjustable tokens? Is it as simple as applying a different corner radius to a component in figma and telling our FE guys what the change is?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table width="223" align="center" style="margin: 0 auto" cellpadding="0" cellspacing="0">
<tr>
<td class="active-t" align="center" style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
">
<a style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsfGeceekr9wEpZcvD4gQf26wJ76YphHv291FA4nDjDeZeAiUv0uNGpcX6TOSadlcierKiJcsvT20oUPdCGLCiwI-3DHzO1_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP3FqJyI0rtc6kyY71HoxtUGAJhgJ4175jrWXLRxNDlyrZm0h4LOXjYGLrbRW-2F49U50qjDJWNbiFAVBJB-2F7Ofph40gJklA3TizFkWZJgq0WRyqzVcUApUYRNLw7k42mwIKgup4gAwGnvR5AtJYUC-2Bq6Yh7JfxAlbYxcRYIfhQ3Fu9epXZK-2BzibIOWX7JpRvNn3Cipkbqx1CDpg1GxuKTq9lxvz5xWc4M29kNpwRf-2B8Om2563kPbDSCCRbqXxLregBGJWC2oxcbh3fm7KDqs7tJHv3NTYeDq69ZGDB4NAa7kWUNZNf5eEIC0sf3wqMcH0aws1EM708N0RrjJamLfNI141">Reply to comment</a>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
Answered on community:
> Hi [@remcobakker1](https://www.figma.com/@remcobakker1) yes you can customize the design system and then communicate your changes to the front-end team to apply them. For basic changes like border radius, colors, you use our plugin https://www.figma.com/community/plugin/1336346114713490235/material-ui-sync
