### ISSUE TITLE
Update Figma UI Kit Material UI v6

### ISSUE THREAD

**Issue by camerondunford** [mui/mui-design-kits#403]
### Summary

Are there plans for a v6 version of the Figma Kit, consistent with the current code package release?

https://www.figma.com/community/file/912837788133317724?comment=1423711746113044288

### Examples

Figma Kit v5.16.0
https://www.figma.com/community/file/912837788133317724

MUI Material v6.1.1
https://mui.com/material-ui/migration/upgrade-to-v6/

### Motivation

We would like to use a consistent version between our Figma UI kit & our code dependency.

**Search keywords**: Figma

**Search keywords**:

**Comment by oliviertassinari** [comment]
Yes, we plan to release a new version of the kit next week for Material UI v6. Now, mind that there are no visual changes changes between Material UI v5 and Material UI v6. We have been mostly focused on solving technical problems. For example, we removed IE 11 support to lighten the library.

**Comment by vkinnune** [comment]
Hello Olivier! Is there plans on releasing also an updated version of Figma MUI sync plugin that works with MUI v6?

**Comment by oliviertassinari** [comment]
@vkinnune This is tracked in #397.
