### ISSUE TITLE
[question] General question on purchase expiring

### ISSUE THREAD

**Issue by Lbm2439** [mui/mui-design-kits#404]
### The problem in depth

I ordered MUI last november and we are using this in Figma to build out our design system and then creating the components via React to use in Storybook.  When I go to download the latest version, it states that my order has expired.  To correct this and NOT have to purchase this again, can I simply pay for a license to reactivate it or do I have to repurchase this annually?  

Also, if we have already been working with a purchased version and made style changes, and I update my figma to the latest changes, will it override any style changes we have made?

### Your environment

version 5.14

**Search keywords**: expired

**Comment by adrianmanea** [comment]
Hi there,
Access to updates for our Figma licenses lasts for one year. If you'd like to double-check the expiration date of your specific licenses, please feel free to send an email to our [Figma Team](figma@mui.com).

> can I simply pay for a license to reactivate it or do I have to repurchase this annually

To continue accessing the latest updates after the initial year, you will need to renew your licenses. This involves purchasing new licenses for each designer on your team.
