### ISSUE TITLE
[question] My Developer can't find the colors from "Components" collections from the Variables. (See attachments).

### ISSUE THREAD

**Issue by Oscarf77** [mui/mui-design-kits#406]
### The problem in depth

After h
![SCR-20241021-gqp](https://github.com/user-attachments/assets/8ee2218e-d7e2-4fa3-8d9d-8c820424ffe2)
![SCR-20241021-hsl](https://github.com/user-attachments/assets/d996bcf8-0c0a-4570-8f8a-482e603e12ec)
aving A discussion with the developer they can't find the "Component" with all the variables/color tokens in the list.  One example is color tokens for Inputs.

### Your environment

using 5.17 Figma

**Search keywords**: Components collection

**Comment by adrianmanea** [comment]
I'm sorry I do not understand what "Component" are you looking for. Not all components have a token assigned, only those who require it for changing the mode (light/dark).

**Comment by Oscarf77** [comment]
In the screenshot from Figma there is a a group called **Components** from the Palette Collection. A lot of those components are using the Material Colors like Grey or Red but other components for example, `Inputs`, have a color token named  "EnabledBorder" another example the` Chip` component has a color token name "defaultHoverFill" #000000 12%  If my developer wants to override the colors they can't find where these colors are coming from.  If this doesn't make sense let me reach out to the developers I work with, and maybe reframe the issue later. Thanks!

**Comment by adrianmanea** [comment]
Hi Oscar, all the colors from the Components group are Figma exclusive tokens, these are not meant to reflect the actual API of the components. To find the specific class you want to overwrite you have to check the API docs of that component.

**Comment by Oscarf77** [comment]
Thanks!
