### ISSUE TITLE
Version update

### ISSUE THREAD

**Issue by davideatsol** [mui/mui-design-kits#409]
### The problem in depth

Hello, I joined my current company almost a year ago and at that time they already purchased the v5 version of the kit.
It is fantastic but I was wondering if I can somehow update the components or we need to purchase the new v6 one to be up to date. Thanks!

### Your environment

MUI for Figma v5.15.0 - Material UI v5.14.12

**Search keywords**: versions

**Comment by adrianmanea** [comment]
Hi David, to check if your access to the MUI store is still valid. You can verify this by signing in to your account: [mui.com/store/sign-in](https://mui.com/store/sign-in)

If your access has expired, you'll need to renew your license to download the latest updates.

**Comment by adrianmanea** [comment]
User hasn't replied for two weeks.
