### ISSUE TITLE
[sketch] List item text only nesting

### ISSUE THREAD

**Issue by adrianmanea** [mui/mui-design-kits#41]
## The issue
List Item, Text Only variant not adjusting its padding if nesting level is changed

## Solution until next update
The weird thing is that the rest of the components work fine with the same text properties so this must be a Sketch bug. The simple solution is to just copy and paste a text style from other components.

## 📹 Video
https://user-images.githubusercontent.com/5917515/145779374-aa8b6168-abeb-4f29-a4be-c6ec0dcb14b1.mov

**Comment by oliviertassinari** [comment]
Fixed in v5.4.0
