### ISSUE TITLE
[question] Enabled Tab in Figma, Changing Vertical Bar from Right to Left

### ISSUE THREAD

**Issue by mj-koanix** [mui/mui-design-kits#413]
### The problem in depth

I would like the enabled Tab to have the vertical bar on the left side and not the right. Is there a way to do this? Thank you!

![AskMUI](https://github.com/user-attachments/assets/701ad465-bc63-4b2d-a716-6f3060d5bede)

### Your environment

v6.1.6

**Search keywords**: Tabs, Enabled State, Figma

**Comment by adrianmanea** [comment]
Hi, you will have to create a new set of components for the border orientation to the left.
