### ISSUE TITLE
[question] [Figma] Is it possible to add a component into the main content of the Dialog component without using Stack 

### ISSUE THREAD

**Issue by amyfourie** [mui/mui-design-kits#415]
### The problem in depth

When placing the dialog component into my design in Figma, I create a design but then later want to add an additional component in between components I have already added. When pasting, the component always falls outside of the dialog.

### Your environment

MUI for Figma v5.17.0

**Search keywords**: dialog component figma paste

**Comment by adrianmanea** [comment]
Hi Amy, the <Dialog> is designed to be detached. It's much harder to create contextual components to replace into the <Dialog> instance.

**Comment by amyfourie** [comment]
Sorry, are you saying it is designed so when I add a dialog I should detach the component to then design what I need?

**Comment by adrianmanea** [comment]
Yes, that is correct.
