### ISSUE TITLE
[question] How can i redownload the MUI for Figma v6.1.0 - Material UI.zip

### ISSUE THREAD

**Issue by vanwebbs** [mui/mui-design-kits#417]
### The problem in depth

I need to redownload the file that i purchased May 12, 2023
[MUI for Figma v6.1.0 - Material UI.zip
And does this file include all the new updates you guys have made or do i need to repurchase the new file to get the updates?

### Your environment

Figma v6.1.0

**Search keywords**: Redownload

**Comment by zannager** [comment]
Hi @vanwebbs,

The license is perpetual – once the kit is downloaded, it can be used forever. It's a one-time payment with no automatic annual subscription. However, access to updates and support is limited to 1 year from date of purchase. If after 1 year and you wish the get the latest updates, you can renew your license at a discounted price.

Please reach out to sales@mui.com for the discount code or if you have other concerns related to your license. Thanks.
