### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by bodas67661

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#419]
<tr>
<td class="wi-100p pb-30" align="center" style="padding: 0 0 52px">
<img src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792" width="392" style="width: 392px; vertical-align: top" alt="">
</td>
</tr>
<tr>
<td class="pb-30 plr-8 fs-24 lh-28" align="center" style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
">
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td class="ptb-20 plr-25" style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
">
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsTJiJVSP-2B84x4PI-2BusgunwhTMOjAuQIQkvchZx3fRcLqv3lXGe0w6rLPxf6xUemsfo7oGUxqQALZqipCdOYFFtw-3DrZeb_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP0t21CDxLvfbGQkjEvjcHwGpmKZcl5OtbbkIwmyLGsT6P3stBzsG-2Bk-2FJfpZw0tjTu2Jv4mnqrmdgdaIBW8V5wVi3wWVyIjiPnHOiIXRkuREWTy18gKWyXoXpbKZmipyyuHf1-2Bxx1XyAcS-2BGrJPZTXlMoO3mv1NSGz2MHsO5D8FpT8udcAbymTbmi5wXvoGdTJtC-2Fz6c7KzILbeNpNTQCXDfOodFXkLPYc4mO4B2cDAcMF-2F8D-2FS0GVkN-2FwxoGSKILjmJzG1CorJsDCgeoDJJ1W1FeqX33kob9Cntj-2Fs165M9I6xz1kEecwJm1IrETCaRvNCJAywArJSkmDFWU1nwcyZZ"><img src="https://www.gravatar.com/avatar/b869f93fb5ae392a80da9f9120112788?size=240&amp;default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_b_v2.png" style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
" alt=""></a>
</td>
<td style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsTJiJVSP-2B84x4PI-2BusgunwhTMOjAuQIQkvchZx3fRcLqv3lXGe0w6rLPxf6xUemsfo7oGUxqQALZqipCdOYFFtw-3D551l_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP0t21CDxLvfbGQkjEvjcHwGwD2qALReFk8oY6G0bi137MNGQAlkNWibJgm4CTqOUkz-2Fz1j-2B244SapClcbuVpzzzn9wH4m-2B0AwLnUgPY8pXitZGsVB92zOKNqxVem9fEKGGnpjkcVECvn0lr0UHB4PA7ADx5eEuyELIjXAdN0cLRiPTae0T-2FzNOoJAyEU-2FME1JeVDyRqedq7mF8GrVnu0f2072BwSGqUnUKDpsk-2B3ufmMWqUs4n-2B-2BzV6wIINb9TH9GfeLzZtsog67UgBmvntV6sVO5-2Bx18cp-2BFn0MXvt-2FDkLraVFQgtfo6hV-2FEEDpCIFGU7wgtUTBfoVlAUEWKJ-2BUu41">bodas67661</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
">
I'm a developer, not a designer, so I don't know how things work.<br>I want to add this library to my project.<br>When I open it, I see hundreds of components (on the INSTANCES pages), and only 6 components (on the COMPONENTS pages).<br>When I publish this library to my project, and open it in the assets section, I only see these 6 components. But I don't see all the others, starting from a simple “Chip” and ending with “Data Grid”.<br>Am I doing something wrong?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table width="223" align="center" style="margin: 0 auto" cellpadding="0" cellspacing="0">
<tr>
<td class="active-t" align="center" style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
">
<a style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsTJo-2BLVUsorfX8IHDaXVlF7MaHp4bCRHbTUWk50AiMcFQ9J7GLIS0Cli4FhUIPvcYM5vbzZT71z73PAmT3-2B6Tms-3DTlxY_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP0t21CDxLvfbGQkjEvjcHwGPf9oE2z06reLtr-2FC990CR5Nl1tC1M9ZDSW27HC23IBE7VlSAzUYECxWa7AvaOYTJdvYhvks-2BFmK-2BjTA2f1v8MmlSrhEgKuAzTk-2F2yaPn-2FfMsTAZ2umAi4afC9oZRwtEDtB1-2F4D2IxdqAay3GD3pF0ChCQzp-2BrBm-2BoEYOj4yJQF3klGqCAqjtPGuFNh48p9-2FXdbt8kx6ceQ8VdONhZNQRcVawqZvwtf6mwrjaWeaAAVpflUk13O6YVCnQ7x7F0rcY8BD77ta8GB6YUCM6pwzjd5KparE9Xj-2FfhOoFYdTp29RSeQ2yXHxPFF84a5AnKtUe">Reply to comment</a>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
Answered on the community channel.
