### ISSUE TITLE
ListItem Divider not visible in 5.17.0 or 6.1.0

### ISSUE THREAD

**Issue by olivier-g74** [mui/mui-design-kits#423]
### Steps to reproduce

Steps:
1. Go to page Data Display / List
2. Go to section Divider:True
3. Zoom in and try to see a grey line

### Current behavior

No line to be seen

### Expected behavior

One can see a line 1 px thick and color Divider, like it was in 5.15.0

### Your environment

| Software            | Version               |
| ------------------- | --------------------- |
| Design file version | v5.17.0, 6.1.0             |
| Design tool         | Figma |

**Search keywords**: ListItem, Divider

**Comment by adrianmanea** [comment]
Hi Oliver, you are right, thank you for reporting this, this is the annoying part when working with absolute positions. To solve this is super simple, select all <ListItem> instances and **deselect** the Clip Content.

**Comment by olivier-g74** [comment]
Thank you, I shared the workaround with the team.
