### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Fachihul Alam

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#426]
<tr>
<td class="wi-100p pb-30" align="center" style="padding: 0 0 52px">
<img src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792" width="392" style="width: 392px; vertical-align: top" alt="">
</td>
</tr>
<tr>
<td class="pb-30 plr-8 fs-24 lh-28" align="center" style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
">
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td class="ptb-20 plr-25" style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
">
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2Byqtsb0fDl0LCXTF9vf2U44sTYVGT7Naf8JEW4pmkdsohJN1SezRn6Lt3j8D0l6D5y-2FSDC8jJYSLH3YMrPLD-2F0QoFsg-3DQPfN_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2FtRz3A6UlpIaGnO5OjBVtUECRzHlhl-2BmlkfE9n8PPIZXstFhwKhlj4gJ1pxUkWdBXsMIkjYrD211oJLoPR-2BW3P-2BMOSfDqPUYq89EbGH754qImHkJsf-2FpVDraOgNQ7RKIfsN-2BwRz6wBSUjH0zOt0aPjiM0lWewUXvRZcSGHoCUOxsNfYmUnj8Fz9MF1tGipkeDVBoj3O2rMCgUWBxjsaqfO4zbgXCCl0r9RPKrevHyueL0mUwBqEgcsBYAKZ9kIFsSN3KGqUcHkfKZAaqvk4KCKEm6UEuXI1gEABwHlQkESfUltiFAUsnAhkV4ExIyMj1qr7NoGDC9aw-2FHOgFDq5xW"><img src="https://www.gravatar.com/avatar/6c1c800ec0f4c160654d8d2a782b3c05?size=240&amp;default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_f_v2.png" style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
" alt=""></a>
</td>
<td style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2Byqtsb0fDl0LCXTF9vf2U44sTYVGT7Naf8JEW4pmkdsohJN1SezRn6Lt3j8D0l6D5y-2FSDC8jJYSLH3YMrPLD-2F0QoFsg-3DPPLj_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2FtRz3A6UlpIaGnO5OjBVtffBT6nTGpZcHhANNSE0FFCEgR7cGpEUBk6nxGorEtTPcgW-2FxwPvcOVOMZWk8LGA-2B-2BYIH4txKj3epAGgnW2jliRXYVpJVMcYqj46Yrc7ybwEdmknGZqgLE6jny2QyJ1-2BKKROCFdQxEix7xgEwm6ZmYq332MAHZJ58RnLnlamNbccH33w1wB9Zd0v0V60zU40flqM2-2BMMIVRCjPhgT31VBHK0alpst07vd-2Fc9HIDVSc07CZ76bV5GA9KQlzlDuHsyGQC2p16ZobXAcsr0fl0mgthrp018I1ZEngTqc5ap-2FZpjGkinAwMECPnNcz2livfDU">Fachihul Alam</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
">
Can I use the free version commercially without facing copyright problem?
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table width="223" align="center" style="margin: 0 auto" cellpadding="0" cellspacing="0">
<tr>
<td class="active-t" align="center" style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
">
<a style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsallcnU4rE4t0zGzeSVF-2Brpks7GfTN2hj4JevMPOlQocYkKbPySWxOu858x-2BOEXJJAKzeSiUuKjI2jxWnq0gGPw-3DHyB8_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2FtRz3A6UlpIaGnO5OjBVtvn7aaOSEanyO6tgoOrvv03bu-2BllwRUEdG5Fh0koW1h4WmPwPXHxv2pP7IvNTHJtPP0r851pdNCb05caEZSEmIH-2F4rmRly3RBH-2FcpONLL2Zb59-2B7ZECnMM2YiYfWrkyDTRx-2BbPvDi1RhINPAYmEhF4f-2BEr2sJwgWMGG0BzZWmYNu8lOQALt2L0z6sQynYQqmha56tNTlXxbWgbiC9W6PLX3U6ohY7-2F-2Fj-2Bf0JGpCuFX-2BrOrhGzIhd3Q-2BQAcn0qhajyXuxjcmz7sqz8hh9xXllPaM2PNxTF1lmCRkiACvs-2BGdsrVJ3nh6My9r-2FbDxA7cx-2FU">Reply to comment</a>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
Answered on community!
