### ISSUE TITLE
[figma][question] where can I find detail changes in MUI Design Kits v6.1.0?

### ISSUE THREAD

**Issue by Oscarf77** [mui/mui-design-kits#427]
### The problem in depth

I've been using the 5.14 version and making changes and customizations that at this point it's not feasible to integrate the new updates as i'd like to be up to date. In the changelog, it doesn't specific detail changes. 

Support Material UI v6.1.0 - **What are the updates here?** and **what can I do to integrate the changes to my current library?**
Support MUI X v7.20.0 -**What are the updates here?**
Fixed Select focused state not showing correctly **in what components does this changed happened?**
Fixed Table examples - **What are the updates here?**

If I have customized a library and I want to integrate new updates from new Kits does the swap option works without overriding my customizations?

Let me know if you understand the issue I'm going through.

### Your environment

I'm using version 5.14 that has been heavily customized and I have manually added updates from version 5.16 and 5.17 

**Search keywords**: Design Kits v6.1.0

**Comment by adrianmanea** [comment]
Hi Oscar, we if you are on the 5.14 I don't think it's worth the time to update since we haven't changed a lot of things in 6.1.0 except what we mentioned in the changelog. If you have a customized library you need to apply those again to the new file and use the Swap Library feature.
