### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Aurélien BARBIER

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#434]
<tr>
<td class="wi-100p pb-30" align="center" style="padding: 0 0 52px">
<img src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792" width="392" style="width: 392px; vertical-align: top" alt="">
</td>
</tr>
<tr>
<td class="pb-30 plr-8 fs-24 lh-28" align="center" style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
">
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td class="ptb-20 plr-25" style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
">
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsWUZtwcHmvA2KFevb3j7wZKvrSa1OkrKbvl-2BNDw4IRpTHeojTf-2FGz0f3EtvCz-2FIPpELXSS0VhJh5V1LN4Vh2APKbN8WEZXd6WM2ULl6cad8DdVx7_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP1GPlbcsl9b2YoZnFzkIed32MMtFzPH1vWUWOtr7Vfvqg1IK-2FHEiRtUaeB1ovUPM6ybO5d40sFAD221Pzsp4H8BQW7TukVRtZIWDGp22c1QQlmHIdJ-2FAbLjpeUD0GrP3gEM4LqZd4KnZu-2F0mB-2Fn3KbtfJ9hxoGwe33EAaV49N14SODcGZzkcjXso2Aoe2QW-2F-2BezTYHayv4A2X5-2FN8UUm2UHwt2NesqhUm81g7aakXOVUGZZNpnoPzm3fKTPftQMSXIRkctSdx6yJC2KbCQztBuqLxtiLOfI42lKdj82WBKa1TXnI-2BW9qqN3xxjwE3-2B-2FMNwzL4S-2FwwJCIFQWMYbohX3x"><img src="https://s3-alpha.figma.com/profile/a7ec3e6b-ac4c-4ca1-8205-1cbde19881d4" style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
" alt=""></a>
</td>
<td style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsWUZtwcHmvA2KFevb3j7wZKvrSa1OkrKbvl-2BNDw4IRpTHeojTf-2FGz0f3EtvCz-2FIPpELXSS0VhJh5V1LN4Vh2APKbN8WEZXd6WM2ULl6cad8D0eQD_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP1GPlbcsl9b2YoZnFzkIed3Twm6qZtU0z926hEdRB8eni4H4tly0MmdYrdVD8iIz45UUY3q70N5Vvjrs8bVkxjfUsWoXkl0kryKsCZ89RcKwpzLXKozyf23OgYB6k1W8VDEwca84hPnDwxQ3Bt8reYDXLmFj2rPDBxAoeohwU9-2BAeTIucWJciaIReitR0fAJHlH93UokyTRZ4T6OSBcmzi8hxZrY20ChB40wjH6tNfm4qkd3MYLLeSjuGi5U8PRDDXtSYe1x2DFNCarw6JbrDrznC75EQV5HXkEM5zabyLLtykdyLFxjpI-2FHVjGVzVa6Zfpl0PWvy7dNlLdK34qQXxC">Aurélien BARBIER</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
">
Hi, Thanks for this Figma file. <br>We have a problem to use the free version, we can't use variables to change the color, please could you tell us if it's normal ? Maybe it's a paid version option ?<br>Thanks in advance :)
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table width="223" align="center" style="margin: 0 auto" cellpadding="0" cellspacing="0">
<tr>
<td class="active-t" align="center" style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
">
<a style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtscNNdahsH-2FbM1AR1-2BD7pqxtwkzQSvoSzqvgBL4EWSwt6ohq9aSkqt5-2FOSI1QGtGz8fSWOQwhTCMFvAHGaOYb-2FPM-3DOscZ_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP1GPlbcsl9b2YoZnFzkIed3-2FuDhWBUxnBF-2BjnIKwM27g7A-2Bt9TP8z03wEYwO96xF-2BOyfy2A5kIElt7MtloDHwgeT0fzBmBBaarfGGX9Adk8rm5AYqaQvV836P9wnDrjywiFD5sRsLu2GYvFtgdjnufSAvorVQhWm-2FixHkgdnYTN8ZWlwhs58sMadl3hgk2uHU4ld7u-2BnvqRAPkLeaaaNbDS-2B0rM87f7vddFsQAviRTpOuOwWsvDpNsAV43JahfKp1kl34MniRQwWFToeQFoaVP9NPvPw28-2FpDcdDeZBRNS2FKAg39R4cwPp2UBOaJmMdz0u4U6MS1L9c4HmZJm3X14u">Reply to comment</a>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment]
Answered on community!
