### ISSUE TITLE
[figma] Memory usage high

### ISSUE THREAD

**Issue by adrianmanea** [mui/mui-design-kits#47]
One of our designers has experienced a [high memory usage alert](https://help.figma.com/hc/en-us/articles/360040528173) in Figma.

The entire library does feel a bit laggy on an 8GB machine like an MBP 13 2018. Seems like it takes 2.8GB of RAM when having just the MUI for Figma opened. If users have multiple tabs opened it might cause problems.

![image](https://user-images.githubusercontent.com/5917515/151545621-87bcc9e6-b063-4b07-a859-218ef9cc36ca.png)

## Solution

Close other Figma files when working inside the library.

## Your Environment 🌎

v5.2.0

**Comment by oliviertassinari** [comment]
How does it compare to v5.0.2? It also feels a bit slower on my laptop

<img width="183" alt="Screenshot 2022-01-29 at 18 38 16" src="https://user-images.githubusercontent.com/3165635/151671323-a76f5186-a177-4874-a978-6581a9a6ba00.png">

**Comment by adrianmanea** [comment]
Below is the 5.0.2

![image](https://user-images.githubusercontent.com/5917515/151757084-5eb47e46-1a90-45b4-9345-3e039048de2b.png)

Notice the presence of the new Focused state which takes advantage of GPU.

**Comment by adrianmanea** [comment]
Solved in the upcoming update.

**Comment by oliviertassinari** [comment]
Did you use a special trick to solve this?

**Comment by adrianmanea** [comment]
By just reducing the huge amount of variants we solved the RAM issue! Good call, will explain the issues solved as well.
