### ISSUE TITLE
[figma] Improve coverage of data grid

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-design-kits#48]
### Ideas

It would be great to add coverage for:

- [x] A clear separation of the data grid community and pro and premium
- [x] Column panel
- [x] Column menu
- [x] Toolbar
- [x] Filter panel: While the filter feature is still a WIP, we are currently far from happy with the UX: https://github.com/mui-org/material-ui-x/issues/3140, once fixed.

### Requests

A list of user feedback:

- Review from @thunderpigeon
  > I bought it large because, I needed the datatables & tables. So, I was a bit dissapoinet that it was not so ellaborate in terms of features and reponsive. Like the prints, filter features are all missing.
Otherwise, seems like a good purchase.
- Comments in https://www.figma.com/community/file/912837788133317724?comment=1138868874312027233
  > however, there is no data grid pro page - only data grid. can you please add this?
- Comments in #107
  > why is the data grid pro not available?

**Comment by adrianmanea** [comment]
We now have more examples for Data Grid / Tables: https://www.figma.com/file/cICEsU6eNdiTawOEiFO5Or/MUI-for-Figma-Material-Pro-v5.9.0?node-id=6603%3A52282 - planning to add more examples.

**Comment by oliviertassinari** [comment]
@adrianmanea great thanks. Let's see what designers are asking for the most frequently. It will help us prioritize the most important features of the data grid to cover. I'm also adding @gerdadesign to the notifications loop, as our MUI X's designer.

**Comment by oliviertassinari** [comment]
I'm not sure that we covered the Column menu:

<img width="392" alt="Screenshot 2023-03-01 at 15 56 08" src="https://user-images.githubusercontent.com/3165635/222176810-48af243b-0453-4086-8a87-7c1a90efc2a9.png">

https://next.mui.com/x/react-data-grid/#mit-version

but maybe it's not very important. We can wait for requests.

**Comment by adrianmanea** [comment]
Ah, yes! Will keep this one for the next release.
