### ISSUE TITLE
[figma] Add a spacer component

### ISSUE THREAD

**Issue by adrianmanea** [mui/mui-design-kits#51]
## Idea
Add a spacer component with pre-defined widths and heights.
![image](https://user-images.githubusercontent.com/5917515/153605655-a5532dd9-9ef8-4e2c-a379-5de463e53fc7.png)

Should we replace the paddings with spacers? Or just use them in layouts.

## Benchmark
IBM Carbon Design System (https://www.figma.com/file/kbaAuFUvEWhoPLWIersWf9/IBM-Carbon-Design-System-(Community)?node-id=0%3A4149)

**Comment by oliviertassinari** [comment]
Related to https://github.com/mui/mui-design-kits/issues/30#issuecomment-1005579509

**Comment by adrianmanea** [comment]
Added in the 5.8!
