### ISSUE TITLE
[sketch] Chip sizing broken

### ISSUE THREAD

**Issue by mikekotsch** [mui/mui-design-kits#52]
Since I updated Sketch to 83.2 the *chips w. thumbnails* are not resizing with the content. Old chip components changed to the default width too. I'm using v5.0.0.

**Comment by adrianmanea** [comment]
We're working on an update right now. I'm adding this one to our list, thanks! On the 21st of this month (Feb) should be deployed. Thanks for reporting.

**Comment by mikekotsch** [comment]
Thanks for the fast response, this is what I'm seeing when I open the downloaded _(Light)Material-UI for Sketch_v5.0.0.sketch_: 

https://user-images.githubusercontent.com/5254934/155152215-3e98c1ff-e367-43a7-95e5-fbdbfd3a771e.mov

No matter if I'm changing the text inside the chip or through the value input in the inspector panel, the chip isn't resizing. Neither here, nor in documents that have this document added as a library.

Hope this helps 🤞

**Comment by oliviertassinari** [comment]
It's broken for me too on Sketch v83.2 with the Sketch for MUI v5.0.0.

**Comment by oliviertassinari** [comment]
Fixed in v5.4.0
