### ISSUE TITLE
[figma] Tree View items don't align properly

### ISSUE THREAD

**Issue by brookssolveig** [mui/mui-design-kits#55]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

In Figma, when Tree List items receive nesting, the text appears at a different indentation depending on if they have a dropdown or not. 
<img width="1095" alt="Screen Shot 2022-02-28 at 1 35 33 PM" src="https://user-images.githubusercontent.com/11778900/156066721-7941bbfc-49db-428f-b903-a9cb25e96f7d.png">

### Expected behavior 🤔

Figma should match prod. In production, the text of Tree List items display at the same regardless of whether a dropdown is present in the item.
<img width="994" alt="Screen Shot 2022-02-28 at 2 11 22 PM" src="https://user-images.githubusercontent.com/11778900/156066959-6f27151e-cc97-4535-a1c5-166bb9c3d121.png">

https://mui.com/components/tree-view/

### Steps to reproduce 🕹

Steps:

1. Use the Figma file.
2. Notice that text doesn't align between Tree View items of the same nesting level.

### Context 🔦

Provide pixel perfect specs to my engineers.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by danilo-leal** [comment]
Hey, @brookssolveig, thanks for the heads up! I've moved the issue to the design-kits repo — we've been trying to centralize issues regarding them in this separate space for better coordination, so feel free to come here whenever you bump into things about it.

cc @adrianmanea

**Comment by brookssolveig** [comment]
> Hey, @brookssolveig, thanks for the heads up! I've moved the issue to the design-kits repo — we've been trying to centralize issues regarding them in this separate space for better coordination, so feel free to come here whenever you bump into things about it.
> 
> 
> 
> cc @adrianmanea 

Awesome! I'll post here next time.

**Comment by adrianmanea** [comment]
Updated in 5.9.0, now items are aligned properly but the values are a bit strange, child items have a 17px margin-left, I wonder why 17 and not the usual multipliers.

**Comment by oliviertassinari** [comment]
> I wonder why 17 and not the usual multipliers.

@adrianmanea True, the spacings look quite strange in v5.10.0:

<img width="424" alt="Screenshot 2022-08-15 at 00 15 37" src="https://user-images.githubusercontent.com/3165635/184556842-edd0943f-8fd7-4f13-859b-480b8ecd2f37.png">

https://mui.com/material-ui/react-tree-view/#controlled-tree-view
