### ISSUE TITLE
Possible 'bugs' with Avatar and Badge Variants (v5.4.0)

### ISSUE THREAD

**Issue by moorefficient** [mui/mui-design-kits#59]
The Avatar Variant only includes a 24px and 40px size, and I required a larger one for a particular card design. I used the MUI spec example of a larger 56px size Avatar, and decided to try to add that as a third larger size to make the component more useful.

In doing so, I ran into an issue with the Constraints for resizing/scaling on the *Badge* associated with the Dark set of the Avatar. I also ran into some confusion on how the Badge component was applying the Color tokens. (It appeared to be set to 'Primary'--which was still the blue color, as I had not customized it--but the Variants grid was displaying all green-colored (Success) badges despite being set to Color: Primary. This could be my own misunderstanding or user error, but when changing the Color Variant around a bit, it did end up setting Primary to the blue color as you'd expect. 

To recap: two separate issues related to apparent 'bugs' with the Avatar w/Badge Variant:

1. The Dark version's badge doesn't seem to scale properly (like the Light version)
2. There's some confusion (for me) as to why the Color: Primary (as blue) Variant is showing the Success (as green) by default

I purchased MUI for Figma v5.4.0 so as not to have to troubleshoot and build out these things myself, and as a non-expert (as of right now) with Design Systems, I may just be doing it wrong. But the fact it works one way with Light version and another with Dark (i.e. for badge resizing) makes me think there is an issue. The 'clash' of the token colors is just so confusing, I can't honestly say if I'm doing anything wrong, just misunderstanding it, or if there really is some strange bug/conflict thing going on with how the Variants were initially set up and using the Badge's color system by default.

Loom: https://www.loom.com/share/137133db6cc74fca9f0a691af62e9c32 

[Unrelated Comments]
P.s. - I agree with others that I was a bit disappointed to see that even super basic screens and layouts (e.g. sign in screen or simple grid view or simple dashboard or whatever) were not included in the premium Pro set. I want to love this...and it looks great on the surface...but in actual usage, so far I am having second thoughts of 'doubling down' and really investing in it.

P.p.s. - I am also quite concerned about breaking changes and updates. One of the biggest reasons I was excited about MUI for Figma is because I assumed it'd be a great way to keep a Figma-based Design System in sync with MUI (for development) over time. But that just doesn't seem to be the case, right?

**Comment by oliviertassinari** [comment]
@moorefficient Thanks for the feedback. Here is a summary of the changes that I understood we should do:

1. Fix the padding of the avatars with the badge:

<img width="142" alt="Screenshot 2022-05-27 at 00 21 13" src="https://user-images.githubusercontent.com/3165635/170589176-e7c283c6-19ac-49c0-bc70-5870a3366c86.png">

It doesn't make sense to have 8px, it should be 0px.

<img width="151" alt="Screenshot 2022-05-27 at 00 21 40" src="https://user-images.githubusercontent.com/3165635/170589215-d668d089-535e-4822-99c3-89a1b1021454.png">

2. Fix the size scaling of the badge. The badge's size shouldn't scale with the avatar, it should be of fixed size, like in https://mui.com/material-ui/react-badge/#badge-overlap.
  KO (current):

  <img width="327" alt="Screenshot 2022-05-27 at 00 23 32" src="https://user-images.githubusercontent.com/3165635/170589473-8df98291-74dc-4778-9240-4eef066547ea.png">

  OK: 

  <img width="340" alt="Screenshot 2022-05-27 at 00 24 55" src="https://user-images.githubusercontent.com/3165635/170589504-2b827ecf-eb48-4026-aca3-5de1fc0834c2.png">

  It would also fix a scaling issue:

  <img width="235" alt="Screenshot 2022-05-27 at 00 30 47" src="https://user-images.githubusercontent.com/3165635/170590204-3c120cec-5f35-4650-804e-ab547584c846.png">

3. Fix the name of the badge color variant. It should be "success", not "primary":

<img width="339" alt="Screenshot 2022-05-27 at 00 33 13" src="https://user-images.githubusercontent.com/3165635/170590478-f3a66e74-c670-466a-9708-a14eab1e9658.png">

cc @adrianmanea in case I have missed something

**Comment by adrianmanea** [comment]
Solved in the 5.9.0.

**Comment by oliviertassinari** [comment]
Great thanks
