### ISSUE TITLE
Publishing updates always fails

### ISSUE THREAD

**Issue by ace-reef** [mui/mui-design-kits#64]
We're using the base MUI kit the way it comes, but we're updating some styles to fit choices we've made to alter the look/feel of MUI. I haven't yet had a successful publish, which leaves me having to copy/paste instances out of the original file, which ain't great.

<img width="518" alt="image" src="https://user-images.githubusercontent.com/100724643/174672988-70a744eb-9b4b-418f-9b58-7b96b34cf8ab.png">

<img width="259" alt="image" src="https://user-images.githubusercontent.com/100724643/174672960-8e94e193-23dd-42c7-a117-bb49cbc18da7.png">

**Comment by adrianmanea** [comment]
Hi, it usually takes a ~2-5 minutes to update the whole design system especially if you are pushing a high-volume pack of changes like primary color.

Can you try leaving the window on focus while it updates?
