### ISSUE TITLE
[figma] Integration with the Figma Tokens plugin

### ISSUE THREAD

**Issue by LincAtMerkle** [mui/mui-design-kits#67]
Hi there,
Will you be adding Design Tokens to the Figma UI kit?

My use case is: 

1. I'm using [Figma Tokens Plugin](https://www.figma.com/community/plugin/843461159747178978/Figma-Tokens)
2. Have to import the UI kit's Styles to Figma Tokens

Would be better if I could:
1. Import MUI Token.json file/s to Figma Tokens
2. Have a MUI Figma plugin that accessed Figma Tokens API
3. A Figma Tokens MUI generated library already existed and I could just use it.

### Benchmarks

- https://www.antforfigma.com/docs/introduction-to-figma-tokens-sync

**Comment by adrianmanea** [comment]
Hi there, thank you for the suggestion. Having the design tokens as the default theme is on our list for the upcoming update! Covering the nice-to-have points requires a custom plugin, which is something that is still being discussed -- might happen soon!

**Comment by adrianmanea** [comment]
Great idea! Unfortunately, we had to release the 5.9.0 without the design tokens but we will add in the next one for sure! I'm not sure about the release estimation. Will keep this issue active.

**Comment by LincAtMerkle** [comment]
That’s cool.
Would be awesome if this aligned with MUI base using design tokens too.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by oliviertassinari** [comment]
@LincAtMerkle I would love to know more. What's your use case for [Figma Tokens](https://www.figma.com/community/plugin/843461159747178978/Figma-Tokens)? From what I understand, there are different classes of use cases:

1. Fill the gap of the types of Figma support as tokens, e.g. border-radius
2. Create derivate values, from existing values, like doing Math
3. JSON Schema exports/imports, with sync.

For context, we are looking to fix point 3 with #10.

**Comment by frassinier** [comment]
@oliviertassinari All of them! 

And I would like to add a use case: be able to integrate custom design tokens.
We built our MUI theme, and now we want to make more semantic design decisions.
`Chip` can be used for a new component, ' Status`, for example, letting know to the user that a feature is in "beta".
I need to store more design tokens than the ones offered by MUI theme, by default: `Light/Beta/Main`
And this new design token will be part of our MUI theme for convenience.
Using that plugin, I can augment that MUI theme and keep it in sync with the codebase.

**Comment by oliviertassinari** [comment]
This issue is also related to https://twitter.com/matsugfx/status/1575105271055060993.

**Comment by frassinier** [comment]
Correct Olivier!
That's why it could be nice to define those MUI theme properties for once!

**Comment by adrianmanea** [comment]
We should hold our breath for the upcoming https://schema.figma.com/ regarding Figma Tokens implementation. Rumors say that we might get a native tokens solution 🤤. Even though I really like Figma Tokens plugin I feel it's still buggy and one can mess up a lot of things In a very short time.
