### ISSUE TITLE
Layout Grids - Extended, False and True?

### ISSUE THREAD

**Issue by Oscarf77** [mui/mui-design-kits#68]
Can you clarify what this is?

When I used one of the layouts there are 3 layout structures. For instance, Extra Large (1536+px)

"Extended" @ 2048px with a red section (is this a space for a Drawer component?
Then you have "False" at 1920px with just the 12 columns
and "True" `@2028` with a minimized drawer column?

Just need to clarify what Extended, False, and True are.

Thanks!

**Comment by Oscarf77** [comment]
Any comments?

**Comment by adrianmanea** [comment]
You are absolutely right. The 'extended' is showing the guides of your main layout, e.g a Left Navigation and/or a top bar. Note that these are only examples and are meant to be personalized.

**Comment by adrianmanea** [comment]
We've deleted the Extended variants since it might get confusing, but we've done some examples for these use cases where one would like to show the layout structure as a grid.
