### ISSUE TITLE
[question] Why can't I clip content with MUI components?

### ISSUE THREAD

**Issue by rheamajumdar** [mui/mui-design-kits#70]
I am making an email-like frame similar to the one on Outlook and am trying to do overflow scrolling with the left side (see attachment). They are all within the "Ship Updates" frame and are grouped by frame as well as "Updates". For the overflow scrolling to work I need to adjust the frame (like I did on other frames in the same project); but every time I click on clip content and adjust the frame to the larger "Ship Updates" frame, the components become tightly crowded/bunched up. I want to maintain the original look while keeping the other information out of sight unless a user decides to scroll. Please advise.

<img width="589" alt="Screen Shot 2022-08-02 at 12 39 51 AM" src="https://user-images.githubusercontent.com/90526177/182294656-bc31bf66-0e78-4fc2-890e-feb9e4bee0bb.png">
<img width="240" alt="Screen Shot 2022-08-02 at 12 40 10 AM" src="https://user-images.githubusercontent.com/90526177/182294665-9d30a42e-38ce-46f2-b6db-db882825887a.png">
<img width="239" alt="Screen Shot 2022-08-02 at 12 40 16 AM" src="https://user-images.githubusercontent.com/90526177/182294672-0668984c-52a3-48da-a308-4e308bf161b4.png">
<img width="585" alt="Screen Shot 2022-08-02 at 12 40 30 AM" src="https://user-images.githubusercontent.com/90526177/182294678-3e1d95e2-5987-457e-ad7b-4aa1fee87177.png">

**Comment by oliviertassinari** [comment]
@rheamajumdar I assume that you have found a solution. I could find https://www.figma.com/community/file/1043327063660860416 and https://www.youtube.com/watch?v=3ZWZk6pHEjo that might have helped.
