### ISSUE TITLE
[figma] Wrong outlined disabled style

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-design-kits#72]
### Current behavior 😯

The border style should be solid, not dotted. The border color should be darker.

<img width="246" alt="Screenshot 2022-08-14 at 12 17 59" src="https://user-images.githubusercontent.com/3165635/184532472-fa5acc09-19ff-499e-b5a2-b7a32f7b38ec.png">

https://www.figma.com/file/EliRYpocPtcjKCP6zR349B/MUI-for-Figma-v5.9.0-(Community)?node-id=5448%3A69602

### Expected behavior 🤔

<img width="239" alt="Screenshot 2022-08-14 at 12 17 34" src="https://user-images.githubusercontent.com/3165635/184532464-1e4d9b03-7e1e-4acf-aa26-e7a840f8139d.png">

https://mui.com/material-ui/react-text-field/#form-props

### Context 🔦

The bug reported was reported in https://www.figma.com/community/file/912837788133317724?comment=1132261545761186112. Out of curiosity, I had a look at what the specification says:

- Material Design v2. What we are implementing with Material UI v5

  <img width="362" alt="Screenshot 2022-08-14 at 12 18 53" src="https://user-images.githubusercontent.com/3165635/184532498-dc9c9393-40c0-4e85-b165-80b440a2913b.png">

  https://material.io/components/text-fields#outlined-text-field

- Material Design v3. What we might implement with Material UI v6

  <img width="222" alt="Screenshot 2022-08-14 at 12 23 51" src="https://user-images.githubusercontent.com/3165635/184532659-d9d3d1ed-53b0-4a2c-8967-11505c35f345.png">

  https://m3.material.io/components/text-fields/specs#28125724-06e2-48bc-ab9f-da8428190a14

### Your environment 🌎

v5.9.0

**Comment by WilliamZimmermann** [comment]
I have the same issue. Any plans to fix it?

**Comment by adrianmanea** [comment]
Hei William, sorry for the trouble. Here's a 1-minute video on solving the issue:

Uploading MUI-F 4.9 - Fix Mismatch Outlined Inputs.mov…
