### ISSUE TITLE
New comment on MUI for Figma (Community) by Alejandro Mendoza

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-design-kits#95]
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DEbLZ_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMHO0IIhRFN7s5xgNoRvQq0IO6g2qHx1vVDaRgiJhTk-2F9DLeg88oD4LvtbCrrEn3iAp7-2FU41mEbPujsA7jXjgTVr-2FoKzR5ItFwfN4Wr1Bt8kySy6MVlNcnemEeCGQ-2FfNO7sxJZ9uUYdlEcFnaqTTBBTTyeSojHiSsIA2qutoH0ISgGrsX8wvFXDPbIBYcZHcKpCtNQKoRKijduKky7VrxoqEOrylDbpcFOKwVedT83Jng-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on MUI for Figma v5.9.0 (Community)<b>MUI for Figma v5.9.0 (Community)</b>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kroxmMz9XNfrI78EEYUIWo8AW-2BFmVuNFyUBaAlOPOTg-2BgV7G8R_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMHO0IIhRFN7s5xgNoRvQq0Jkf5M651F6JlG2I8l-2BCpwhE5QlhTuFAhVxIVgHyRRPZ3FuXJt1D3xPra4vSYF0xWNQjnGdu5bd9P9AFzVjLKyMQ2yQPGLE37e-2FvHM-2F4OdGh2nqRXWK119UbFil3TIXFKNFBhckQdrlYtnDmrm3u4p9QElU8oJ6mWEIza-2FGJLNtH3uoXGYII-2BWACSHiEqAP2jb-2FglmwvUooro-2BV5060thhw-3D-3D"
><img
src="https://s3-alpha.figma.com/profile/d21f4306-6275-4356-b315-9aa442f0ff4e"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kroxmMz9XNfrI78EEYUIWo8AW-2BFmVuNFyUBaAlOPOTg-2BgV8hpr_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMHO0IIhRFN7s5xgNoRvQq02ojXg0g3fuWr-2FWdj091-2FPuoaQOaq84oS3A2gW-2BrNZlQ1J8DS2gkFu4CG8rshEXNFRxHIIIcKPm26FaedNX0KR75FZaT-2FooBf75vyOfggZie8dnu1xJOqOoAIeR1yAjNRu5IeUuq9VY6D4B0i6nr-2FA1jw9YiFHQAqXiHt-2BVd9QFwSrsOEQax4qCul7ByKzP-2Fu7hoMGC5vlsMB2pSKA5ZhUQ-3D-3D"
>Alejandro Mendoza</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Do you plan to make new releases of this version? zaldrian
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfL4TxD2nyQ5DuuqgQtI9rrIJ4JItWIIXhNcx92hyfdBHkJgT_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmMHO0IIhRFN7s5xgNoRvQq0o-2FkdPo2YVb0AorztGqIgmO5F-2FmXQgBxK3xlyrRoB3NWRoy-2F6Y-2FESEmNiP-2FuQPzw21-2Bs2GSN7bdb1DaWMH2To4yoeIETqAFnGCod-2Ff6Peg-2Fc2K5TgdJ-2FVxqrCdF287ORvVwiH8FiCKwAW-2Fh-2BnW3tAwuvJWp2Li79FE0Q-2Bwz8oSxl-2FlL56Vayjv6Hy9ydFzsr-2F7ZD6OOY5soAn3c5kOcpu6w-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by adrianmanea** [comment]
Yes, we are already working on a new update. Do you have any requirements or issues with the current one?
